/-
Copyright (c) 2026 Robby Sneiderman. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Robby Sneiderman
-/
import FormalSLT.AnytimeValid.CountableEProcess
import FormalSLT.PACBayes.ForwardPredictableStrategyPACBayes

/-!
# Countable predictable-strategy PAC-Bayes master process

This module forms one countable master e-process from a predeclared
`Nat`-indexed catalog of predictable tilt strategies.  Each catalog atom is a
finite model-prior mixture, and the outer weights are fixed, nonnegative, and
normalized before the path is observed.

The strategies may depend on the observed past, but every strategy must be
predictable.  This module does not permit post-data changes to the outer
mixing weights.  Downstream results may select a declared strategy atom on the
single event generated by this master process.
-/

open MeasureTheory ProbabilityTheory
open FormalSLT.AnytimeValid
open FormalSLT.PACBayesKL
open FormalSLT.PACBayes.ForwardPredictableTiltPACBayes
open scoped BigOperators

namespace FormalSLT.PACBayes.ForwardPredictableStrategyPACBayesCountable

noncomputable section

local instance (p : Prop) : Decidable p := Classical.propDecidable p

variable {ι Ω : Type*}
  [Fintype ι] [DecidableEq ι] [Nonempty ι]
  {mΩ : MeasurableSpace Ω} {μ : Measure Ω} {ℱ : Filtration ℕ mΩ}

/-- The finite model-prior component for one declared predictable strategy. -/
def countableForwardPredictableStrategyPACBayesComponent
    (prior : ι → ℝ) (X : ι → ℕ → Ω → ℝ) (risk : ι → ℝ)
    (strategy : ℕ → ℕ → Ω → ℝ) (j : ℕ) : ℕ → Ω → ℝ :=
  finiteWeightedProcess prior fun i ↦
    forwardPredictableTiltMeanEmpiricalBernsteinLowerProcess
      (X i) (fun _ _ ↦ risk i) (strategy j)

/-- The outer countable mixture over the predeclared predictable strategies. -/
def countableForwardPredictableStrategyPACBayesMasterProcess
    (prior : ι → ℝ) (weight : ℕ → ℝ)
    (X : ι → ℕ → Ω → ℝ) (risk : ι → ℝ)
    (strategy : ℕ → ℕ → Ω → ℝ) : ℕ → Ω → ℝ :=
  countableWeightedProcess weight
    (countableForwardPredictableStrategyPACBayesComponent
      prior X risk strategy)

omit [Nonempty ι] in
/-- Every declared predictable-strategy component is an e-process. -/
theorem countableForwardPredictableStrategyPACBayesComponent_eProcess_of_bounded
    [IsProbabilityMeasure μ]
    {prior : ι → ℝ} (hprior : IsFullSupportPMF prior)
    {X : ι → ℕ → Ω → ℝ} {risk : ι → ℝ}
    {strategy : ℕ → ℕ → Ω → ℝ} {L : ℝ}
    (hL1 : L < 1)
    (hX_adapted : ∀ i, IncrementAdapted ℱ (X i))
    (hstrategy_adapted : ∀ j, StronglyAdapted ℱ (strategy j))
    (hX_unit : ∀ i k ω, 0 ≤ X i k ω ∧ X i k ω ≤ 1)
    (hstrategy_range : ∀ j k ω,
      0 ≤ strategy j k ω ∧ strategy j k ω ≤ L)
    (hmean : ∀ i k, μ[X i k | ℱ k] =ᵐ[μ] fun _ ↦ risk i)
    (j : ℕ) :
    EProcess μ ℱ
      (countableForwardPredictableStrategyPACBayesComponent
        prior X risk strategy j) := by
  unfold countableForwardPredictableStrategyPACBayesComponent
  apply finiteWeightedProcess_eProcess hprior.nonneg hprior.sum_one
  intro i
  exact
    forwardPredictableTiltMeanEmpiricalBernsteinLowerProcess_eProcess_of_bounded
      (X := X i) (mean := fun _ _ ↦ risk i)
      (lambda := strategy j) hL1 (hX_adapted i)
      (fun _ ↦ stronglyMeasurable_const) (hstrategy_adapted j)
      (hX_unit i) (hstrategy_range j) (hmean i)

omit [DecidableEq ι] [Nonempty ι] in
/-- Every finite model-prior component is nonnegative pointwise. -/
theorem countableForwardPredictableStrategyPACBayesComponent_nonneg
    {prior : ι → ℝ} (hprior : IsPMF prior)
    (X : ι → ℕ → Ω → ℝ) (risk : ι → ℝ)
    (strategy : ℕ → ℕ → Ω → ℝ) (j n : ℕ) (ω : Ω) :
    0 ≤ countableForwardPredictableStrategyPACBayesComponent
      prior X risk strategy j n ω := by
  unfold countableForwardPredictableStrategyPACBayesComponent
    finiteWeightedProcess
  exact Finset.sum_nonneg fun i _ ↦
    mul_nonneg (hprior.nonneg i) (Real.exp_pos _).le

omit [DecidableEq ι] [Nonempty ι] in
/-- All declared strategy components share the same pointwise exponential
envelope at a fixed time. -/
theorem countableForwardPredictableStrategyPACBayesComponent_le_exp
    {prior : ι → ℝ} (hprior : IsPMF prior)
    {X : ι → ℕ → Ω → ℝ} {risk : ι → ℝ}
    {strategy : ℕ → ℕ → Ω → ℝ} {L : ℝ}
    (hL1 : L < 1)
    (hrisk : ∀ i, 0 ≤ risk i ∧ risk i ≤ 1)
    (hX_unit : ∀ i k ω, 0 ≤ X i k ω ∧ X i k ω ≤ 1)
    (hstrategy_range : ∀ j k ω,
      0 ≤ strategy j k ω ∧ strategy j k ω ≤ L)
    (j n : ℕ) (ω : Ω) :
    countableForwardPredictableStrategyPACBayesComponent
        prior X risk strategy j n ω ≤
      Real.exp ((n : ℝ) * L) := by
  unfold countableForwardPredictableStrategyPACBayesComponent
    finiteWeightedProcess
  calc
    (∑ i : ι, prior i *
        forwardPredictableTiltMeanEmpiricalBernsteinLowerProcess
          (X i) (fun _ _ ↦ risk i) (strategy j) n ω) ≤
        ∑ i : ι, prior i * Real.exp ((n : ℝ) * L) := by
      apply Finset.sum_le_sum
      intro i _
      apply mul_le_mul_of_nonneg_left _ (hprior.nonneg i)
      exact forwardPredictableTiltMeanEmpiricalBernsteinLowerProcess_le_exp
        hL1 (hX_unit i) (fun _ _ ↦ (hrisk i).2)
        (hstrategy_range j) n ω
    _ = Real.exp ((n : ℝ) * L) := by
      rw [← Finset.sum_mul, hprior.sum_one, one_mul]

omit [DecidableEq ι] [Nonempty ι] in
/-- The weighted outer series is summable at every time and path. -/
theorem countableForwardPredictableStrategyPACBayesMasterProcess_pointwise_summable
    {prior : ι → ℝ} (hprior : IsPMF prior)
    {weight : ℕ → ℝ} (hweight_nonneg : ∀ j, 0 ≤ weight j)
    (hweight_summable : Summable weight)
    {X : ι → ℕ → Ω → ℝ} {risk : ι → ℝ}
    {strategy : ℕ → ℕ → Ω → ℝ} {L : ℝ}
    (hL1 : L < 1)
    (hrisk : ∀ i, 0 ≤ risk i ∧ risk i ≤ 1)
    (hX_unit : ∀ i k ω, 0 ≤ X i k ω ∧ X i k ω ≤ 1)
    (hstrategy_range : ∀ j k ω,
      0 ≤ strategy j k ω ∧ strategy j k ω ≤ L)
    (n : ℕ) (ω : Ω) :
    Summable fun j ↦ weight j *
      countableForwardPredictableStrategyPACBayesComponent
        prior X risk strategy j n ω := by
  let C := Real.exp ((n : ℝ) * L)
  have hbound : Summable fun j ↦ weight j * C :=
    hweight_summable.mul_right C
  exact hbound.of_nonneg_of_le
    (fun j ↦ mul_nonneg (hweight_nonneg j)
      (countableForwardPredictableStrategyPACBayesComponent_nonneg
        hprior X risk strategy j n ω))
    (fun j ↦ mul_le_mul_of_nonneg_left
      (countableForwardPredictableStrategyPACBayesComponent_le_exp
        hprior hL1 hrisk hX_unit hstrategy_range j n ω)
      (hweight_nonneg j))

omit [DecidableEq ι] [Nonempty ι] in
/-- Pointwise nonnegativity of the countable strategy master process. -/
theorem countableForwardPredictableStrategyPACBayesMasterProcess_nonneg
    {prior : ι → ℝ} (hprior : IsPMF prior)
    {weight : ℕ → ℝ} (hweight_nonneg : ∀ j, 0 ≤ weight j)
    (X : ι → ℕ → Ω → ℝ) (risk : ι → ℝ)
    (strategy : ℕ → ℕ → Ω → ℝ) :
    0 ≤ countableForwardPredictableStrategyPACBayesMasterProcess
      prior weight X risk strategy := by
  unfold countableForwardPredictableStrategyPACBayesMasterProcess
  exact countableWeightedProcess_nonneg hweight_nonneg fun j n ω ↦
    countableForwardPredictableStrategyPACBayesComponent_nonneg
      hprior X risk strategy j n ω

omit [DecidableEq ι] [Nonempty ι] in
/-- The normalized countable strategy master inherits the common exponential
envelope. -/
theorem countableForwardPredictableStrategyPACBayesMasterProcess_le_exp
    {prior : ι → ℝ} (hprior : IsPMF prior)
    {weight : ℕ → ℝ} (hweight_nonneg : ∀ j, 0 ≤ weight j)
    (hweight_sum_one : HasSum weight 1)
    {X : ι → ℕ → Ω → ℝ} {risk : ι → ℝ}
    {strategy : ℕ → ℕ → Ω → ℝ} {L : ℝ}
    (hL1 : L < 1)
    (hrisk : ∀ i, 0 ≤ risk i ∧ risk i ≤ 1)
    (hX_unit : ∀ i k ω, 0 ≤ X i k ω ∧ X i k ω ≤ 1)
    (hstrategy_range : ∀ j k ω,
      0 ≤ strategy j k ω ∧ strategy j k ω ≤ L)
    (n : ℕ) (ω : Ω) :
    countableForwardPredictableStrategyPACBayesMasterProcess
        prior weight X risk strategy n ω ≤
      Real.exp ((n : ℝ) * L) := by
  let C := Real.exp ((n : ℝ) * L)
  have hseries :=
    countableForwardPredictableStrategyPACBayesMasterProcess_pointwise_summable
      (X := X) (risk := risk) (strategy := strategy)
      hprior hweight_nonneg hweight_sum_one.summable hL1 hrisk
      hX_unit hstrategy_range n ω
  have hbound_series : Summable fun j ↦ weight j * C :=
    hweight_sum_one.summable.mul_right C
  unfold countableForwardPredictableStrategyPACBayesMasterProcess
    countableWeightedProcess
  calc
    (∑' j, weight j *
        countableForwardPredictableStrategyPACBayesComponent
          prior X risk strategy j n ω) ≤
        ∑' j, weight j * C :=
      hseries.tsum_le_tsum
        (fun j ↦ mul_le_mul_of_nonneg_left
          (countableForwardPredictableStrategyPACBayesComponent_le_exp
            hprior hL1 hrisk hX_unit hstrategy_range j n ω)
          (hweight_nonneg j))
        hbound_series
    _ = C := by simpa using (hweight_sum_one.mul_right C).tsum_eq

omit [Nonempty ι] in
/-- The automatically summable outer strategy series is strongly adapted. -/
theorem countableForwardPredictableStrategyPACBayesMasterProcess_stronglyAdapted
    [IsProbabilityMeasure μ]
    {prior : ι → ℝ} (hprior : IsFullSupportPMF prior)
    {weight : ℕ → ℝ} (hweight_nonneg : ∀ j, 0 ≤ weight j)
    (hweight_sum_one : HasSum weight 1)
    {X : ι → ℕ → Ω → ℝ} {risk : ι → ℝ}
    {strategy : ℕ → ℕ → Ω → ℝ} {L : ℝ}
    (hL1 : L < 1)
    (hrisk : ∀ i, 0 ≤ risk i ∧ risk i ≤ 1)
    (hX_adapted : ∀ i, IncrementAdapted ℱ (X i))
    (hstrategy_adapted : ∀ j, StronglyAdapted ℱ (strategy j))
    (hX_unit : ∀ i k ω, 0 ≤ X i k ω ∧ X i k ω ≤ 1)
    (hstrategy_range : ∀ j k ω,
      0 ≤ strategy j k ω ∧ strategy j k ω ≤ L)
    (hmean : ∀ i k, μ[X i k | ℱ k] =ᵐ[μ] fun _ ↦ risk i) :
    StronglyAdapted ℱ
      (countableForwardPredictableStrategyPACBayesMasterProcess
        prior weight X risk strategy) := by
  intro n
  unfold countableForwardPredictableStrategyPACBayesMasterProcess
    countableWeightedProcess
  refine stronglyMeasurable_of_tendsto Filter.atTop
    (f := fun N ω ↦ ∑ j ∈ Finset.range N,
      weight j *
        countableForwardPredictableStrategyPACBayesComponent
          prior X risk strategy j n ω)
    (g := fun ω ↦ ∑' j,
      weight j *
        countableForwardPredictableStrategyPACBayesComponent
          prior X risk strategy j n ω) ?_ ?_
  · intro N
    have hsum := Finset.stronglyMeasurable_sum (Finset.range N)
      (fun j _ ↦
        (((countableForwardPredictableStrategyPACBayesComponent_eProcess_of_bounded
          hprior hL1 hX_adapted hstrategy_adapted hX_unit
            hstrategy_range hmean j).supermartingale).stronglyAdapted n).const_mul
              (weight j))
    convert hsum using 1
    ext ω
    simp only [Finset.sum_apply]
  · rw [tendsto_pi_nhds]
    intro ω
    exact
      (countableForwardPredictableStrategyPACBayesMasterProcess_pointwise_summable
        (X := X) (risk := risk) (strategy := strategy)
        hprior.toIsPMF hweight_nonneg hweight_sum_one.summable hL1
        hrisk hX_unit hstrategy_range n ω).hasSum.tendsto_sum_nat

omit [Nonempty ι] in
/-- The bounded countable strategy master is integrable at every time. -/
theorem countableForwardPredictableStrategyPACBayesMasterProcess_integrable
    [IsProbabilityMeasure μ]
    {prior : ι → ℝ} (hprior : IsFullSupportPMF prior)
    {weight : ℕ → ℝ} (hweight_nonneg : ∀ j, 0 ≤ weight j)
    (hweight_sum_one : HasSum weight 1)
    {X : ι → ℕ → Ω → ℝ} {risk : ι → ℝ}
    {strategy : ℕ → ℕ → Ω → ℝ} {L : ℝ}
    (hL1 : L < 1)
    (hrisk : ∀ i, 0 ≤ risk i ∧ risk i ≤ 1)
    (hX_adapted : ∀ i, IncrementAdapted ℱ (X i))
    (hstrategy_adapted : ∀ j, StronglyAdapted ℱ (strategy j))
    (hX_unit : ∀ i k ω, 0 ≤ X i k ω ∧ X i k ω ≤ 1)
    (hstrategy_range : ∀ j k ω,
      0 ≤ strategy j k ω ∧ strategy j k ω ≤ L)
    (hmean : ∀ i k, μ[X i k | ℱ k] =ᵐ[μ] fun _ ↦ risk i)
    (n : ℕ) :
    Integrable
      (countableForwardPredictableStrategyPACBayesMasterProcess
        prior weight X risk strategy n) μ := by
  let C := Real.exp ((n : ℝ) * L)
  have hadapted :=
    countableForwardPredictableStrategyPACBayesMasterProcess_stronglyAdapted
      hprior hweight_nonneg hweight_sum_one hL1 hrisk hX_adapted
      hstrategy_adapted hX_unit hstrategy_range hmean
  refine Integrable.of_bound
    ((hadapted n).mono (ℱ.le n)).aestronglyMeasurable C ?_
  exact Filter.Eventually.of_forall fun ω ↦ by
    rw [Real.norm_eq_abs, abs_of_nonneg
      (countableForwardPredictableStrategyPACBayesMasterProcess_nonneg
        hprior.toIsPMF hweight_nonneg X risk strategy n ω)]
    exact countableForwardPredictableStrategyPACBayesMasterProcess_le_exp
      hprior.toIsPMF hweight_nonneg hweight_sum_one hL1 hrisk
      hX_unit hstrategy_range n ω

omit [DecidableEq ι] [Nonempty ι] in
/-- The component set-integral norms are dominated by one summable weight
sequence. -/
theorem countableForwardPredictableStrategyPACBayesMasterProcess_integralNorm_summable
    [IsProbabilityMeasure μ]
    {prior : ι → ℝ} (hprior : IsFullSupportPMF prior)
    {weight : ℕ → ℝ} (hweight_nonneg : ∀ j, 0 ≤ weight j)
    (hweight_sum_one : HasSum weight 1)
    {X : ι → ℕ → Ω → ℝ} {risk : ι → ℝ}
    {strategy : ℕ → ℕ → Ω → ℝ} {L : ℝ}
    (hL1 : L < 1)
    (hrisk : ∀ i, 0 ≤ risk i ∧ risk i ≤ 1)
    (hX_unit : ∀ i k ω, 0 ≤ X i k ω ∧ X i k ω ≤ 1)
    (hstrategy_range : ∀ j k ω,
      0 ≤ strategy j k ω ∧ strategy j k ω ≤ L)
    (n : ℕ) (s : Set Ω) (_hs : MeasurableSet s) :
    Summable fun j ↦ ∫ ω in s,
      ‖weight j *
        countableForwardPredictableStrategyPACBayesComponent
          prior X risk strategy j n ω‖ ∂μ := by
  let C := Real.exp ((n : ℝ) * L)
  have hC : 0 ≤ C := (Real.exp_pos _).le
  have hdom : Summable fun j ↦ weight j * C :=
    hweight_sum_one.summable.mul_right C
  refine hdom.of_nonneg_of_le (fun j ↦ integral_nonneg fun _ ↦ norm_nonneg _) ?_
  intro j
  have hconst_nonneg : 0 ≤ weight j * C :=
    mul_nonneg (hweight_nonneg j) hC
  have hnorm_bound : ∀ ω ∈ s,
      ‖weight j *
        countableForwardPredictableStrategyPACBayesComponent
          prior X risk strategy j n ω‖ ≤ weight j * C := by
    intro ω _hω
    rw [Real.norm_eq_abs, abs_of_nonneg
      (mul_nonneg (hweight_nonneg j)
        (countableForwardPredictableStrategyPACBayesComponent_nonneg
          hprior.toIsPMF X risk strategy j n ω))]
    exact mul_le_mul_of_nonneg_left
      (countableForwardPredictableStrategyPACBayesComponent_le_exp
        hprior.toIsPMF hL1 hrisk hX_unit hstrategy_range j n ω)
      (hweight_nonneg j)
  have hset := norm_setIntegral_le_of_norm_le_const
    (μ := μ) (s := s)
    (f := fun ω ↦ ‖weight j *
      countableForwardPredictableStrategyPACBayesComponent
        prior X risk strategy j n ω‖)
    (measure_lt_top μ s) (fun ω hω ↦ by
      rw [Real.norm_eq_abs, abs_of_nonneg (norm_nonneg _)]
      exact hnorm_bound ω hω)
  have hint_nonneg : 0 ≤ ∫ ω in s,
      ‖weight j *
        countableForwardPredictableStrategyPACBayesComponent
          prior X risk strategy j n ω‖ ∂μ :=
    integral_nonneg fun _ ↦ norm_nonneg _
  rw [Real.norm_eq_abs, abs_of_nonneg hint_nonneg] at hset
  calc
    (∫ ω in s,
        ‖weight j *
          countableForwardPredictableStrategyPACBayesComponent
            prior X risk strategy j n ω‖ ∂μ) ≤
        (weight j * C) * μ.real s := hset
    _ ≤ (weight j * C) * 1 :=
      mul_le_mul_of_nonneg_left measureReal_le_one hconst_nonneg
    _ = weight j * C := mul_one _

omit [Nonempty ι] in
/-- The countable model-prior--strategy master is an e-process.  Its catalog
and normalized outer weights are fixed before observing the path. -/
theorem countableForwardPredictableStrategyPACBayesMasterProcess_eProcess_of_bounded
    [IsProbabilityMeasure μ]
    {prior : ι → ℝ} (hprior : IsFullSupportPMF prior)
    {weight : ℕ → ℝ} (hweight_nonneg : ∀ j, 0 ≤ weight j)
    (hweight_sum_one : HasSum weight 1)
    {X : ι → ℕ → Ω → ℝ} {risk : ι → ℝ}
    {strategy : ℕ → ℕ → Ω → ℝ} {L : ℝ}
    (hL1 : L < 1)
    (hrisk : ∀ i, 0 ≤ risk i ∧ risk i ≤ 1)
    (hX_adapted : ∀ i, IncrementAdapted ℱ (X i))
    (hstrategy_adapted : ∀ j, StronglyAdapted ℱ (strategy j))
    (hX_unit : ∀ i k ω, 0 ≤ X i k ω ∧ X i k ω ≤ 1)
    (hstrategy_range : ∀ j k ω,
      0 ≤ strategy j k ω ∧ strategy j k ω ≤ L)
    (hmean : ∀ i k, μ[X i k | ℱ k] =ᵐ[μ] fun _ ↦ risk i) :
    EProcess μ ℱ
      (countableForwardPredictableStrategyPACBayesMasterProcess
        prior weight X risk strategy) := by
  unfold countableForwardPredictableStrategyPACBayesMasterProcess
  apply countableWeightedProcess_eProcess
    hweight_nonneg hweight_sum_one
  · intro j
    exact
      countableForwardPredictableStrategyPACBayesComponent_eProcess_of_bounded
        hprior hL1 hX_adapted hstrategy_adapted hX_unit
        hstrategy_range hmean j
  · exact
      countableForwardPredictableStrategyPACBayesMasterProcess_stronglyAdapted
        hprior hweight_nonneg hweight_sum_one hL1 hrisk hX_adapted
        hstrategy_adapted hX_unit hstrategy_range hmean
  · exact
      countableForwardPredictableStrategyPACBayesMasterProcess_integrable
        hprior hweight_nonneg hweight_sum_one hL1 hrisk hX_adapted
        hstrategy_adapted hX_unit hstrategy_range hmean
  · exact
      countableForwardPredictableStrategyPACBayesMasterProcess_integralNorm_summable
        hprior hweight_nonneg hweight_sum_one hL1 hrisk
        hX_unit hstrategy_range

/-! ## Selected countable strategy atoms -/

omit [DecidableEq ι] [Nonempty ι] in
/-- When one predictable strategy is shared across all models and every model
has a constant conditional risk, its positive accumulated weight cancels from
the normalized posterior mean. -/
theorem forwardPredictableTiltPosteriorNormalizedMean_shared_constant
    (posterior : ι → ℝ) (hposterior : IsPMF posterior)
    (risk : ι → ℝ) (strategy : ℕ → ℕ → Ω → ℝ)
    (j n : ℕ) (ω : Ω)
    (hexposure : 0 <
      forwardPredictableTiltPosteriorTotalWeight posterior
        (fun _i ↦ strategy j) n ω) :
    forwardPredictableTiltPosteriorNormalizedMean posterior
        (fun i _k _ω ↦ risk i) (fun _i ↦ strategy j) n ω =
      posteriorAverage posterior risk := by
  let exposure := ∑ k ∈ Finset.range n, strategy j k ω
  have hden :
      forwardPredictableTiltPosteriorTotalWeight posterior
          (fun _i ↦ strategy j) n ω = exposure := by
    unfold forwardPredictableTiltPosteriorTotalWeight posteriorAverage
    change (∑ i : ι, posterior i * exposure) = exposure
    rw [← Finset.sum_mul, hposterior.sum_one, one_mul]
  have hexposure_pos : 0 < exposure := by rwa [hden] at hexposure
  have hnum :
      posteriorAverage posterior
          (fun i ↦ ∑ k ∈ Finset.range n,
            strategy j k ω * risk i) =
        posteriorAverage posterior risk * exposure := by
    unfold posteriorAverage
    calc
      (∑ i : ι, posterior i *
          ∑ k ∈ Finset.range n, strategy j k ω * risk i) =
          ∑ i : ι, (posterior i * risk i) * exposure := by
        apply Finset.sum_congr rfl
        intro i _hi
        rw [show (∑ k ∈ Finset.range n, strategy j k ω * risk i) =
            exposure * risk i by
          rw [Finset.sum_mul]]
        ring
      _ = (∑ i : ι, posterior i * risk i) * exposure := by
        rw [Finset.sum_mul]
  unfold forwardPredictableTiltPosteriorNormalizedMean
  rw [hden, hnum]
  exact mul_div_cancel_right₀
    (posteriorAverage posterior risk) hexposure_pos.ne'

/-- Width paid by one selected countable predictable-strategy atom.  The
strategy atom is selected from the predeclared catalog; the outer weights are
not changed after observing the path. -/
def countableForwardPredictableStrategyPACBayesSelectedAtomWidth
    (prior : ι → ℝ) (weight : ℕ → ℝ)
    (X : ι → ℕ → Ω → ℝ) (strategy : ℕ → ℕ → Ω → ℝ)
    (posterior : ι → ℝ) (delta : ℝ) (j n : ℕ) (ω : Ω) : ℝ :=
  (klDiv posterior prior + Real.log (1 / (delta * weight j)) +
      forwardPredictableTiltPosteriorQuadraticPenalty posterior X
        (fun _i ↦ strategy j) n ω) /
    forwardPredictableTiltPosteriorTotalWeight posterior
      (fun _i ↦ strategy j) n ω

/-- Ordinary conditional-risk boundary for one selected countable strategy
atom and one model posterior. -/
def countableForwardPredictableStrategyPACBayesSelectedAtomBoundary
    (prior : ι → ℝ) (weight : ℕ → ℝ)
    (X : ι → ℕ → Ω → ℝ) (strategy : ℕ → ℕ → Ω → ℝ)
    (posterior : ι → ℝ) (delta : ℝ) (j n : ℕ) (ω : Ω) : ℝ :=
  forwardPredictableTiltPosteriorNormalizedObservation posterior X
      (fun _i ↦ strategy j) n ω +
    countableForwardPredictableStrategyPACBayesSelectedAtomWidth
      prior weight X strategy posterior delta j n ω

/-- One crossing event for all times, model posteriors, and atoms in the
predeclared countable predictable-strategy catalog. -/
def countableForwardPredictableStrategyPACBayesExceptionalEvent
    (prior : ι → ℝ) (weight : ℕ → ℝ)
    (X : ι → ℕ → Ω → ℝ) (risk : ι → ℝ)
    (strategy : ℕ → ℕ → Ω → ℝ) (delta : ℝ) : Set Ω :=
  atTopCrossingEvent
    (countableForwardPredictableStrategyPACBayesMasterProcess
      prior weight X risk strategy)
    (1 / delta)

omit [Nonempty ι] in
/-- Ville control of the single countable predictable-strategy master
process. -/
theorem countableForwardPredictableStrategyPACBayesExceptionalEvent_mass_le_delta
    [IsProbabilityMeasure μ]
    {prior : ι → ℝ} (hprior : IsFullSupportPMF prior)
    {weight : ℕ → ℝ} (hweight_nonneg : ∀ j, 0 ≤ weight j)
    (hweight_sum_one : HasSum weight 1)
    {X : ι → ℕ → Ω → ℝ} {risk : ι → ℝ}
    {strategy : ℕ → ℕ → Ω → ℝ} {L delta : ℝ}
    (hL1 : L < 1) (hdelta : 0 < delta)
    (hrisk : ∀ i, 0 ≤ risk i ∧ risk i ≤ 1)
    (hX_adapted : ∀ i, IncrementAdapted ℱ (X i))
    (hstrategy_adapted : ∀ j, StronglyAdapted ℱ (strategy j))
    (hX_unit : ∀ i k ω, 0 ≤ X i k ω ∧ X i k ω ≤ 1)
    (hstrategy_range : ∀ j k ω,
      0 ≤ strategy j k ω ∧ strategy j k ω ≤ L)
    (hmean : ∀ i k, μ[X i k | ℱ k] =ᵐ[μ] fun _ ↦ risk i) :
    μ.real
        (countableForwardPredictableStrategyPACBayesExceptionalEvent
          prior weight X risk strategy delta) ≤
      delta := by
  have hE :=
    countableForwardPredictableStrategyPACBayesMasterProcess_eProcess_of_bounded
      hprior hweight_nonneg hweight_sum_one hL1 hrisk hX_adapted
      hstrategy_adapted hX_unit hstrategy_range hmean
  have hville := ville_atTop_maximal_ineq
    (μ := μ) (𝒢 := ℱ)
    (M := countableForwardPredictableStrategyPACBayesMasterProcess
      prior weight X risk strategy)
    hE.supermartingale hE.nonneg (one_div_pos.mpr hdelta)
  rw [hE.integral_start_eq_one] at hville
  unfold countableForwardPredictableStrategyPACBayesExceptionalEvent
  calc
    μ.real
        (atTopCrossingEvent
          (countableForwardPredictableStrategyPACBayesMasterProcess
            prior weight X risk strategy)
          (1 / delta)) =
        delta * ((1 / delta) *
          μ.real
            (atTopCrossingEvent
              (countableForwardPredictableStrategyPACBayesMasterProcess
                prior weight X risk strategy)
              (1 / delta))) := by
      field_simp [hdelta.ne']
    _ ≤ delta * 1 := mul_le_mul_of_nonneg_left hville hdelta.le
    _ = delta := by ring

omit [DecidableEq ι] in
/-- Failure of one positive-exposure ordinary-risk boundary forces the single
countable master process into its crossing event. -/
theorem
    countableForwardPredictableStrategyPACBayes_boundaryFailure_mem_exceptionalEvent
    {prior : ι → ℝ} (hprior : IsFullSupportPMF prior)
    {weight : ℕ → ℝ} (hweight_pos : ∀ j, 0 < weight j)
    (hweight_sum_one : HasSum weight 1)
    {X : ι → ℕ → Ω → ℝ} {risk : ι → ℝ}
    {strategy : ℕ → ℕ → Ω → ℝ} {L delta : ℝ}
    (hL1 : L < 1) (hdelta : 0 < delta)
    (hrisk : ∀ i, 0 ≤ risk i ∧ risk i ≤ 1)
    (hX_unit : ∀ i k ω, 0 ≤ X i k ω ∧ X i k ω ≤ 1)
    (hstrategy_range : ∀ j k ω,
      0 ≤ strategy j k ω ∧ strategy j k ω ≤ L)
    {posterior : ι → ℝ} (hposterior : IsPMF posterior)
    {j n : ℕ} {ω : Ω}
    (hexposure : 0 <
      forwardPredictableTiltPosteriorTotalWeight posterior
        (fun _i ↦ strategy j) n ω)
    (hfail :
      countableForwardPredictableStrategyPACBayesSelectedAtomBoundary
          prior weight X strategy posterior delta j n ω ≤
        posteriorAverage posterior risk) :
    ω ∈ countableForwardPredictableStrategyPACBayesExceptionalEvent
      prior weight X risk strategy delta := by
  classical
  have hnormalized :=
    forwardPredictableTiltPosteriorNormalizedMean_shared_constant
      posterior hposterior risk strategy j n ω hexposure
  have hgap_identity :=
    forwardPredictableTiltPosteriorNormalizedMean_sub_observation
      posterior X (fun i _k _ω ↦ risk i)
      (fun _i ↦ strategy j) n ω
  unfold countableForwardPredictableStrategyPACBayesSelectedAtomBoundary
    countableForwardPredictableStrategyPACBayesSelectedAtomWidth at hfail
  rw [← hnormalized] at hfail
  have hbudget_div_le_gap_div :
      (klDiv posterior prior + Real.log (1 / (delta * weight j)) +
          forwardPredictableTiltPosteriorQuadraticPenalty posterior X
            (fun _i ↦ strategy j) n ω) /
          forwardPredictableTiltPosteriorTotalWeight posterior
            (fun _i ↦ strategy j) n ω ≤
        forwardPredictableTiltPosteriorMeanGap posterior X
            (fun i _k _ω ↦ risk i) (fun _i ↦ strategy j) n ω /
          forwardPredictableTiltPosteriorTotalWeight posterior
            (fun _i ↦ strategy j) n ω := by
    linarith
  have hbudget_le_gap :=
    (div_le_div_iff_of_pos_right hexposure).mp hbudget_div_le_gap_div
  have hscore_identity :=
    posteriorAverage_forwardPredictableTiltPACBayesScore posterior X
      (fun i _k _ω ↦ risk i) (fun _i ↦ strategy j) n ω
  have hbudget_le_score :
      klDiv posterior prior + Real.log (1 / (delta * weight j)) ≤
        posteriorAverage posterior
          (fun i ↦ forwardPredictableTiltPACBayesScore X
            (fun i _k _ω ↦ risk i) (fun _i ↦ strategy j) i n ω) := by
    rw [hscore_identity]
    linarith
  have hdv := posterior_change_of_measure hposterior hprior
    (fun i ↦ forwardPredictableTiltPACBayesScore X
      (fun i _k _ω ↦ risk i) (fun _i ↦ strategy j) i n ω)
  have hlog_le :
      Real.log (1 / (delta * weight j)) ≤
        Real.log
          (∑ i : ι, prior i *
            Real.exp
              (forwardPredictableTiltPACBayesScore X
                (fun i _k _ω ↦ risk i) (fun _i ↦ strategy j)
                i n ω)) := by
    linarith
  have hthreshold_pos : 0 < 1 / (delta * weight j) :=
    one_div_pos.mpr (mul_pos hdelta (hweight_pos j))
  have hmoment_pos :
      0 < ∑ i : ι, prior i *
        Real.exp
          (forwardPredictableTiltPACBayesScore X
            (fun i _k _ω ↦ risk i) (fun _i ↦ strategy j)
            i n ω) :=
    Finset.sum_pos
      (fun i _ ↦ mul_pos (hprior.pos i) (Real.exp_pos _))
      Finset.univ_nonempty
  have hthreshold_le_moment :
      1 / (delta * weight j) ≤
        ∑ i : ι, prior i *
          Real.exp
            (forwardPredictableTiltPACBayesScore X
              (fun i _k _ω ↦ risk i) (fun _i ↦ strategy j)
              i n ω) :=
    (Real.log_le_log_iff hthreshold_pos hmoment_pos).mp hlog_le
  have hmoment_eq_component :
      (∑ i : ι, prior i *
        Real.exp
          (forwardPredictableTiltPACBayesScore X
            (fun i _k _ω ↦ risk i) (fun _i ↦ strategy j)
            i n ω)) =
        countableForwardPredictableStrategyPACBayesComponent
          prior X risk strategy j n ω := by
    unfold countableForwardPredictableStrategyPACBayesComponent
      finiteWeightedProcess
    apply Finset.sum_congr rfl
    intro i _hi
    apply congrArg (fun z : ℝ ↦ prior i * z)
    symm
    simpa [forwardPredictableTiltPACBayesScore] using
      (forwardPredictableTiltMeanEmpiricalBernsteinLowerProcess_eq
        (X i) (fun _ _ ↦ risk i) (strategy j) n ω)
  have hinner :
      1 / (delta * weight j) ≤
        countableForwardPredictableStrategyPACBayesComponent
          prior X risk strategy j n ω := by
    rwa [← hmoment_eq_component]
  have hweighted :
      weight j * (1 / (delta * weight j)) ≤
        weight j *
          countableForwardPredictableStrategyPACBayesComponent
            prior X risk strategy j n ω :=
    mul_le_mul_of_nonneg_left hinner (hweight_pos j).le
  have hseries :=
    countableForwardPredictableStrategyPACBayesMasterProcess_pointwise_summable
      (X := X) (risk := risk) (strategy := strategy)
      hprior.toIsPMF (fun k ↦ (hweight_pos k).le)
      hweight_sum_one.summable hL1 hrisk hX_unit hstrategy_range n ω
  have hsingle :
      weight j *
          countableForwardPredictableStrategyPACBayesComponent
            prior X risk strategy j n ω ≤
        countableForwardPredictableStrategyPACBayesMasterProcess
          prior weight X risk strategy n ω := by
    unfold countableForwardPredictableStrategyPACBayesMasterProcess
      countableWeightedProcess
    exact hseries.le_tsum j fun k _ ↦
      mul_nonneg (hweight_pos k).le
        (countableForwardPredictableStrategyPACBayesComponent_nonneg
          hprior.toIsPMF X risk strategy k n ω)
  rw [show weight j * (1 / (delta * weight j)) = 1 / delta by
    field_simp [hdelta.ne', (hweight_pos j).ne']] at hweighted
  unfold countableForwardPredictableStrategyPACBayesExceptionalEvent
  exact ⟨n, hweighted.trans hsingle⟩

omit [DecidableEq ι] in
/-- Outside the master crossing event, the ordinary-risk boundary holds
simultaneously for every declared strategy atom, every model posterior, and
every time with positive accumulated exposure. -/
theorem countableForwardPredictableStrategyPACBayes_allPosteriors_of_not_mem
    {prior : ι → ℝ} (hprior : IsFullSupportPMF prior)
    {weight : ℕ → ℝ} (hweight_pos : ∀ j, 0 < weight j)
    (hweight_sum_one : HasSum weight 1)
    {X : ι → ℕ → Ω → ℝ} {risk : ι → ℝ}
    {strategy : ℕ → ℕ → Ω → ℝ} {L delta : ℝ}
    (hL1 : L < 1) (hdelta : 0 < delta)
    (hrisk : ∀ i, 0 ≤ risk i ∧ risk i ≤ 1)
    (hX_unit : ∀ i k ω, 0 ≤ X i k ω ∧ X i k ω ≤ 1)
    (hstrategy_range : ∀ j k ω,
      0 ≤ strategy j k ω ∧ strategy j k ω ≤ L)
    {ω : Ω}
    (hω : ω ∉ countableForwardPredictableStrategyPACBayesExceptionalEvent
      prior weight X risk strategy delta) :
    ∀ j : ℕ, ∀ posterior : ι → ℝ, IsPMF posterior → ∀ n : ℕ,
      0 < forwardPredictableTiltPosteriorTotalWeight posterior
          (fun _i ↦ strategy j) n ω →
        posteriorAverage posterior risk <
          countableForwardPredictableStrategyPACBayesSelectedAtomBoundary
            prior weight X strategy posterior delta j n ω := by
  intro j posterior hposterior n hexposure
  apply lt_of_not_ge
  intro hfail
  apply hω
  exact
    countableForwardPredictableStrategyPACBayes_boundaryFailure_mem_exceptionalEvent
      hprior hweight_pos hweight_sum_one hL1 hdelta hrisk hX_unit
      hstrategy_range hposterior hexposure hfail

omit [DecidableEq ι] in
/-- One outer-probability event carries the ordinary conditional-risk bound
for every declared countable strategy atom, every model posterior, and every
time with positive exposure.  The strategy catalog and its weights are fixed
before observing the path. -/
theorem exists_countableForwardPredictableStrategyPACBayes_event
    [IsProbabilityMeasure μ]
    {prior : ι → ℝ} (hprior : IsFullSupportPMF prior)
    {weight : ℕ → ℝ} (hweight_pos : ∀ j, 0 < weight j)
    (hweight_sum_one : HasSum weight 1)
    {X : ι → ℕ → Ω → ℝ} {risk : ι → ℝ}
    {strategy : ℕ → ℕ → Ω → ℝ} {L delta : ℝ}
    (hL1 : L < 1) (hdelta : 0 < delta)
    (hrisk : ∀ i, 0 ≤ risk i ∧ risk i ≤ 1)
    (hX_adapted : ∀ i, IncrementAdapted ℱ (X i))
    (hstrategy_adapted : ∀ j, StronglyAdapted ℱ (strategy j))
    (hX_unit : ∀ i k ω, 0 ≤ X i k ω ∧ X i k ω ≤ 1)
    (hstrategy_range : ∀ j k ω,
      0 ≤ strategy j k ω ∧ strategy j k ω ≤ L)
    (hmean : ∀ i k, μ[X i k | ℱ k] =ᵐ[μ] fun _ ↦ risk i) :
    ∃ goodEvent : Set Ω,
      μ.real goodEventᶜ ≤ delta ∧
        ∀ ω ∈ goodEvent, ∀ j : ℕ,
          ∀ posterior : ι → ℝ, IsPMF posterior → ∀ n : ℕ,
            0 < forwardPredictableTiltPosteriorTotalWeight posterior
                (fun _i ↦ strategy j) n ω →
              posteriorAverage posterior risk <
                countableForwardPredictableStrategyPACBayesSelectedAtomBoundary
                  prior weight X strategy posterior delta j n ω := by
  let badEvent :=
    countableForwardPredictableStrategyPACBayesExceptionalEvent
      prior weight X risk strategy delta
  refine ⟨badEventᶜ, ?_, ?_⟩
  · simpa [badEvent] using
      (countableForwardPredictableStrategyPACBayesExceptionalEvent_mass_le_delta
        hprior (fun j ↦ (hweight_pos j).le) hweight_sum_one hL1 hdelta
        hrisk hX_adapted hstrategy_adapted hX_unit hstrategy_range hmean)
  · intro ω hω
    apply countableForwardPredictableStrategyPACBayes_allPosteriors_of_not_mem
      hprior hweight_pos hweight_sum_one hL1 hdelta hrisk hX_unit
        hstrategy_range
    simpa [badEvent] using hω

/-! ## Exact finite-prefix selection -/

omit [DecidableEq ι] [Nonempty ι] in
private theorem
    countableForwardPredictableStrategyPACBayesFinitePrefix_exists_argmin
    (prior : ι → ℝ) (weight : ℕ → ℝ)
    (X : ι → ℕ → Ω → ℝ) (strategy : ℕ → ℕ → Ω → ℝ)
    (posterior : ι → ℝ) (delta : ℝ)
    (maxIndex n : ℕ) (ω : Ω) :
    ∃ j ∈ Finset.range (maxIndex + 1),
      ∀ j' ∈ Finset.range (maxIndex + 1),
        countableForwardPredictableStrategyPACBayesSelectedAtomBoundary
            prior weight X strategy posterior delta j n ω ≤
          countableForwardPredictableStrategyPACBayesSelectedAtomBoundary
            prior weight X strategy posterior delta j' n ω := by
  exact (Finset.range (maxIndex + 1)).exists_min_image
    (fun j ↦
      countableForwardPredictableStrategyPACBayesSelectedAtomBoundary
        prior weight X strategy posterior delta j n ω)
    (by simp)

/-- A concrete exact argmin over strategy atoms `0, ..., maxIndex`.  It may
depend on the observed path, time, model posterior, and declared prefix. -/
def countableForwardPredictableStrategyPACBayesFinitePrefixArgmin
    (prior : ι → ℝ) (weight : ℕ → ℝ)
    (X : ι → ℕ → Ω → ℝ) (strategy : ℕ → ℕ → Ω → ℝ)
    (posterior : ι → ℝ) (delta : ℝ)
    (maxIndex n : ℕ) (ω : Ω) : ℕ :=
  Classical.choose
    (countableForwardPredictableStrategyPACBayesFinitePrefix_exists_argmin
      prior weight X strategy posterior delta maxIndex n ω)

omit [DecidableEq ι] [Nonempty ι] in
/-- The finite-prefix selector belongs to its declared candidate range. -/
theorem countableForwardPredictableStrategyPACBayesFinitePrefixArgmin_mem
    (prior : ι → ℝ) (weight : ℕ → ℝ)
    (X : ι → ℕ → Ω → ℝ) (strategy : ℕ → ℕ → Ω → ℝ)
    (posterior : ι → ℝ) (delta : ℝ)
    (maxIndex n : ℕ) (ω : Ω) :
    countableForwardPredictableStrategyPACBayesFinitePrefixArgmin
        prior weight X strategy posterior delta maxIndex n ω ∈
      Finset.range (maxIndex + 1) := by
  exact
    (Classical.choose_spec
      (countableForwardPredictableStrategyPACBayesFinitePrefix_exists_argmin
        prior weight X strategy posterior delta maxIndex n ω)).1

omit [DecidableEq ι] [Nonempty ι] in
/-- The selected finite-prefix boundary is no larger than every candidate
boundary in the declared prefix. -/
theorem countableForwardPredictableStrategyPACBayesFinitePrefixArgmin_le
    (prior : ι → ℝ) (weight : ℕ → ℝ)
    (X : ι → ℕ → Ω → ℝ) (strategy : ℕ → ℕ → Ω → ℝ)
    (posterior : ι → ℝ) (delta : ℝ)
    (maxIndex n : ℕ) (ω : Ω)
    {j : ℕ} (hj : j ∈ Finset.range (maxIndex + 1)) :
    countableForwardPredictableStrategyPACBayesSelectedAtomBoundary
        prior weight X strategy posterior delta
          (countableForwardPredictableStrategyPACBayesFinitePrefixArgmin
            prior weight X strategy posterior delta maxIndex n ω)
          n ω ≤
      countableForwardPredictableStrategyPACBayesSelectedAtomBoundary
        prior weight X strategy posterior delta j n ω := by
  exact
    (Classical.choose_spec
      (countableForwardPredictableStrategyPACBayesFinitePrefix_exists_argmin
        prior weight X strategy posterior delta maxIndex n ω)).2 j hj

omit [DecidableEq ι] in
/-- One countable-uniform event supports exact post-data minimization over any
declared finite prefix.  The selector competes only with that prefix, while
the underlying event remains simultaneous over the whole countable catalog. -/
theorem
    exists_countableForwardPredictableStrategyPACBayesFinitePrefixOracle_event
    [IsProbabilityMeasure μ]
    {prior : ι → ℝ} (hprior : IsFullSupportPMF prior)
    {weight : ℕ → ℝ} (hweight_pos : ∀ j, 0 < weight j)
    (hweight_sum_one : HasSum weight 1)
    {X : ι → ℕ → Ω → ℝ} {risk : ι → ℝ}
    {strategy : ℕ → ℕ → Ω → ℝ} {L delta : ℝ}
    (hL1 : L < 1) (hdelta : 0 < delta)
    (hrisk : ∀ i, 0 ≤ risk i ∧ risk i ≤ 1)
    (hX_adapted : ∀ i, IncrementAdapted ℱ (X i))
    (hstrategy_adapted : ∀ j, StronglyAdapted ℱ (strategy j))
    (hX_unit : ∀ i k ω, 0 ≤ X i k ω ∧ X i k ω ≤ 1)
    (hstrategy_range : ∀ j k ω,
      0 ≤ strategy j k ω ∧ strategy j k ω ≤ L)
    (hmean : ∀ i k, μ[X i k | ℱ k] =ᵐ[μ] fun _ ↦ risk i) :
    ∃ goodEvent : Set Ω,
      μ.real goodEventᶜ ≤ delta ∧
        ∀ ω ∈ goodEvent, ∀ posterior : ι → ℝ, IsPMF posterior →
          ∀ n maxIndex : ℕ,
            (∀ j ∈ Finset.range (maxIndex + 1),
              0 < forwardPredictableTiltPosteriorTotalWeight posterior
                (fun _i ↦ strategy j) n ω) →
              let selected :=
                countableForwardPredictableStrategyPACBayesFinitePrefixArgmin
                  prior weight X strategy posterior delta maxIndex n ω
              selected ∈ Finset.range (maxIndex + 1) ∧
                posteriorAverage posterior risk <
                  countableForwardPredictableStrategyPACBayesSelectedAtomBoundary
                    prior weight X strategy posterior delta selected n ω ∧
                ∀ j ∈ Finset.range (maxIndex + 1),
                  countableForwardPredictableStrategyPACBayesSelectedAtomBoundary
                      prior weight X strategy posterior delta selected n ω ≤
                    countableForwardPredictableStrategyPACBayesSelectedAtomBoundary
                      prior weight X strategy posterior delta j n ω := by
  obtain ⟨goodEvent, hmass, hgood⟩ :=
    exists_countableForwardPredictableStrategyPACBayes_event
      hprior hweight_pos hweight_sum_one hL1 hdelta hrisk hX_adapted
      hstrategy_adapted hX_unit hstrategy_range hmean
  refine ⟨goodEvent, hmass, ?_⟩
  intro ω hω posterior hposterior n maxIndex hexposure
  let selected :=
    countableForwardPredictableStrategyPACBayesFinitePrefixArgmin
      prior weight X strategy posterior delta maxIndex n ω
  have hselected_mem : selected ∈ Finset.range (maxIndex + 1) := by
    exact countableForwardPredictableStrategyPACBayesFinitePrefixArgmin_mem
      prior weight X strategy posterior delta maxIndex n ω
  have hrisk_bound := hgood ω hω selected posterior hposterior n
    (hexposure selected hselected_mem)
  refine ⟨hselected_mem, hrisk_bound, ?_⟩
  intro j hj
  exact countableForwardPredictableStrategyPACBayesFinitePrefixArgmin_le
    prior weight X strategy posterior delta maxIndex n ω hj

end

end FormalSLT.PACBayes.ForwardPredictableStrategyPACBayesCountable
