/-
Copyright (c) 2026 Robby Sneiderman. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Robby Sneiderman
-/
import FormalSLT.AnytimeValid.CountableEProcess
import FormalSLT.PACBayes.ForwardPredictableStrategyPACBayes

/-!
# Countable predictable-strategy PAC-Bayes master process

This module forms one countable master e-process from a predeclared
`Nat`-indexed catalog of predictable tilt strategies.  Each catalog atom is a
finite model-prior mixture, and the outer weights are fixed, nonnegative, and
normalized before the path is observed.

The strategies may depend on the observed past, but every strategy must be
predictable.  This module does not permit post-data changes to the outer
mixing weights.  Downstream results may select a declared strategy atom on the
single event generated by this master process.
-/

open MeasureTheory ProbabilityTheory
open FormalSLT.AnytimeValid
open FormalSLT.PACBayesKL
open scoped BigOperators

namespace FormalSLT.PACBayes.ForwardPredictableStrategyPACBayesCountable

noncomputable section

local instance (p : Prop) : Decidable p := Classical.propDecidable p

variable {ι Ω : Type*}
  [Fintype ι] [DecidableEq ι] [Nonempty ι]
  {mΩ : MeasurableSpace Ω} {μ : Measure Ω} {ℱ : Filtration ℕ mΩ}

/-- The finite model-prior component for one declared predictable strategy. -/
def countableForwardPredictableStrategyPACBayesComponent
    (prior : ι → ℝ) (X : ι → ℕ → Ω → ℝ) (risk : ι → ℝ)
    (strategy : ℕ → ℕ → Ω → ℝ) (j : ℕ) : ℕ → Ω → ℝ :=
  finiteWeightedProcess prior fun i ↦
    forwardPredictableTiltMeanEmpiricalBernsteinLowerProcess
      (X i) (fun _ _ ↦ risk i) (strategy j)

/-- The outer countable mixture over the predeclared predictable strategies. -/
def countableForwardPredictableStrategyPACBayesMasterProcess
    (prior : ι → ℝ) (weight : ℕ → ℝ)
    (X : ι → ℕ → Ω → ℝ) (risk : ι → ℝ)
    (strategy : ℕ → ℕ → Ω → ℝ) : ℕ → Ω → ℝ :=
  countableWeightedProcess weight
    (countableForwardPredictableStrategyPACBayesComponent
      prior X risk strategy)

omit [Nonempty ι] in
/-- Every declared predictable-strategy component is an e-process. -/
theorem countableForwardPredictableStrategyPACBayesComponent_eProcess_of_bounded
    [IsProbabilityMeasure μ]
    {prior : ι → ℝ} (hprior : IsFullSupportPMF prior)
    {X : ι → ℕ → Ω → ℝ} {risk : ι → ℝ}
    {strategy : ℕ → ℕ → Ω → ℝ} {L : ℝ}
    (hL1 : L < 1)
    (hX_adapted : ∀ i, IncrementAdapted ℱ (X i))
    (hstrategy_adapted : ∀ j, StronglyAdapted ℱ (strategy j))
    (hX_unit : ∀ i k ω, 0 ≤ X i k ω ∧ X i k ω ≤ 1)
    (hstrategy_range : ∀ j k ω,
      0 ≤ strategy j k ω ∧ strategy j k ω ≤ L)
    (hmean : ∀ i k, μ[X i k | ℱ k] =ᵐ[μ] fun _ ↦ risk i)
    (j : ℕ) :
    EProcess μ ℱ
      (countableForwardPredictableStrategyPACBayesComponent
        prior X risk strategy j) := by
  unfold countableForwardPredictableStrategyPACBayesComponent
  apply finiteWeightedProcess_eProcess hprior.nonneg hprior.sum_one
  intro i
  exact
    forwardPredictableTiltMeanEmpiricalBernsteinLowerProcess_eProcess_of_bounded
      (X := X i) (mean := fun _ _ ↦ risk i)
      (lambda := strategy j) hL1 (hX_adapted i)
      (fun _ ↦ stronglyMeasurable_const) (hstrategy_adapted j)
      (hX_unit i) (hstrategy_range j) (hmean i)

omit [DecidableEq ι] [Nonempty ι] in
/-- Every finite model-prior component is nonnegative pointwise. -/
theorem countableForwardPredictableStrategyPACBayesComponent_nonneg
    {prior : ι → ℝ} (hprior : IsPMF prior)
    (X : ι → ℕ → Ω → ℝ) (risk : ι → ℝ)
    (strategy : ℕ → ℕ → Ω → ℝ) (j n : ℕ) (ω : Ω) :
    0 ≤ countableForwardPredictableStrategyPACBayesComponent
      prior X risk strategy j n ω := by
  unfold countableForwardPredictableStrategyPACBayesComponent
    finiteWeightedProcess
  exact Finset.sum_nonneg fun i _ ↦
    mul_nonneg (hprior.nonneg i) (Real.exp_pos _).le

omit [DecidableEq ι] [Nonempty ι] in
/-- All declared strategy components share the same pointwise exponential
envelope at a fixed time. -/
theorem countableForwardPredictableStrategyPACBayesComponent_le_exp
    {prior : ι → ℝ} (hprior : IsPMF prior)
    {X : ι → ℕ → Ω → ℝ} {risk : ι → ℝ}
    {strategy : ℕ → ℕ → Ω → ℝ} {L : ℝ}
    (hL1 : L < 1)
    (hrisk : ∀ i, 0 ≤ risk i ∧ risk i ≤ 1)
    (hX_unit : ∀ i k ω, 0 ≤ X i k ω ∧ X i k ω ≤ 1)
    (hstrategy_range : ∀ j k ω,
      0 ≤ strategy j k ω ∧ strategy j k ω ≤ L)
    (j n : ℕ) (ω : Ω) :
    countableForwardPredictableStrategyPACBayesComponent
        prior X risk strategy j n ω ≤
      Real.exp ((n : ℝ) * L) := by
  unfold countableForwardPredictableStrategyPACBayesComponent
    finiteWeightedProcess
  calc
    (∑ i : ι, prior i *
        forwardPredictableTiltMeanEmpiricalBernsteinLowerProcess
          (X i) (fun _ _ ↦ risk i) (strategy j) n ω) ≤
        ∑ i : ι, prior i * Real.exp ((n : ℝ) * L) := by
      apply Finset.sum_le_sum
      intro i _
      apply mul_le_mul_of_nonneg_left _ (hprior.nonneg i)
      exact forwardPredictableTiltMeanEmpiricalBernsteinLowerProcess_le_exp
        hL1 (hX_unit i) (fun _ _ ↦ (hrisk i).2)
        (hstrategy_range j) n ω
    _ = Real.exp ((n : ℝ) * L) := by
      rw [← Finset.sum_mul, hprior.sum_one, one_mul]

omit [DecidableEq ι] [Nonempty ι] in
/-- The weighted outer series is summable at every time and path. -/
theorem countableForwardPredictableStrategyPACBayesMasterProcess_pointwise_summable
    {prior : ι → ℝ} (hprior : IsPMF prior)
    {weight : ℕ → ℝ} (hweight_nonneg : ∀ j, 0 ≤ weight j)
    (hweight_summable : Summable weight)
    {X : ι → ℕ → Ω → ℝ} {risk : ι → ℝ}
    {strategy : ℕ → ℕ → Ω → ℝ} {L : ℝ}
    (hL1 : L < 1)
    (hrisk : ∀ i, 0 ≤ risk i ∧ risk i ≤ 1)
    (hX_unit : ∀ i k ω, 0 ≤ X i k ω ∧ X i k ω ≤ 1)
    (hstrategy_range : ∀ j k ω,
      0 ≤ strategy j k ω ∧ strategy j k ω ≤ L)
    (n : ℕ) (ω : Ω) :
    Summable fun j ↦ weight j *
      countableForwardPredictableStrategyPACBayesComponent
        prior X risk strategy j n ω := by
  let C := Real.exp ((n : ℝ) * L)
  have hbound : Summable fun j ↦ weight j * C :=
    hweight_summable.mul_right C
  exact hbound.of_nonneg_of_le
    (fun j ↦ mul_nonneg (hweight_nonneg j)
      (countableForwardPredictableStrategyPACBayesComponent_nonneg
        hprior X risk strategy j n ω))
    (fun j ↦ mul_le_mul_of_nonneg_left
      (countableForwardPredictableStrategyPACBayesComponent_le_exp
        hprior hL1 hrisk hX_unit hstrategy_range j n ω)
      (hweight_nonneg j))

omit [DecidableEq ι] [Nonempty ι] in
/-- Pointwise nonnegativity of the countable strategy master process. -/
theorem countableForwardPredictableStrategyPACBayesMasterProcess_nonneg
    {prior : ι → ℝ} (hprior : IsPMF prior)
    {weight : ℕ → ℝ} (hweight_nonneg : ∀ j, 0 ≤ weight j)
    (X : ι → ℕ → Ω → ℝ) (risk : ι → ℝ)
    (strategy : ℕ → ℕ → Ω → ℝ) :
    0 ≤ countableForwardPredictableStrategyPACBayesMasterProcess
      prior weight X risk strategy := by
  unfold countableForwardPredictableStrategyPACBayesMasterProcess
  exact countableWeightedProcess_nonneg hweight_nonneg fun j n ω ↦
    countableForwardPredictableStrategyPACBayesComponent_nonneg
      hprior X risk strategy j n ω

omit [DecidableEq ι] [Nonempty ι] in
/-- The normalized countable strategy master inherits the common exponential
envelope. -/
theorem countableForwardPredictableStrategyPACBayesMasterProcess_le_exp
    {prior : ι → ℝ} (hprior : IsPMF prior)
    {weight : ℕ → ℝ} (hweight_nonneg : ∀ j, 0 ≤ weight j)
    (hweight_sum_one : HasSum weight 1)
    {X : ι → ℕ → Ω → ℝ} {risk : ι → ℝ}
    {strategy : ℕ → ℕ → Ω → ℝ} {L : ℝ}
    (hL1 : L < 1)
    (hrisk : ∀ i, 0 ≤ risk i ∧ risk i ≤ 1)
    (hX_unit : ∀ i k ω, 0 ≤ X i k ω ∧ X i k ω ≤ 1)
    (hstrategy_range : ∀ j k ω,
      0 ≤ strategy j k ω ∧ strategy j k ω ≤ L)
    (n : ℕ) (ω : Ω) :
    countableForwardPredictableStrategyPACBayesMasterProcess
        prior weight X risk strategy n ω ≤
      Real.exp ((n : ℝ) * L) := by
  let C := Real.exp ((n : ℝ) * L)
  have hseries :=
    countableForwardPredictableStrategyPACBayesMasterProcess_pointwise_summable
      (X := X) (risk := risk) (strategy := strategy)
      hprior hweight_nonneg hweight_sum_one.summable hL1 hrisk
      hX_unit hstrategy_range n ω
  have hbound_series : Summable fun j ↦ weight j * C :=
    hweight_sum_one.summable.mul_right C
  unfold countableForwardPredictableStrategyPACBayesMasterProcess
    countableWeightedProcess
  calc
    (∑' j, weight j *
        countableForwardPredictableStrategyPACBayesComponent
          prior X risk strategy j n ω) ≤
        ∑' j, weight j * C :=
      hseries.tsum_le_tsum
        (fun j ↦ mul_le_mul_of_nonneg_left
          (countableForwardPredictableStrategyPACBayesComponent_le_exp
            hprior hL1 hrisk hX_unit hstrategy_range j n ω)
          (hweight_nonneg j))
        hbound_series
    _ = C := by simpa using (hweight_sum_one.mul_right C).tsum_eq

omit [Nonempty ι] in
/-- The automatically summable outer strategy series is strongly adapted. -/
theorem countableForwardPredictableStrategyPACBayesMasterProcess_stronglyAdapted
    [IsProbabilityMeasure μ]
    {prior : ι → ℝ} (hprior : IsFullSupportPMF prior)
    {weight : ℕ → ℝ} (hweight_nonneg : ∀ j, 0 ≤ weight j)
    (hweight_sum_one : HasSum weight 1)
    {X : ι → ℕ → Ω → ℝ} {risk : ι → ℝ}
    {strategy : ℕ → ℕ → Ω → ℝ} {L : ℝ}
    (hL1 : L < 1)
    (hrisk : ∀ i, 0 ≤ risk i ∧ risk i ≤ 1)
    (hX_adapted : ∀ i, IncrementAdapted ℱ (X i))
    (hstrategy_adapted : ∀ j, StronglyAdapted ℱ (strategy j))
    (hX_unit : ∀ i k ω, 0 ≤ X i k ω ∧ X i k ω ≤ 1)
    (hstrategy_range : ∀ j k ω,
      0 ≤ strategy j k ω ∧ strategy j k ω ≤ L)
    (hmean : ∀ i k, μ[X i k | ℱ k] =ᵐ[μ] fun _ ↦ risk i) :
    StronglyAdapted ℱ
      (countableForwardPredictableStrategyPACBayesMasterProcess
        prior weight X risk strategy) := by
  intro n
  unfold countableForwardPredictableStrategyPACBayesMasterProcess
    countableWeightedProcess
  refine stronglyMeasurable_of_tendsto Filter.atTop
    (f := fun N ω ↦ ∑ j ∈ Finset.range N,
      weight j *
        countableForwardPredictableStrategyPACBayesComponent
          prior X risk strategy j n ω)
    (g := fun ω ↦ ∑' j,
      weight j *
        countableForwardPredictableStrategyPACBayesComponent
          prior X risk strategy j n ω) ?_ ?_
  · intro N
    have hsum := Finset.stronglyMeasurable_sum (Finset.range N)
      (fun j _ ↦
        (((countableForwardPredictableStrategyPACBayesComponent_eProcess_of_bounded
          hprior hL1 hX_adapted hstrategy_adapted hX_unit
            hstrategy_range hmean j).supermartingale).stronglyAdapted n).const_mul
              (weight j))
    convert hsum using 1
    ext ω
    simp only [Finset.sum_apply]
  · rw [tendsto_pi_nhds]
    intro ω
    exact
      (countableForwardPredictableStrategyPACBayesMasterProcess_pointwise_summable
        (X := X) (risk := risk) (strategy := strategy)
        hprior.toIsPMF hweight_nonneg hweight_sum_one.summable hL1
        hrisk hX_unit hstrategy_range n ω).hasSum.tendsto_sum_nat

omit [Nonempty ι] in
/-- The bounded countable strategy master is integrable at every time. -/
theorem countableForwardPredictableStrategyPACBayesMasterProcess_integrable
    [IsProbabilityMeasure μ]
    {prior : ι → ℝ} (hprior : IsFullSupportPMF prior)
    {weight : ℕ → ℝ} (hweight_nonneg : ∀ j, 0 ≤ weight j)
    (hweight_sum_one : HasSum weight 1)
    {X : ι → ℕ → Ω → ℝ} {risk : ι → ℝ}
    {strategy : ℕ → ℕ → Ω → ℝ} {L : ℝ}
    (hL1 : L < 1)
    (hrisk : ∀ i, 0 ≤ risk i ∧ risk i ≤ 1)
    (hX_adapted : ∀ i, IncrementAdapted ℱ (X i))
    (hstrategy_adapted : ∀ j, StronglyAdapted ℱ (strategy j))
    (hX_unit : ∀ i k ω, 0 ≤ X i k ω ∧ X i k ω ≤ 1)
    (hstrategy_range : ∀ j k ω,
      0 ≤ strategy j k ω ∧ strategy j k ω ≤ L)
    (hmean : ∀ i k, μ[X i k | ℱ k] =ᵐ[μ] fun _ ↦ risk i)
    (n : ℕ) :
    Integrable
      (countableForwardPredictableStrategyPACBayesMasterProcess
        prior weight X risk strategy n) μ := by
  let C := Real.exp ((n : ℝ) * L)
  have hadapted :=
    countableForwardPredictableStrategyPACBayesMasterProcess_stronglyAdapted
      hprior hweight_nonneg hweight_sum_one hL1 hrisk hX_adapted
      hstrategy_adapted hX_unit hstrategy_range hmean
  refine Integrable.of_bound
    ((hadapted n).mono (ℱ.le n)).aestronglyMeasurable C ?_
  exact Filter.Eventually.of_forall fun ω ↦ by
    rw [Real.norm_eq_abs, abs_of_nonneg
      (countableForwardPredictableStrategyPACBayesMasterProcess_nonneg
        hprior.toIsPMF hweight_nonneg X risk strategy n ω)]
    exact countableForwardPredictableStrategyPACBayesMasterProcess_le_exp
      hprior.toIsPMF hweight_nonneg hweight_sum_one hL1 hrisk
      hX_unit hstrategy_range n ω

omit [DecidableEq ι] [Nonempty ι] in
/-- The component set-integral norms are dominated by one summable weight
sequence. -/
theorem countableForwardPredictableStrategyPACBayesMasterProcess_integralNorm_summable
    [IsProbabilityMeasure μ]
    {prior : ι → ℝ} (hprior : IsFullSupportPMF prior)
    {weight : ℕ → ℝ} (hweight_nonneg : ∀ j, 0 ≤ weight j)
    (hweight_sum_one : HasSum weight 1)
    {X : ι → ℕ → Ω → ℝ} {risk : ι → ℝ}
    {strategy : ℕ → ℕ → Ω → ℝ} {L : ℝ}
    (hL1 : L < 1)
    (hrisk : ∀ i, 0 ≤ risk i ∧ risk i ≤ 1)
    (hX_unit : ∀ i k ω, 0 ≤ X i k ω ∧ X i k ω ≤ 1)
    (hstrategy_range : ∀ j k ω,
      0 ≤ strategy j k ω ∧ strategy j k ω ≤ L)
    (n : ℕ) (s : Set Ω) (_hs : MeasurableSet s) :
    Summable fun j ↦ ∫ ω in s,
      ‖weight j *
        countableForwardPredictableStrategyPACBayesComponent
          prior X risk strategy j n ω‖ ∂μ := by
  let C := Real.exp ((n : ℝ) * L)
  have hC : 0 ≤ C := (Real.exp_pos _).le
  have hdom : Summable fun j ↦ weight j * C :=
    hweight_sum_one.summable.mul_right C
  refine hdom.of_nonneg_of_le (fun j ↦ integral_nonneg fun _ ↦ norm_nonneg _) ?_
  intro j
  have hconst_nonneg : 0 ≤ weight j * C :=
    mul_nonneg (hweight_nonneg j) hC
  have hnorm_bound : ∀ ω ∈ s,
      ‖weight j *
        countableForwardPredictableStrategyPACBayesComponent
          prior X risk strategy j n ω‖ ≤ weight j * C := by
    intro ω _hω
    rw [Real.norm_eq_abs, abs_of_nonneg
      (mul_nonneg (hweight_nonneg j)
        (countableForwardPredictableStrategyPACBayesComponent_nonneg
          hprior.toIsPMF X risk strategy j n ω))]
    exact mul_le_mul_of_nonneg_left
      (countableForwardPredictableStrategyPACBayesComponent_le_exp
        hprior.toIsPMF hL1 hrisk hX_unit hstrategy_range j n ω)
      (hweight_nonneg j)
  have hset := norm_setIntegral_le_of_norm_le_const
    (μ := μ) (s := s)
    (f := fun ω ↦ ‖weight j *
      countableForwardPredictableStrategyPACBayesComponent
        prior X risk strategy j n ω‖)
    (measure_lt_top μ s) (fun ω hω ↦ by
      rw [Real.norm_eq_abs, abs_of_nonneg (norm_nonneg _)]
      exact hnorm_bound ω hω)
  have hint_nonneg : 0 ≤ ∫ ω in s,
      ‖weight j *
        countableForwardPredictableStrategyPACBayesComponent
          prior X risk strategy j n ω‖ ∂μ :=
    integral_nonneg fun _ ↦ norm_nonneg _
  rw [Real.norm_eq_abs, abs_of_nonneg hint_nonneg] at hset
  calc
    (∫ ω in s,
        ‖weight j *
          countableForwardPredictableStrategyPACBayesComponent
            prior X risk strategy j n ω‖ ∂μ) ≤
        (weight j * C) * μ.real s := hset
    _ ≤ (weight j * C) * 1 :=
      mul_le_mul_of_nonneg_left measureReal_le_one hconst_nonneg
    _ = weight j * C := mul_one _

omit [Nonempty ι] in
/-- The countable model-prior--strategy master is an e-process.  Its catalog
and normalized outer weights are fixed before observing the path. -/
theorem countableForwardPredictableStrategyPACBayesMasterProcess_eProcess_of_bounded
    [IsProbabilityMeasure μ]
    {prior : ι → ℝ} (hprior : IsFullSupportPMF prior)
    {weight : ℕ → ℝ} (hweight_nonneg : ∀ j, 0 ≤ weight j)
    (hweight_sum_one : HasSum weight 1)
    {X : ι → ℕ → Ω → ℝ} {risk : ι → ℝ}
    {strategy : ℕ → ℕ → Ω → ℝ} {L : ℝ}
    (hL1 : L < 1)
    (hrisk : ∀ i, 0 ≤ risk i ∧ risk i ≤ 1)
    (hX_adapted : ∀ i, IncrementAdapted ℱ (X i))
    (hstrategy_adapted : ∀ j, StronglyAdapted ℱ (strategy j))
    (hX_unit : ∀ i k ω, 0 ≤ X i k ω ∧ X i k ω ≤ 1)
    (hstrategy_range : ∀ j k ω,
      0 ≤ strategy j k ω ∧ strategy j k ω ≤ L)
    (hmean : ∀ i k, μ[X i k | ℱ k] =ᵐ[μ] fun _ ↦ risk i) :
    EProcess μ ℱ
      (countableForwardPredictableStrategyPACBayesMasterProcess
        prior weight X risk strategy) := by
  unfold countableForwardPredictableStrategyPACBayesMasterProcess
  apply countableWeightedProcess_eProcess
    hweight_nonneg hweight_sum_one
  · intro j
    exact
      countableForwardPredictableStrategyPACBayesComponent_eProcess_of_bounded
        hprior hL1 hX_adapted hstrategy_adapted hX_unit
        hstrategy_range hmean j
  · exact
      countableForwardPredictableStrategyPACBayesMasterProcess_stronglyAdapted
        hprior hweight_nonneg hweight_sum_one hL1 hrisk hX_adapted
        hstrategy_adapted hX_unit hstrategy_range hmean
  · exact
      countableForwardPredictableStrategyPACBayesMasterProcess_integrable
        hprior hweight_nonneg hweight_sum_one hL1 hrisk hX_adapted
        hstrategy_adapted hX_unit hstrategy_range hmean
  · exact
      countableForwardPredictableStrategyPACBayesMasterProcess_integralNorm_summable
        hprior hweight_nonneg hweight_sum_one hL1 hrisk
        hX_unit hstrategy_range

end

end FormalSLT.PACBayes.ForwardPredictableStrategyPACBayesCountable
