/-
Copyright (c) 2026 Robby Sneiderman. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Robby Sneiderman
-/
import FormalSLT.PACBayes.TimeUniformGaussianPACBayes
import FormalSLT.PACBayes.TimeUniformIID
import Mathlib.Probability.Distributions.Bernoulli
import Mathlib.Probability.Independence.InfinitePi

/-!
# I.i.d. continuous-hypothesis PAC-Bayes with explicit Gaussian KL

This module connects the continuous process theorem to an actual i.i.d.
bounded-loss model.  Hypotheses range over `Fin d → ℝ`; the prior and posterior
are spherical Gaussian measures; and the displayed complexity is the closed
finite-dimensional Gaussian KL formula.

The main result is time-uniform: one exceptional event controls every positive
sample size for the fixed Gaussian posterior.  Its hypotheses are stated at
the data/loss level.  The proof derives the centered increment model, the
per-hypothesis supermartingales, the Gaussian prior mixture, and the
Donsker--Varadhan inversion.
-/

open MeasureTheory ProbabilityTheory
open FormalSLT.AnytimeValid
open scoped ENNReal

namespace FormalSLT.PACBayes.IIDContinuousGaussian

open TimeUniformIID TimeUniformContinuous TimeUniformGaussian

noncomputable section

variable {Z Ω : Type*}

/-- The log-exponential process generated by an i.i.d. bounded loss. -/
def iidContinuousScore [MeasurableSpace Z] {d : ℕ}
    (dataLaw : Measure Z) (loss : GaussianParameterSpace d → Z → ℝ)
    (sample : ℕ → Ω → Z) (lam : ℝ)
    (θ : GaussianParameterSpace d) (n : ℕ) (ω : Ω) : ℝ :=
  lam * runningSum (iidLossGap dataLaw loss sample θ) n ω -
    (n : ℝ) * subGammaCgf 1 1 lam

/-- Gaussian-posterior population risk in the i.i.d. model. -/
def gaussianPosteriorPopulationRisk [MeasurableSpace Z] {d : ℕ}
    (dataLaw : Measure Z) (loss : GaussianParameterSpace d → Z → ℝ)
    (posterior : SphericalGaussianParams d) : ℝ :=
  ∫ θ, iidLossPopulationRisk dataLaw loss θ
    ∂sphericalGaussianMeasure posterior

/-- Gaussian-posterior empirical risk from the first `n` revealed samples. -/
def gaussianPosteriorEmpiricalRisk {d : ℕ}
    (loss : GaussianParameterSpace d → Z → ℝ) (sample : ℕ → Ω → Z)
    (posterior : SphericalGaussianParams d) (n : ℕ) (ω : Ω) : ℝ :=
  ∫ θ, iidLossEmpiricalRisk loss sample θ n ω
    ∂sphericalGaussianMeasure posterior

/-- Failure event for the i.i.d. Gaussian PAC-Bayes risk bound. -/
def timeUniformIIDGaussianPACBayesUpperFailure [MeasurableSpace Z] {d : ℕ}
    (dataLaw : Measure Z) (prior posterior : SphericalGaussianParams d)
    (loss : GaussianParameterSpace d → Z → ℝ) (sample : ℕ → Ω → Z)
    (lam delta : ℝ) : Set Ω :=
  {ω | ∃ n : ℕ, 0 < n ∧
    subGammaCgf 1 1 lam / lam +
        (sphericalGaussianKLClosedForm posterior prior + Real.log (1 / delta)) /
          ((n : ℝ) * lam)
      ≤ gaussianPosteriorPopulationRisk dataLaw loss posterior -
          gaussianPosteriorEmpiricalRisk loss sample posterior n ω}

/-- The i.i.d. score is the log of the standard sub-Gamma exponential process. -/
theorem exp_iidContinuousScore_eq {d : ℕ} [MeasurableSpace Z]
    (dataLaw : Measure Z) (loss : GaussianParameterSpace d → Z → ℝ)
    (sample : ℕ → Ω → Z) (lam : ℝ) (θ : GaussianParameterSpace d)
    (n : ℕ) (ω : Ω) :
    Real.exp (iidContinuousScore dataLaw loss sample lam θ n ω) =
      subGammaExponentialProcess
        (iidLossGap dataLaw loss sample θ) 1 1 lam n ω := by
  rfl

/-- A risk-bound failure implies failure of the Gaussian process boundary. -/
theorem timeUniformIIDGaussianPACBayesUpperFailure_subset_processFailure
    {d : ℕ} [MeasurableSpace Z]
    {dataLaw : Measure Z} {prior posterior : SphericalGaussianParams d}
    {loss : GaussianParameterSpace d → Z → ℝ} {sample : ℕ → Ω → Z}
    {lam delta : ℝ}
    (hlam : 0 < lam)
    (hpop_int : Integrable (iidLossPopulationRisk dataLaw loss)
      (sphericalGaussianMeasure posterior))
    (hemp_int : ∀ n ω, Integrable
      (fun θ => iidLossEmpiricalRisk loss sample θ n ω)
      (sphericalGaussianMeasure posterior)) :
    timeUniformIIDGaussianPACBayesUpperFailure
        dataLaw prior posterior loss sample lam delta
      ⊆
    timeUniformSphericalGaussianPACBayesUpperFailure prior posterior
      (iidContinuousScore dataLaw loss sample lam) delta := by
  intro ω hω
  rcases hω with ⟨n, hn, hfail⟩
  refine ⟨n, hn, ?_⟩
  have hnR : 0 < (n : ℝ) := Nat.cast_pos.mpr hn
  have hden : 0 < (n : ℝ) * lam := mul_pos hnR hlam
  have hgap_int : Integrable
      (fun θ => iidLossPopulationRisk dataLaw loss θ -
        iidLossEmpiricalRisk loss sample θ n ω)
      (sphericalGaussianMeasure posterior) :=
    hpop_int.sub (hemp_int n ω)
  have hscore_eq :
      (∫ θ, iidContinuousScore dataLaw loss sample lam θ n ω
          ∂sphericalGaussianMeasure posterior) =
        (n : ℝ) * lam *
            (gaussianPosteriorPopulationRisk dataLaw loss posterior -
              gaussianPosteriorEmpiricalRisk loss sample posterior n ω) -
          (n : ℝ) * subGammaCgf 1 1 lam := by
    have hpoint : ∀ θ,
        iidContinuousScore dataLaw loss sample lam θ n ω =
          (n : ℝ) * lam *
              (iidLossPopulationRisk dataLaw loss θ -
                iidLossEmpiricalRisk loss sample θ n ω) -
            (n : ℝ) * subGammaCgf 1 1 lam := by
      intro θ
      have hmean := iidLossGap_runningMean dataLaw loss sample θ hn ω
      simp only [runningMean] at hmean
      unfold iidContinuousScore
      rw [show runningSum (iidLossGap dataLaw loss sample θ) n ω =
          (n : ℝ) *
            (iidLossPopulationRisk dataLaw loss θ -
              iidLossEmpiricalRisk loss sample θ n ω) by
        calc
          runningSum (iidLossGap dataLaw loss sample θ) n ω =
              (runningSum (iidLossGap dataLaw loss sample θ) n ω / (n : ℝ)) *
                (n : ℝ) := by field_simp
          _ = (iidLossPopulationRisk dataLaw loss θ -
                iidLossEmpiricalRisk loss sample θ n ω) * (n : ℝ) := by
              rw [hmean]
          _ = (n : ℝ) * (iidLossPopulationRisk dataLaw loss θ -
                iidLossEmpiricalRisk loss sample θ n ω) := by ring]
      ring
    simp_rw [hpoint]
    rw [integral_sub]
    · rw [integral_const_mul, integral_sub hpop_int (hemp_int n ω)]
      simp [gaussianPosteriorPopulationRisk,
        gaussianPosteriorEmpiricalRisk]
    · exact hgap_int.const_mul ((n : ℝ) * lam)
    · exact integrable_const _
  rw [hscore_eq]
  have hmul := mul_le_mul_of_nonneg_left hfail hden.le
  field_simp [ne_of_gt hnR, ne_of_gt hlam] at hmul
  nlinarith

/--
Time-uniform i.i.d. PAC-Bayes for a continuous finite-dimensional hypothesis
space and a spherical Gaussian prior/posterior pair.

For jointly measurable losses in `[0,1]` and an i.i.d. sample stream, the
failure probability is at most `delta`.  The theorem discharges the stochastic
process and Gaussian measure obligations internally; callers provide only the
loss model, i.i.d. law, positive tilt/confidence parameters, and Gaussian
parameters.
-/
theorem timeUniformIIDGaussianPACBayes_bound
    {d : ℕ}
    [mZ : MeasurableSpace Z] [TopologicalSpace Z] [BorelSpace Z]
    [TopologicalSpace.MetrizableSpace Z]
    [mΩ : MeasurableSpace Ω] {μ : Measure Ω} [IsProbabilityMeasure μ]
    {dataLaw : Measure Z} [IsProbabilityMeasure dataLaw]
    (prior posterior : SphericalGaussianParams d)
    {loss : GaussianParameterSpace d → Z → ℝ}
    {sample : ℕ → Ω → Z} {lam delta : ℝ}
    (hδ : 0 < delta) (hlam : 0 < lam) (hlam_three : lam < 3)
    (hloss_joint : StronglyMeasurable
      (fun p : GaussianParameterSpace d × Z => loss p.1 p.2))
    (hloss_range : ∀ θ z, 0 ≤ loss θ z ∧ loss θ z ≤ 1)
    (hsample : ∀ k, StronglyMeasurable (sample k))
    (hsample_indep : iIndepFun sample μ)
    (hsample_law : ∀ k, HasLaw (sample k) dataLaw μ) :
    μ.real (timeUniformIIDGaussianPACBayesUpperFailure
      dataLaw prior posterior loss sample lam delta) ≤ delta := by
  let ℱ : Filtration ℕ mΩ := Filtration.natural sample hsample
  let X : GaussianParameterSpace d → ℕ → Ω → ℝ :=
    iidLossGap dataLaw loss sample
  let score : GaussianParameterSpace d → ℕ → Ω → ℝ :=
    iidContinuousScore dataLaw loss sample lam
  have hloss : ∀ θ, StronglyMeasurable (loss θ) := by
    intro θ
    exact hloss_joint.comp_measurable (measurable_const.prodMk measurable_id)
  have hrisk_range : ∀ θ,
      iidLossPopulationRisk dataLaw loss θ ∈ Set.Icc (0 : ℝ) 1 := by
    intro θ
    exact iidLossPopulationRisk_mem_Icc
      (dataLaw := dataLaw) θ (hloss θ) (hloss_range θ)
  have hrisk_meas : StronglyMeasurable
      (iidLossPopulationRisk dataLaw loss) := by
    change StronglyMeasurable (fun θ => ∫ z, loss θ z ∂dataLaw)
    exact hloss_joint.integral_prod_right (ν := dataLaw)
  have hX_joint : ∀ k, StronglyMeasurable
      (fun p : GaussianParameterSpace d × Ω => X p.1 k p.2) := by
    intro k
    have hobs : StronglyMeasurable
        (fun p : GaussianParameterSpace d × Ω =>
          loss p.1 (sample (k + 1) p.2)) :=
      hloss_joint.comp_measurable
        (measurable_fst.prodMk ((hsample (k + 1)).measurable.comp measurable_snd))
    change StronglyMeasurable
      ((fun p : GaussianParameterSpace d × Ω =>
          iidLossPopulationRisk dataLaw loss p.1) -
        fun p => loss p.1 (sample (k + 1) p.2))
    exact (hrisk_meas.comp_measurable measurable_fst).sub hobs
  have hX_meas : ∀ θ k, Measurable (X θ k) := by
    intro θ k
    exact iidLossGap_measurable θ k (hloss θ) hsample
  have hX_bound : ∀ θ k ω, |X θ k ω| ≤ (1 : ℝ) := by
    intro θ k ω
    exact abs_iidLossGap_le_one θ k ω (hloss θ) (hloss_range θ)
  have hX_int : ∀ θ k, Integrable (X θ k) μ := by
    intro θ k
    exact iidLossGap_integrable θ k (hloss θ) (hloss_range θ) hsample
  have hsample_adapted := Filtration.stronglyAdapted_natural hsample
  have hX_adapted : ∀ θ, IncrementAdapted ℱ (X θ) := by
    intro θ
    exact iidLossGap_incrementAdapted θ (hloss θ) hsample
  have hcenter : ∀ θ k, μ[X θ k | ℱ k] =ᵐ[μ] 0 := by
    intro θ k
    exact iidLossGap_condExp_eq_zero θ k (hloss θ) (hloss_range θ)
      hsample hsample_indep hsample_law
  have hvar : ∀ θ k,
      μ[fun ω => (X θ k ω) ^ 2 | ℱ k] ≤ᵐ[μ] fun _ => (1 : ℝ) := by
    intro θ k
    exact iidLossGap_condExp_sq_le_one θ k (hloss θ) (hloss_range θ) hsample
  have hM_int : ∀ θ n,
      Integrable (subGammaExponentialProcess (X θ) 1 1 lam n) μ := by
    intro θ n
    exact integrable_subGammaExponentialProcess_of_bounded n
      (by norm_num) (by norm_num) hlam.le (by simpa using hlam_three)
      (hX_meas θ) (fun k => Filter.Eventually.of_forall fun ω => hX_bound θ k ω)
  have hfixed : ∀ θ,
      Supermartingale (fun n ω => Real.exp (score θ n ω)) ℱ μ := by
    intro θ
    have hadapted :=
      stronglyAdapted_subGammaExponentialProcess_of_adapted 1 1 lam
        (hX_adapted θ)
    have hsup : Supermartingale
        (subGammaExponentialProcess (X θ) 1 1 lam) ℱ μ :=
      (nonneg_supermartingale_of_condSubGamma hadapted (hM_int θ)
        (condSubGamma_supermartingale_step
          (by norm_num) (by norm_num) hlam.le (by simpa using hlam_three)
          (hX_meas θ) (hX_int θ) hadapted
          (fun k => Filter.Eventually.of_forall fun ω => hX_bound θ k ω)
          (hcenter θ) (hvar θ))).1
    change Supermartingale
      (subGammaExponentialProcess
        (iidLossGap dataLaw loss sample θ) 1 1 lam) ℱ μ
    exact hsup
  have hscore_joint : ∀ n, StronglyMeasurable
      (fun p : GaussianParameterSpace d × Ω => score p.1 n p.2) := by
    intro n
    have hsum : StronglyMeasurable
        (fun p : GaussianParameterSpace d × Ω =>
          runningSum (X p.1) n p.2) := by
      have heq : (fun p : GaussianParameterSpace d × Ω =>
          runningSum (X p.1) n p.2) =
          ∑ k ∈ Finset.range n, fun p => X p.1 k p.2 := by
        funext p
        simp [runningSum, Finset.sum_apply]
      rw [heq]
      exact Finset.stronglyMeasurable_sum _ fun k _ => hX_joint k
    change StronglyMeasurable
      (fun p : GaussianParameterSpace d × Ω =>
        lam * runningSum (X p.1) n p.2 -
          (n : ℝ) * subGammaCgf 1 1 lam)
    exact (hsum.const_mul lam).sub stronglyMeasurable_const
  have hscore_bound : ∀ θ n ω,
      |score θ n ω| ≤
        lam * (n : ℝ) + |(n : ℝ) * subGammaCgf 1 1 lam| := by
    intro θ n ω
    have hsum_abs : |runningSum (X θ) n ω| ≤ (n : ℝ) := by
      calc
        |runningSum (X θ) n ω| ≤
            ∑ k ∈ Finset.range n, |X θ k ω| := by
              simpa [runningSum] using
                (Finset.abs_sum_le_sum_abs (s := Finset.range n)
                  (f := fun k => X θ k ω))
        _ ≤ ∑ _k ∈ Finset.range n, (1 : ℝ) := by
              exact Finset.sum_le_sum fun k _ => hX_bound θ k ω
        _ = (n : ℝ) := by simp
    change |lam * runningSum (X θ) n ω -
      (n : ℝ) * subGammaCgf 1 1 lam| ≤ _
    calc
      |lam * runningSum (X θ) n ω - (n : ℝ) * subGammaCgf 1 1 lam| ≤
          |lam * runningSum (X θ) n ω| +
            |(n : ℝ) * subGammaCgf 1 1 lam| := abs_sub _ _
      _ ≤ lam * (n : ℝ) + |(n : ℝ) * subGammaCgf 1 1 lam| := by
          rw [abs_mul, abs_of_pos hlam]
          simpa [add_comm] using
            (add_le_add_right (mul_le_mul_of_nonneg_left hsum_abs hlam.le)
              |(n : ℝ) * subGammaCgf 1 1 lam|)
  have hexp_joint_int_prior : ∀ n,
      Integrable (fun p : GaussianParameterSpace d × Ω =>
        Real.exp (score p.1 n p.2))
        ((sphericalGaussianMeasure prior).prod μ) := by
    intro n
    refine Integrable.of_bound (Real.continuous_exp.comp_stronglyMeasurable
      (hscore_joint n)).aestronglyMeasurable
      (Real.exp (lam * (n : ℝ) + |(n : ℝ) * subGammaCgf 1 1 lam|)) ?_
    exact Filter.Eventually.of_forall fun p => by
      rw [Real.norm_eq_abs, abs_of_nonneg (Real.exp_pos _).le]
      exact Real.exp_le_exp.mpr ((le_abs_self _).trans (hscore_bound p.1 n p.2))
  have hscore_section_int : ∀ n ω,
      Integrable (fun θ => score θ n ω)
        (sphericalGaussianMeasure posterior) := by
    intro n ω
    refine Integrable.of_bound
      ((hscore_joint n).comp_measurable
        (measurable_id.prodMk measurable_const)).aestronglyMeasurable
      (lam * (n : ℝ) + |(n : ℝ) * subGammaCgf 1 1 lam|) ?_
    exact Filter.Eventually.of_forall fun θ => hscore_bound θ n ω
  have hexp_section_int : ∀ n ω,
      Integrable (fun θ => Real.exp (score θ n ω))
        (sphericalGaussianMeasure prior) := by
    intro n ω
    refine Integrable.of_bound
      (Real.continuous_exp.comp_stronglyMeasurable
        ((hscore_joint n).comp_measurable
          (measurable_id.prodMk measurable_const))).aestronglyMeasurable
      (Real.exp (lam * (n : ℝ) + |(n : ℝ) * subGammaCgf 1 1 lam|)) ?_
    exact Filter.Eventually.of_forall fun θ => by
      rw [Real.norm_eq_abs, abs_of_nonneg (Real.exp_pos _).le]
      exact Real.exp_le_exp.mpr ((le_abs_self _).trans (hscore_bound θ n ω))
  have hpop_int : Integrable (iidLossPopulationRisk dataLaw loss)
      (sphericalGaussianMeasure posterior) :=
    Integrable.of_bound hrisk_meas.aestronglyMeasurable 1
      (Filter.Eventually.of_forall fun θ => by
        rw [Real.norm_eq_abs, abs_of_nonneg (hrisk_range θ).1]
        exact (hrisk_range θ).2)
  have hemp_int : ∀ n ω, Integrable
      (fun θ => iidLossEmpiricalRisk loss sample θ n ω)
      (sphericalGaussianMeasure posterior) := by
    intro n ω
    by_cases hn : n = 0
    · subst n
      simp [iidLossEmpiricalRisk]
    · have hemp_meas : StronglyMeasurable
          (fun θ => iidLossEmpiricalRisk loss sample θ n ω) := by
        unfold iidLossEmpiricalRisk
        change StronglyMeasurable
          (fun θ => (∑ k ∈ Finset.range n, loss θ (sample (k + 1) ω)) *
            (n : ℝ)⁻¹)
        apply StronglyMeasurable.mul_const
        have heq : (fun θ : GaussianParameterSpace d =>
            ∑ k ∈ Finset.range n, loss θ (sample (k + 1) ω)) =
            ∑ k ∈ Finset.range n,
              (fun θ : GaussianParameterSpace d => loss θ (sample (k + 1) ω)) := by
          funext θ
          simp [Finset.sum_apply]
        rw [heq]
        apply Finset.stronglyMeasurable_sum
        intro k _hk
        simpa [Function.comp_def] using
          hloss_joint.comp_measurable
            (measurable_id.prodMk (measurable_const :
              Measurable (fun _ : GaussianParameterSpace d => sample (k + 1) ω)))
      refine Integrable.of_bound hemp_meas.aestronglyMeasurable 1 ?_
      exact Filter.Eventually.of_forall fun θ => by
        rw [Real.norm_eq_abs, abs_of_nonneg]
        · have hsum_le :
              (∑ k ∈ Finset.range n, loss θ (sample (k + 1) ω)) ≤ (n : ℝ) := by
            calc
              _ ≤ ∑ _k ∈ Finset.range n, (1 : ℝ) :=
                Finset.sum_le_sum fun k _ => (hloss_range θ _).2
              _ = (n : ℝ) := by simp
          exact (div_le_one (Nat.cast_pos.mpr (Nat.pos_of_ne_zero hn))).mpr hsum_le
        · exact div_nonneg
            (Finset.sum_nonneg fun k _ => (hloss_range θ _).1) (Nat.cast_nonneg n)
  have h_adapted_mix : StronglyAdapted ℱ
      (continuousExponentialMixtureProcess
        (sphericalGaussianMeasure prior) score) := by
    intro n
    have hjoint : StronglyMeasurable[(inferInstance :
        MeasurableSpace (GaussianParameterSpace d)).prod (ℱ n)]
        (fun p : GaussianParameterSpace d × Ω =>
          Real.exp (score p.1 n p.2)) := by
      have hsum : StronglyMeasurable[(inferInstance :
          MeasurableSpace (GaussianParameterSpace d)).prod (ℱ n)]
          (fun p : GaussianParameterSpace d × Ω =>
            runningSum (X p.1) n p.2) := by
        have heq : (fun p : GaussianParameterSpace d × Ω =>
            runningSum (X p.1) n p.2) =
            ∑ k ∈ Finset.range n, fun p => X p.1 k p.2 := by
          funext p
          simp [runningSum, Finset.sum_apply]
        rw [heq]
        apply Finset.stronglyMeasurable_sum
        intro k hk
        have hklt : k < n := Finset.mem_range.mp hk
        have hobs : StronglyMeasurable[(inferInstance :
            MeasurableSpace (GaussianParameterSpace d)).prod (ℱ n)]
            (fun p : GaussianParameterSpace d × Ω =>
              loss p.1 (sample (k + 1) p.2)) := by
          exact hloss_joint.comp_measurable
            (measurable_fst.prodMk
              (((hsample_adapted (k + 1)).mono
                (ℱ.mono (Nat.succ_le_of_lt hklt))).measurable.comp measurable_snd))
        change StronglyMeasurable[(inferInstance :
            MeasurableSpace (GaussianParameterSpace d)).prod (ℱ n)]
          ((fun p : GaussianParameterSpace d × Ω =>
              iidLossPopulationRisk dataLaw loss p.1) -
            fun p => loss p.1 (sample (k + 1) p.2))
        exact (hrisk_meas.comp_measurable measurable_fst).sub hobs
      have hbody : StronglyMeasurable[(inferInstance :
          MeasurableSpace (GaussianParameterSpace d)).prod (ℱ n)]
          (fun p : GaussianParameterSpace d × Ω =>
            lam * runningSum (X p.1) n p.2 -
              (n : ℝ) * subGammaCgf 1 1 lam) :=
        (hsum.const_mul lam).sub stronglyMeasurable_const
      exact Real.continuous_exp.comp_stronglyMeasurable hbody
    change StronglyMeasurable[ℱ n]
      (fun ω => ∫ θ, Real.exp (score θ n ω)
        ∂sphericalGaussianMeasure prior)
    letI : MeasurableSpace Ω := ℱ n
    exact (hjoint.comp_measurable measurable_swap).integral_prod_right'
  have h_integrable_mix : ∀ n, Integrable
      (continuousExponentialMixtureProcess
        (sphericalGaussianMeasure prior) score n) μ := by
    intro n
    exact (hexp_joint_int_prior n).integral_prod_right
  have hM_int_next : ∀ n, Integrable
      (fun p : GaussianParameterSpace d × Ω =>
        Real.exp (score p.1 (n + 1) p.2))
      ((sphericalGaussianMeasure prior).prod μ) :=
    fun n => hexp_joint_int_prior (n + 1)
  have hM_int_current : ∀ n, Integrable
      (fun p : Ω × GaussianParameterSpace d =>
        Real.exp (score p.2 n p.1))
      (μ.prod (sphericalGaussianMeasure prior)) := by
    intro n
    simpa [Function.comp_def] using (hexp_joint_int_prior n).swap
  have hM_int_restrict : ∀ n, ∀ {s : Set Ω}, MeasurableSet s → μ s < ⊤ →
      Integrable (fun p : Ω × GaussianParameterSpace d =>
        Real.exp (score p.2 n p.1))
      ((μ.restrict s).prod (sphericalGaussianMeasure prior)) := by
    intro n s hs hμs
    have hmeas : StronglyMeasurable
        (fun p : Ω × GaussianParameterSpace d =>
          Real.exp (score p.2 n p.1)) :=
      (Real.continuous_exp.comp_stronglyMeasurable
        ((hscore_joint n).comp_measurable measurable_swap))
    refine Integrable.of_bound hmeas.aestronglyMeasurable
      (Real.exp (lam * (n : ℝ) + |(n : ℝ) * subGammaCgf 1 1 lam|)) ?_
    exact Filter.Eventually.of_forall fun p => by
      rw [Real.norm_eq_abs, abs_of_nonneg (Real.exp_pos _).le]
      exact Real.exp_le_exp.mpr ((le_abs_self _).trans (hscore_bound p.2 n p.1))
  have hprocess := timeUniformSphericalGaussianPACBayes_bound
    (μ := μ) (ℱ := ℱ) prior posterior score hδ h_adapted_mix
    h_integrable_mix hM_int_next
    (fun n s hs hμs => hM_int_restrict (n + 1) hs hμs)
    hM_int_current hM_int_restrict
    (Filter.Eventually.of_forall hfixed)
    (fun θ ω => by simp [score, iidContinuousScore, runningSum])
    hexp_section_int hscore_section_int
  exact (measureReal_mono
    (timeUniformIIDGaussianPACBayesUpperFailure_subset_processFailure
      (dataLaw := dataLaw) (prior := prior) (posterior := posterior)
      (loss := loss) (sample := sample) (lam := lam) (delta := delta)
      hlam hpop_int hemp_int)).trans hprocess

/-! ### Evaluated Gaussian complexity -/

/-- Standard one-dimensional Gaussian prior `N(0, 1)`. -/
def standardGaussianPrior : SphericalGaussianParams 1 where
  mean := fun _ => 0
  variance := 1
  variance_pos := by norm_num

/-- Shifted one-dimensional Gaussian posterior `N(1, 1)`. -/
def shiftedGaussianPosterior : SphericalGaussianParams 1 where
  mean := fun _ => 1
  variance := 1
  variance_pos := by norm_num

/-- The explicit KL of `N(1,1)` against `N(0,1)` is exactly `1/2`. -/
theorem shiftedGaussian_kl_closedForm :
    sphericalGaussianKLClosedForm shiftedGaussianPosterior standardGaussianPrior =
      (1 : ℝ) / 2 := by
  norm_num [sphericalGaussianKLClosedForm, shiftedGaussianPosterior,
    standardGaussianPrior, squaredMeanDistance]

/-- At `λ = 1`, `n = 10`, and `δ = exp(-1)`, the complete displayed penalty is `9/10`. -/
theorem shiftedGaussian_penalty_evaluated :
    subGammaCgf 1 1 1 / 1 +
        (sphericalGaussianKLClosedForm shiftedGaussianPosterior standardGaussianPrior +
          Real.log (1 / Real.exp (-1))) / ((10 : ℝ) * 1) =
      (9 : ℝ) / 10 := by
  rw [shiftedGaussian_kl_closedForm]
  rw [show (1 / Real.exp (-1 : ℝ)) = Real.exp 1 by
    rw [one_div, ← Real.exp_neg]
    norm_num]
  rw [Real.log_exp]
  norm_num [subGammaCgf]

/-! ### Minimal deterministic sanity check -/

/-- Deterministic i.i.d. stream used to instantiate every assumption of the theorem. -/
def unitSample (_k : ℕ) (_ω : Unit) : Unit := ()

/-- A concrete bounded loss with population and empirical value `1/2`. -/
def unitHalfLoss (_θ : GaussianParameterSpace 1) (_z : Unit) : ℝ := (1 : ℝ) / 2

/-- The deterministic unit stream is independent under its Dirac law. -/
theorem unitSample_iIndep :
    iIndepFun unitSample (Measure.dirac ()) := by
  change iIndepFun (fun _ : ℕ => fun _ : Unit => ()) (Measure.dirac ())
  rw [iIndepFun_iff_measure_inter_preimage_eq_mul]
  intro S sets _hsets
  simp
  by_cases hall : ∀ i ∈ S, () ∈ sets i
  · have hmem : () ∈ ⋂ i ∈ S, sets i := by
      simp only [Set.mem_iInter]
      exact fun i => fun hi => hall i hi
    rw [Set.indicator_of_mem hmem]
    rw [Finset.prod_eq_one]
    · simp
    · intro i hi
      exact Set.indicator_of_mem (hall i hi) (fun _ : Unit => (1 : ENNReal))
  · obtain ⟨i, hi⟩ := Classical.not_forall.mp hall
    obtain ⟨hiS, hnot⟩ := Classical.not_imp.mp hi
    have hnotmem : () ∉ ⋂ i ∈ S, sets i := by
      intro hmem
      exact hnot (Set.mem_iInter.mp (Set.mem_iInter.mp hmem i) hiS)
    rw [Set.indicator_of_notMem hnotmem]
    rw [Finset.prod_eq_zero hiS]
    exact Set.indicator_of_notMem hnot (fun _ : Unit => (1 : ENNReal))

/--
Concrete end-to-end certificate: `N(0,1)` prior, `N(1,1)` posterior,
`δ = exp(-1)`, `λ = 1`, and an explicitly bounded i.i.d. loss model.

Together with `shiftedGaussian_penalty_evaluated`, the time-10 term in this
certificate has the fully evaluated penalty `9/10`. This deterministic sanity
check is deliberately vacuous: the constant `1/2` loss makes population and
empirical risks equal, so its failure event is empty. For a stochastic,
nonconstant example with a positive-mass failure cylinder, see
`fairBoolThreshold_endToEnd_certificate` and
`fairBoolGaussianPACBayesFailure_mass_ge_twoPowNegHundred`.
-/
theorem unitHalfLoss_endToEnd_certificate :
    (Measure.dirac ()).real
        (timeUniformIIDGaussianPACBayesUpperFailure
          (Measure.dirac ()) standardGaussianPrior shiftedGaussianPosterior
          unitHalfLoss unitSample 1 (Real.exp (-1))) ≤
      Real.exp (-1) := by
  refine timeUniformIIDGaussianPACBayes_bound
    (μ := Measure.dirac ()) (dataLaw := Measure.dirac ())
    standardGaussianPrior shiftedGaussianPosterior
    (loss := unitHalfLoss) (sample := unitSample)
    (lam := 1) (delta := Real.exp (-1))
    (Real.exp_pos _)
    (by norm_num) (by norm_num) ?_ ?_ ?_ unitSample_iIndep ?_
  · exact stronglyMeasurable_const
  · intro θ z
    norm_num [unitHalfLoss]
  · intro k
    exact stronglyMeasurable_const
  · intro k
    exact hasLaw_dirac_of_ae_eq
      (Filter.Eventually.of_forall fun ω => by simp [unitSample])

/-! ### Stochastic fair-Bernoulli example -/

/-- The fair law on `Bool`, used as the marginal law in the stochastic example. -/
noncomputable def fairBoolLaw : Measure Bool :=
  bernoulliMeasure true false
    ⟨(1 : ℝ) / 2, by norm_num, by norm_num⟩

/-- The fair Bernoulli law is a probability measure. -/
theorem fairBoolLaw_isProbabilityMeasure :
    IsProbabilityMeasure fairBoolLaw := by
  unfold fairBoolLaw
  infer_instance

/-- Sample space for an infinite sequence of fair Boolean observations. -/
abbrev FairBoolStream := ℕ → Bool

/-- Infinite product law for the fair Bernoulli sample stream. -/
noncomputable def fairBoolStreamLaw : Measure FairBoolStream :=
  Measure.infinitePi (fun _ : ℕ => fairBoolLaw)

/-- The infinite fair-Bernoulli product law is a probability measure. -/
theorem fairBoolStreamLaw_isProbabilityMeasure :
    IsProbabilityMeasure fairBoolStreamLaw := by
  letI := fairBoolLaw_isProbabilityMeasure
  unfold fairBoolStreamLaw
  infer_instance

/-- The `k`th observation in the Bernoulli product stream. -/
def fairBoolCoordinateSample (k : ℕ) (ω : FairBoolStream) : Bool :=
  ω k

/--
A nonconstant bounded loss whose value changes with both the Boolean label and
the sign of the Gaussian parameter's only coordinate.
-/
def gaussianThresholdBoolLoss
    (θ : GaussianParameterSpace 1) (z : Bool) : ℝ :=
  if z then
    if 0 ≤ θ 0 then 0 else (1 : ℝ) / 4
  else
    if 0 ≤ θ 0 then 1 else (3 : ℝ) / 4

/-- On the nonnegative branch, the two Boolean labels have losses `0` and `1`. -/
theorem gaussianThresholdBoolLoss_of_nonneg
    (θ : GaussianParameterSpace 1) (hθ : 0 ≤ θ 0) :
    gaussianThresholdBoolLoss θ true = 0 ∧
      gaussianThresholdBoolLoss θ false = 1 := by
  simp [gaussianThresholdBoolLoss, hθ]

/-- On the negative branch, the two Boolean labels have losses `1/4` and `3/4`. -/
theorem gaussianThresholdBoolLoss_of_neg
    (θ : GaussianParameterSpace 1) (hθ : θ 0 < 0) :
    gaussianThresholdBoolLoss θ true = (1 : ℝ) / 4 ∧
      gaussianThresholdBoolLoss θ false = (3 : ℝ) / 4 := by
  simp [gaussianThresholdBoolLoss, not_le.mpr hθ]

/-- The Gaussian-threshold Boolean loss is jointly strongly measurable. -/
theorem gaussianThresholdBoolLoss_stronglyMeasurable :
    StronglyMeasurable
      (fun p : GaussianParameterSpace 1 × Bool =>
        gaussianThresholdBoolLoss p.1 p.2) := by
  unfold gaussianThresholdBoolLoss
  refine StronglyMeasurable.ite
    (measurable_snd (measurableSet_singleton true)) ?_ ?_
  · exact StronglyMeasurable.ite
      (measurableSet_le measurable_const (by fun_prop))
      stronglyMeasurable_const stronglyMeasurable_const
  · exact StronglyMeasurable.ite
      (measurableSet_le measurable_const (by fun_prop))
      stronglyMeasurable_const stronglyMeasurable_const

/-- The Gaussian-threshold Boolean loss takes values in `[0,1]`. -/
theorem gaussianThresholdBoolLoss_range :
    ∀ θ z, 0 ≤ gaussianThresholdBoolLoss θ z ∧
      gaussianThresholdBoolLoss θ z ≤ 1 := by
  intro θ z
  simp only [gaussianThresholdBoolLoss]
  split <;> split <;> norm_num

/-- Every Gaussian threshold has population risk `1/2` under the fair law. -/
theorem fairBoolPopulationRisk_eq_half (θ : GaussianParameterSpace 1) :
    iidLossPopulationRisk fairBoolLaw gaussianThresholdBoolLoss θ =
      (1 : ℝ) / 2 := by
  unfold iidLossPopulationRisk fairBoolLaw
  rw [integral_bernoulliMeasure]
  by_cases hθ : 0 ≤ θ 0 <;>
    simp [gaussianThresholdBoolLoss, hθ] <;> norm_num

/-- The coordinate observations are mutually independent under the product law. -/
theorem fairBoolCoordinateSample_iIndep :
    iIndepFun fairBoolCoordinateSample fairBoolStreamLaw := by
  letI := fairBoolLaw_isProbabilityMeasure
  exact iIndepFun_infinitePi (X := fun _ (z : Bool) => z)
    (fun _ => measurable_id)

/-- Every coordinate observation has the fair Bernoulli marginal law. -/
theorem fairBoolCoordinateSample_hasLaw (k : ℕ) :
    HasLaw (fairBoolCoordinateSample k) fairBoolLaw fairBoolStreamLaw := by
  letI := fairBoolLaw_isProbabilityMeasure
  exact MeasurePreserving.hasLaw
    (measurePreserving_eval_infinitePi
      (fun _ : ℕ => fairBoolLaw) k)

/-- The finite cylinder on which observations `1, ..., n` are all `true`. -/
def firstNTrueCylinder (n : ℕ) : Set FairBoolStream :=
  Set.pi (Finset.Icc 1 n) (fun _ => {true})

/-- The all-true finite cylinder is measurable in the product sigma-algebra. -/
theorem measurableSet_firstNTrueCylinder (n : ℕ) :
    MeasurableSet (firstNTrueCylinder n) := by
  exact MeasurableSet.pi (Finset.countable_toSet _)
    (fun _ _ => MeasurableSet.singleton true)

/-- The fair product measure of the first-`n` all-true cylinder is `2⁻ⁿ`. -/
theorem fairBoolStreamLaw_firstNTrueCylinder (n : ℕ) :
    fairBoolStreamLaw (firstNTrueCylinder n) =
      ((1 : ℝ≥0∞) / 2) ^ n := by
  letI := fairBoolLaw_isProbabilityMeasure
  unfold fairBoolStreamLaw firstNTrueCylinder
  rw [Measure.infinitePi_pi]
  · simp only [fairBoolLaw, bernoulliMeasure_apply_of_mem_of_notMem,
      MeasurableSet.singleton, Set.mem_singleton_iff, Bool.false_eq_true,
      not_false_eq_true, Finset.prod_const, Nat.card_Icc, Nat.add_sub_cancel]
    congr 1
    apply (ENNReal.toReal_eq_toReal_iff' (by simp) (by simp)).mp
    norm_num
  · intro i hi
    exact MeasurableSet.singleton true

/-- Real-valued form of the fair all-true cylinder probability. -/
theorem fairBoolStreamLaw_real_firstNTrueCylinder (n : ℕ) :
    fairBoolStreamLaw.real (firstNTrueCylinder n) =
      ((1 : ℝ) / 2) ^ n := by
  rw [measureReal_def, fairBoolStreamLaw_firstNTrueCylinder]
  norm_num [ENNReal.toReal_pow]

/-- Every finite all-true cylinder has strictly positive fair product mass. -/
theorem fairBoolStreamLaw_real_firstNTrueCylinder_pos (n : ℕ) :
    0 < fairBoolStreamLaw.real (firstNTrueCylinder n) := by
  rw [fairBoolStreamLaw_real_firstNTrueCylinder]
  positivity

/-- On the first-`n` all-true cylinder, the empirical risk is the loss at `true`. -/
theorem gaussianThresholdBoolEmpiricalRisk_of_mem_firstNTrueCylinder
    {n : ℕ} (hn : 0 < n) (omega : FairBoolStream)
    (homega : omega ∈ firstNTrueCylinder n)
    (theta : GaussianParameterSpace 1) :
    iidLossEmpiricalRisk gaussianThresholdBoolLoss fairBoolCoordinateSample
        theta n omega =
      gaussianThresholdBoolLoss theta true := by
  unfold iidLossEmpiricalRisk fairBoolCoordinateSample
  have hcoordinate : ∀ k ∈ Finset.range n, omega (k + 1) = true := by
    intro k hk
    have hkIcc : k + 1 ∈ Finset.Icc 1 n := by
      exact Finset.mem_Icc.mpr
        ⟨Nat.succ_le_succ (Nat.zero_le k),
          Nat.succ_le_iff.mpr (Finset.mem_range.mp hk)⟩
    exact homega (k + 1) hkIcc
  rw [Finset.sum_congr rfl (fun k hk => by rw [hcoordinate k hk])]
  simp only [Finset.sum_const, Finset.card_range, nsmul_eq_mul]
  field_simp [Nat.cast_ne_zero.mpr hn.ne']

/-- The all-true stream is the canonical point of every all-true cylinder. -/
def allTrueBoolStream : FairBoolStream := fun _ => true

/-- At time 100, the all-true empirical risk is the loss at `true`. -/
theorem gaussianThresholdBoolEmpiricalRisk_allTrue
    (θ : GaussianParameterSpace 1) :
    iidLossEmpiricalRisk gaussianThresholdBoolLoss fairBoolCoordinateSample
        θ 100 allTrueBoolStream =
      gaussianThresholdBoolLoss θ true := by
  simp [iidLossEmpiricalRisk, fairBoolCoordinateSample, allTrueBoolStream]

/-- The posterior-averaged population risk in the worked example is `1/2`. -/
theorem fairBoolGaussianPosteriorPopulationRisk_eq_half :
    gaussianPosteriorPopulationRisk fairBoolLaw gaussianThresholdBoolLoss
        shiftedGaussianPosterior =
      (1 : ℝ) / 2 := by
  unfold gaussianPosteriorPopulationRisk
  simp_rw [fairBoolPopulationRisk_eq_half]
  simp

/-- On the all-true path, the time-100 posterior empirical risk is at most `1/4`. -/
theorem fairBoolGaussianPosteriorEmpiricalRisk_allTrue_le_quarter :
    gaussianPosteriorEmpiricalRisk gaussianThresholdBoolLoss
        fairBoolCoordinateSample shiftedGaussianPosterior 100
        allTrueBoolStream ≤
      (1 : ℝ) / 4 := by
  have hloss_true : StronglyMeasurable
      (fun θ : GaussianParameterSpace 1 => gaussianThresholdBoolLoss θ true) :=
    gaussianThresholdBoolLoss_stronglyMeasurable.comp_measurable
      (measurable_id.prodMk measurable_const)
  have hloss_true_int : Integrable
      (fun θ : GaussianParameterSpace 1 => gaussianThresholdBoolLoss θ true)
      (sphericalGaussianMeasure shiftedGaussianPosterior) := by
    refine Integrable.of_bound hloss_true.aestronglyMeasurable 1 ?_
    exact Filter.Eventually.of_forall fun θ => by
      rw [Real.norm_eq_abs, abs_of_nonneg
        (gaussianThresholdBoolLoss_range θ true).1]
      exact (gaussianThresholdBoolLoss_range θ true).2
  have hle :
      (∫ θ, gaussianThresholdBoolLoss θ true
          ∂sphericalGaussianMeasure shiftedGaussianPosterior) ≤
        ∫ _ : GaussianParameterSpace 1, (1 : ℝ) / 4
          ∂sphericalGaussianMeasure shiftedGaussianPosterior := by
    refine integral_mono hloss_true_int (integrable_const _) ?_
    intro θ
    by_cases hθ : 0 ≤ θ 0 <;>
      simp [gaussianThresholdBoolLoss, hθ]
  unfold gaussianPosteriorEmpiricalRisk
  simp_rw [gaussianThresholdBoolEmpiricalRisk_allTrue]
  simpa using hle

/-- The time-100 posterior empirical risk is at most `1/4` on the full cylinder. -/
theorem fairBoolGaussianPosteriorEmpiricalRisk_of_mem_firstHundredTrue_le_quarter
    (omega : FairBoolStream) (homega : omega ∈ firstNTrueCylinder 100) :
    gaussianPosteriorEmpiricalRisk gaussianThresholdBoolLoss
        fairBoolCoordinateSample shiftedGaussianPosterior 100 omega ≤
      (1 : ℝ) / 4 := by
  have heq :
      gaussianPosteriorEmpiricalRisk gaussianThresholdBoolLoss
          fairBoolCoordinateSample shiftedGaussianPosterior 100 omega =
        gaussianPosteriorEmpiricalRisk gaussianThresholdBoolLoss
          fairBoolCoordinateSample shiftedGaussianPosterior 100 allTrueBoolStream := by
    unfold gaussianPosteriorEmpiricalRisk
    congr with theta
    rw [gaussianThresholdBoolEmpiricalRisk_of_mem_firstNTrueCylinder
      (by norm_num) omega homega theta]
    exact (gaussianThresholdBoolEmpiricalRisk_allTrue theta).symm
  rw [heq]
  exact fairBoolGaussianPosteriorEmpiricalRisk_allTrue_le_quarter

/--
At `λ = 1/4`, `n = 100`, and `δ = exp(-1)`, the displayed penalty is
`54/275`, which is strictly below the pathwise gap lower bound `1/4`
on the entire first-100-true cylinder. This comparison proves positive failure
mass; it does not establish tightness of the penalty.
-/
theorem shiftedGaussian_nonvacuityPenalty_evaluated :
    subGammaCgf 1 1 ((1 : ℝ) / 4) / ((1 : ℝ) / 4) +
        (sphericalGaussianKLClosedForm shiftedGaussianPosterior
            standardGaussianPrior + Real.log (1 / Real.exp (-1))) /
          ((100 : ℝ) * ((1 : ℝ) / 4)) =
      (54 : ℝ) / 275 := by
  rw [shiftedGaussian_kl_closedForm]
  rw [show (1 / Real.exp (-1 : ℝ)) = Real.exp 1 by
    rw [one_div, ← Real.exp_neg]
    norm_num]
  rw [Real.log_exp]
  norm_num [subGammaCgf]

/-- The first-100-true cylinder is contained in the worked failure event. -/
theorem firstHundredTrueCylinder_subset_gaussianPACBayesFailure :
    firstNTrueCylinder 100 ⊆
      timeUniformIIDGaussianPACBayesUpperFailure
        fairBoolLaw standardGaussianPrior shiftedGaussianPosterior
        gaussianThresholdBoolLoss fairBoolCoordinateSample ((1 : ℝ) / 4)
        (Real.exp (-1)) := by
  intro omega homega
  refine ⟨100, by norm_num, ?_⟩
  change
    subGammaCgf 1 1 ((1 : ℝ) / 4) / ((1 : ℝ) / 4) +
        (sphericalGaussianKLClosedForm shiftedGaussianPosterior
            standardGaussianPrior + Real.log (1 / Real.exp (-1))) /
          ((100 : ℝ) * ((1 : ℝ) / 4)) ≤
      gaussianPosteriorPopulationRisk fairBoolLaw gaussianThresholdBoolLoss
          shiftedGaussianPosterior -
        gaussianPosteriorEmpiricalRisk gaussianThresholdBoolLoss
          fairBoolCoordinateSample shiftedGaussianPosterior 100 omega
  rw [shiftedGaussian_nonvacuityPenalty_evaluated,
    fairBoolGaussianPosteriorPopulationRisk_eq_half]
  have hemp :=
    fairBoolGaussianPosteriorEmpiricalRisk_of_mem_firstHundredTrue_le_quarter
      omega homega
  norm_num at hemp ⊢
  linarith

/-- The worked failure event has fair-product mass at least `2⁻¹⁰⁰`. -/
theorem fairBoolGaussianPACBayesFailure_mass_ge_twoPowNegHundred :
    ((1 : ℝ) / 2) ^ 100 ≤
      fairBoolStreamLaw.real
        (timeUniformIIDGaussianPACBayesUpperFailure
          fairBoolLaw standardGaussianPrior shiftedGaussianPosterior
          gaussianThresholdBoolLoss fairBoolCoordinateSample ((1 : ℝ) / 4)
          (Real.exp (-1))) := by
  letI := fairBoolStreamLaw_isProbabilityMeasure
  rw [← fairBoolStreamLaw_real_firstNTrueCylinder 100]
  exact measureReal_mono
    firstHundredTrueCylinder_subset_gaussianPACBayesFailure

/-- The worked failure event has strictly positive fair-product mass. -/
theorem fairBoolGaussianPACBayesFailure_mass_pos :
    0 < fairBoolStreamLaw.real
      (timeUniformIIDGaussianPACBayesUpperFailure
        fairBoolLaw standardGaussianPrior shiftedGaussianPosterior
        gaussianThresholdBoolLoss fairBoolCoordinateSample ((1 : ℝ) / 4)
        (Real.exp (-1))) := by
  exact (by positivity : 0 < ((1 : ℝ) / 2) ^ 100).trans_le
    fairBoolGaussianPACBayesFailure_mass_ge_twoPowNegHundred

/-- The all-true path is one point in the positive-mass failure cylinder. -/
theorem allTrueBoolStream_mem_gaussianPACBayesFailure :
    allTrueBoolStream ∈
      timeUniformIIDGaussianPACBayesUpperFailure
        fairBoolLaw standardGaussianPrior shiftedGaussianPosterior
        gaussianThresholdBoolLoss fairBoolCoordinateSample ((1 : ℝ) / 4)
        (Real.exp (-1)) := by
  apply firstHundredTrueCylinder_subset_gaussianPACBayesFailure
  intro i hi
  rfl

/--
Stochastic end-to-end certificate on a fair Bernoulli product stream.  It uses
the explicit `N(0,1)` prior and `N(1,1)` posterior, the nonconstant Gaussian
threshold loss, `δ = exp(-1)`, and `λ = 1/4`.

The population risk is exactly `1/2` by `fairBoolPopulationRisk_eq_half`; the
closed-form KL is `1/2`, and the time-100 penalty is `54/275`. The complete
first-100-true cylinder lies in the failure event, giving the explicit positive
lower bound `2⁻¹⁰⁰`. This does not claim that either probability bound is tight.
-/
theorem fairBoolThreshold_endToEnd_certificate :
    fairBoolStreamLaw.real
        (timeUniformIIDGaussianPACBayesUpperFailure
          fairBoolLaw standardGaussianPrior shiftedGaussianPosterior
          gaussianThresholdBoolLoss fairBoolCoordinateSample ((1 : ℝ) / 4)
          (Real.exp (-1))) ≤
      Real.exp (-1) := by
  letI := fairBoolLaw_isProbabilityMeasure
  letI := fairBoolStreamLaw_isProbabilityMeasure
  refine timeUniformIIDGaussianPACBayes_bound
    (μ := fairBoolStreamLaw) (dataLaw := fairBoolLaw)
    standardGaussianPrior shiftedGaussianPosterior
    (loss := gaussianThresholdBoolLoss) (sample := fairBoolCoordinateSample)
    (lam := (1 : ℝ) / 4) (delta := Real.exp (-1))
    (Real.exp_pos _)
    (by norm_num) (by norm_num)
    gaussianThresholdBoolLoss_stronglyMeasurable
    gaussianThresholdBoolLoss_range ?_ fairBoolCoordinateSample_iIndep ?_
  · intro k
    exact (measurable_pi_apply k).stronglyMeasurable
  · exact fairBoolCoordinateSample_hasLaw

end

end FormalSLT.PACBayes.IIDContinuousGaussian
