/-
Copyright (c) 2026 Robby Sneiderman. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Robby Sneiderman
-/
import FormalSLT.StochasticDynamics.MarkovRisk
import FormalSLT.PACBayes.TimeUniformIID

/-!
# Time-uniform PAC-Bayes risk for finite Markov predictor catalogs

This module combines the finite-state Markov path semantics in
`StochasticDynamics.MarkovRisk` with the posterior-uniform process theorem in
`PACBayes.TimeUniformPACBayes`.  A finite catalog of fixed one-step predictors
is evaluated along one trajectory generated by the actual Ionescu--Tulcea path
law.  Outside one measurable exceptional event, the bound holds simultaneously
for every positive time and every posterior PMF, including a posterior selected
after observing the trajectory.

The target is the posterior average of the transition-row conditional risks
encountered along the path.  It is not stationary risk.  The theorem assumes a
deterministic initial state and fixed predictors; it makes no stationarity,
mixing, irreducibility, IID, or same-trajectory-training claim.

The posterior-uniform step follows the test-supermartingale, prior-mixture,
finite Donsker--Varadhan, and Ville recipe of Chugg, Wang, and Ramdas,
"A Unified Recipe for Deriving (Time-Uniform) PAC-Bayes Bounds" (JMLR, 2023).
The contribution here is the checked specialization to the concrete finite
Markov path law and its derived conditional-risk innovations, not a new
concentration inequality or a priority claim.

The low-level mass theorem only needs `0 < delta`; applications describing
`1 - delta` as a confidence level should additionally choose `delta < 1`.
-/

open Filter Finset Function MeasureTheory ProbabilityTheory
open FormalSLT.AnytimeValid
open FormalSLT.PACBayesKL
open scoped BigOperators ENNReal NNReal Topology

namespace FormalSLT.StochasticDynamics

noncomputable section

local instance (p : Prop) : Decidable p := Classical.propDecidable p

variable {ι Z : Type*} [Fintype ι] [DecidableEq ι] [Nonempty ι]
  [Fintype Z] [MeasurableSpace Z] [MeasurableSingletonClass Z]

/-- Conditional transition risk minus observed one-step loss for predictor `q`.
This is the sign needed for an upper certificate on latent conditional risk. -/
def markovRiskShortfall (P : Z → PMF Z) (f q : Z → ℝ)
    (k : ℕ) (x : ℕ → Z) : ℝ :=
  -markovRiskInnovation P f q k x

/-- Posterior average of the observed prequential risks in a finite predictor catalog. -/
def markovPosteriorEmpiricalPrequentialRisk
    (f : Z → ℝ) (q : ι → Z → ℝ) (posterior : ι → ℝ)
    (n : ℕ) (x : ℕ → Z) : ℝ :=
  posteriorAverage posterior (fun i ↦ empiricalPrequentialRisk f (q i) n x)

/-- Posterior average of the encountered transition-row conditional risks. -/
def markovPosteriorAverageConditionalRisk
    (P : Z → PMF Z) (f : Z → ℝ) (q : ι → Z → ℝ)
    (posterior : ι → ℝ) (n : ℕ) (x : ℕ → Z) : ℝ :=
  posteriorAverage posterior (fun i ↦ averageConditionalRisk P f (q i) n x)

omit [Fintype ι] [DecidableEq ι] [Nonempty ι]
  [Fintype Z] [MeasurableSingletonClass Z] in
/-- The risk-shortfall running mean is conditional risk minus observed risk. -/
theorem runningMean_markovRiskShortfall
    (P : Z → PMF Z) (f q : Z → ℝ) (n : ℕ) (x : ℕ → Z) :
    runningMean (markovRiskShortfall P f q) n x =
      averageConditionalRisk P f q n x - empiricalPrequentialRisk f q n x := by
  rw [show markovRiskShortfall P f q =
      fun k x ↦ -markovRiskInnovation P f q k x by rfl]
  rw [runningMean_neg, runningMean_markovRiskInnovation]
  ring

omit [DecidableEq ι] [Nonempty ι]
  [Fintype Z] [MeasurableSingletonClass Z] in
/-- Posterior averaging preserves the Markov conditional-minus-observed identity. -/
theorem posteriorAverage_runningMean_markovRiskShortfall
    (P : Z → PMF Z) (f : Z → ℝ) (q : ι → Z → ℝ)
    (posterior : ι → ℝ) (n : ℕ) (x : ℕ → Z) :
    posteriorAverage posterior
        (fun i ↦ runningMean (markovRiskShortfall P f (q i)) n x) =
      markovPosteriorAverageConditionalRisk P f q posterior n x -
        markovPosteriorEmpiricalPrequentialRisk f q posterior n x := by
  unfold markovPosteriorAverageConditionalRisk
    markovPosteriorEmpiricalPrequentialRisk posteriorAverage
  rw [← Finset.sum_sub_distrib]
  apply Finset.sum_congr rfl
  intro i _hi
  change posterior i * runningMean (markovRiskShortfall P f (q i)) n x =
    posterior i * averageConditionalRisk P f (q i) n x -
      posterior i * empiricalPrequentialRisk f (q i) n x
  rw [runningMean_markovRiskShortfall]
  ring

omit [Fintype ι] [DecidableEq ι] [Nonempty ι] in
lemma markovRiskShortfall_incrementAdapted
    (P : Z → PMF Z) (f q : Z → ℝ) :
    IncrementAdapted (Filtration.piLE (X := fun _ : ℕ ↦ Z))
      (markovRiskShortfall P f q) := by
  exact incrementAdapted_neg (markovRiskInnovation_incrementAdapted P f q)

omit [Fintype ι] [DecidableEq ι] [Nonempty ι] in
lemma measurable_markovRiskShortfall
    (P : Z → PMF Z) (f q : Z → ℝ) (k : ℕ) :
    Measurable (markovRiskShortfall P f q k) :=
  (measurable_markovRiskInnovation P f q k).neg

omit [Fintype ι] [DecidableEq ι] [Nonempty ι] in
lemma integrable_markovRiskShortfall
    {P : Z → PMF Z} {x0 : Z} {f q : Z → ℝ}
    (hf : ∀ z, f z ∈ Set.Icc (0 : ℝ) 1)
    (hq : ∀ z, q z ∈ Set.Icc (0 : ℝ) 1) (k : ℕ) :
    Integrable (markovRiskShortfall P f q k) (markovPathMeasure P x0) :=
  (integrable_markovRiskInnovation (P := P) (x0 := x0) hf hq k).neg

omit [Fintype ι] [DecidableEq ι] [Nonempty ι] in
lemma abs_markovRiskShortfall_le_one
    (P : Z → PMF Z) {f q : Z → ℝ}
    (hf : ∀ z, f z ∈ Set.Icc (0 : ℝ) 1)
    (hq : ∀ z, q z ∈ Set.Icc (0 : ℝ) 1)
    (k : ℕ) (x : ℕ → Z) :
    |markovRiskShortfall P f q k x| ≤ 1 := by
  simpa [markovRiskShortfall, abs_neg] using
    abs_markovRiskInnovation_le_one P hf hq k x

omit [Fintype ι] [DecidableEq ι] [Nonempty ι] in
/-- The risk shortfall is centered under the actual Markov path law. -/
theorem markovRiskShortfall_condExp_eq_zero
    (P : Z → PMF Z) (x0 : Z) {f q : Z → ℝ}
    (hf : ∀ z, f z ∈ Set.Icc (0 : ℝ) 1)
    (hq : ∀ z, q z ∈ Set.Icc (0 : ℝ) 1) (k : ℕ) :
    (markovPathMeasure P x0)[markovRiskShortfall P f q k |
        Filtration.piLE (X := fun _ : ℕ ↦ Z) k] =ᵐ[markovPathMeasure P x0] 0 := by
  show (markovPathMeasure P x0)[fun x ↦ -markovRiskInnovation P f q k x |
      Filtration.piLE (X := fun _ : ℕ ↦ Z) k] =ᵐ[markovPathMeasure P x0] 0
  have hneg := condExp_neg (μ := markovPathMeasure P x0)
    (m := Filtration.piLE (X := fun _ : ℕ ↦ Z) k)
    (markovRiskInnovation P f q k)
  refine hneg.trans ?_
  filter_upwards [markovRiskInnovation_condExp_eq_zero P x0 hf hq k] with x hx
  simp only [Pi.neg_apply, Pi.zero_apply] at hx ⊢
  rw [hx]
  simp

omit [Fintype ι] [DecidableEq ι] [Nonempty ι] in
/-- Negation preserves the sharp universal `1/4` conditional-second-moment bound. -/
theorem markovRiskShortfall_condSecondMoment_le_one_fourth
    (P : Z → PMF Z) (x0 : Z) {f q : Z → ℝ}
    (hf : ∀ z, f z ∈ Set.Icc (0 : ℝ) 1)
    (hq : ∀ z, q z ∈ Set.Icc (0 : ℝ) 1) (k : ℕ) :
    (markovPathMeasure P x0)[fun x ↦ (markovRiskShortfall P f q k x) ^ 2 |
        Filtration.piLE (X := fun _ : ℕ ↦ Z) k] ≤ᵐ[markovPathMeasure P x0]
      fun _ ↦ (1 / 4 : ℝ) := by
  have hsq :
      (fun x ↦ (markovRiskShortfall P f q k x) ^ 2) =
        fun x ↦ (markovRiskInnovation P f q k x) ^ 2 := by
    funext x
    simp [markovRiskShortfall]
  rw [hsq]
  exact markovRiskInnovation_condSecondMoment_le_one_fourth P x0 hf hq k

/-- Risk-facing raw failure set, existential over positive times and posterior PMFs. -/
def markovPACBayesAnyPosteriorUpperFailure
    (prior : ι → ℝ) (P : Z → PMF Z) (f : Z → ℝ) (q : ι → Z → ℝ)
    (lam delta : ℝ) : Set (ℕ → Z) :=
  {x | ∃ posterior : ι → ℝ, IsPMF posterior ∧
    ∃ n : ℕ, 0 < n ∧
      subGammaCgf (1 / 4) 1 lam / lam +
          (klDiv posterior prior + Real.log (1 / delta)) / ((n : ℝ) * lam) ≤
        markovPosteriorAverageConditionalRisk P f q posterior n x -
          markovPosteriorEmpiricalPrequentialRisk f q posterior n x}

omit [DecidableEq ι] [Nonempty ι]
  [Fintype Z] [MeasurableSingletonClass Z] in
/-- A risk-facing posterior failure is a failure of the generic process theorem. -/
theorem markovPACBayesAnyPosteriorUpperFailure_subset_processFailure
    {prior : ι → ℝ} {P : Z → PMF Z} {f : Z → ℝ} {q : ι → Z → ℝ}
    {lam delta : ℝ} :
    markovPACBayesAnyPosteriorUpperFailure prior P f q lam delta ⊆
      PACBayes.TimeUniform.timeUniformPACBayesAnyPosteriorUpperFailure
        prior (fun i ↦ markovRiskShortfall P f (q i)) (1 / 4) 1 lam delta := by
  intro x hx
  rcases hx with ⟨posterior, hposterior, n, hn, hfail⟩
  refine ⟨posterior, hposterior, n, hn, ?_⟩
  rw [posteriorAverage_runningMean_markovRiskShortfall]
  exact hfail

omit [DecidableEq ι] in
/-- Fixed-tilt, all-time, all-posterior PAC-Bayes bound under the actual finite
Markov path law.  The raw posterior-existential failure set has outer mass at
most `delta`. -/
theorem markovPACBayes_allPosteriors_bound
    (P : Z → PMF Z) (x0 : Z) {f : Z → ℝ} {q : ι → Z → ℝ}
    (hf : ∀ z, f z ∈ Set.Icc (0 : ℝ) 1)
    (hq : ∀ i z, q i z ∈ Set.Icc (0 : ℝ) 1)
    {prior : ι → ℝ} (hprior : IsFullSupportPMF prior)
    {lam delta : ℝ} (hdelta : 0 < delta) (hlam : 0 < lam) (hlam_three : lam < 3) :
    (markovPathMeasure P x0).real
      (markovPACBayesAnyPosteriorUpperFailure prior P f q lam delta) ≤ delta := by
  refine (measureReal_mono
    (markovPACBayesAnyPosteriorUpperFailure_subset_processFailure
      (prior := prior) (P := P) (f := f) (q := q)
      (lam := lam) (delta := delta))).trans ?_
  exact PACBayes.TimeUniform.timeUniformPACBayes_allPosteriors_bound
    (μ := markovPathMeasure P x0)
    (ℱ := Filtration.piLE (X := fun _ : ℕ ↦ Z))
    (prior := prior) (X := fun i ↦ markovRiskShortfall P f (q i))
    (sigma2 := (1 / 4 : ℝ)) (b := (1 : ℝ))
    (lam := lam) (delta := delta) hprior hdelta
    (by norm_num) (by norm_num) hlam (by simpa using hlam_three)
    (fun i k ↦ measurable_markovRiskShortfall P f (q i) k)
    (fun i k ↦ integrable_markovRiskShortfall
      (P := P) (x0 := x0) hf (hq i) k)
    (fun i ↦ markovRiskShortfall_incrementAdapted P f (q i))
    (fun i n ↦
      PACBayes.TimeUniformIID.integrable_subGammaExponentialProcess_of_bounded n
        (by norm_num) (by norm_num) hlam.le (by simpa using hlam_three)
        (fun k ↦ measurable_markovRiskShortfall P f (q i) k)
        (fun k ↦ Filter.Eventually.of_forall fun x ↦
          abs_markovRiskShortfall_le_one P hf (hq i) k x))
    (fun i k ↦ Filter.Eventually.of_forall fun x ↦
      abs_markovRiskShortfall_le_one P hf (hq i) k x)
    (fun i k ↦ markovRiskShortfall_condExp_eq_zero P x0 hf (hq i) k)
    (fun i k ↦ markovRiskShortfall_condSecondMoment_le_one_fourth P x0 hf (hq i) k)

/-- Measurable hull of the posterior-existential Markov PAC-Bayes failure set. -/
def markovPACBayesExceptionalEvent
    (prior : ι → ℝ) (P : Z → PMF Z) (x0 : Z)
    (f : Z → ℝ) (q : ι → Z → ℝ) (lam delta : ℝ) : Set (ℕ → Z) :=
  toMeasurable (markovPathMeasure P x0)
    (markovPACBayesAnyPosteriorUpperFailure prior P f q lam delta)

omit [DecidableEq ι] [Nonempty ι] in
theorem markovPACBayesExceptionalEvent_measurable
    (prior : ι → ℝ) (P : Z → PMF Z) (x0 : Z)
    (f : Z → ℝ) (q : ι → Z → ℝ) (lam delta : ℝ) :
    MeasurableSet (markovPACBayesExceptionalEvent prior P x0 f q lam delta) :=
  measurableSet_toMeasurable _ _

omit [DecidableEq ι] [Nonempty ι] in
theorem markovPACBayesRawFailure_subset_exceptionalEvent
    (prior : ι → ℝ) (P : Z → PMF Z) (x0 : Z)
    (f : Z → ℝ) (q : ι → Z → ℝ) (lam delta : ℝ) :
    markovPACBayesAnyPosteriorUpperFailure prior P f q lam delta ⊆
      markovPACBayesExceptionalEvent prior P x0 f q lam delta :=
  subset_toMeasurable _ _

omit [DecidableEq ι] in
/-- The measurable Markov PAC-Bayes exceptional event has ordinary probability
at most `delta`. -/
theorem markovPACBayesExceptionalEvent_mass_le_delta
    (P : Z → PMF Z) (x0 : Z) {f : Z → ℝ} {q : ι → Z → ℝ}
    (hf : ∀ z, f z ∈ Set.Icc (0 : ℝ) 1)
    (hq : ∀ i z, q i z ∈ Set.Icc (0 : ℝ) 1)
    {prior : ι → ℝ} (hprior : IsFullSupportPMF prior)
    {lam delta : ℝ} (hdelta : 0 < delta) (hlam : 0 < lam) (hlam_three : lam < 3) :
    (markovPathMeasure P x0).real
      (markovPACBayesExceptionalEvent prior P x0 f q lam delta) ≤ delta := by
  rw [markovPACBayesExceptionalEvent, Measure.real, measure_toMeasurable]
  exact markovPACBayes_allPosteriors_bound P x0 hf hq hprior hdelta hlam hlam_three

omit [DecidableEq ι] [Nonempty ι] in
/-- Outside the common measurable event, every posterior and every positive
time obeys the Markov prequential PAC-Bayes upper-risk certificate. -/
theorem markovPosteriorAverageConditionalRisk_lt_of_not_mem
    (prior : ι → ℝ) (P : Z → PMF Z) (x0 : Z)
    (f : Z → ℝ) (q : ι → Z → ℝ)
    {lam delta : ℝ} {x : ℕ → Z}
    (hx : x ∉ markovPACBayesExceptionalEvent prior P x0 f q lam delta)
    (posterior : ι → ℝ) (hposterior : IsPMF posterior)
    (n : ℕ) (hn : 0 < n) :
    markovPosteriorAverageConditionalRisk P f q posterior n x <
      markovPosteriorEmpiricalPrequentialRisk f q posterior n x +
        subGammaCgf (1 / 4) 1 lam / lam +
        (klDiv posterior prior + Real.log (1 / delta)) / ((n : ℝ) * lam) := by
  have hxraw : x ∉ markovPACBayesAnyPosteriorUpperFailure prior P f q lam delta :=
    fun hraw ↦ hx (markovPACBayesRawFailure_subset_exceptionalEvent
      prior P x0 f q lam delta hraw)
  have hgap :
      markovPosteriorAverageConditionalRisk P f q posterior n x -
          markovPosteriorEmpiricalPrequentialRisk f q posterior n x <
        subGammaCgf (1 / 4) 1 lam / lam +
          (klDiv posterior prior + Real.log (1 / delta)) / ((n : ℝ) * lam) := by
    exact lt_of_not_ge fun hfail ↦ hxraw ⟨posterior, hposterior, n, hn, hfail⟩
  linarith

/-- Closed form of the sharp `1/4` sub-Gamma variance contribution. -/
theorem subGammaCgf_oneFourth_one_div
    {lam : ℝ} (hlam : 0 < lam) (hlam_three : lam < 3) :
    subGammaCgf (1 / 4) 1 lam / lam = lam / (8 * (1 - lam / 3)) := by
  have hlam_ne : lam ≠ 0 := ne_of_gt hlam
  have hden_ne : 1 - lam / 3 ≠ 0 := by linarith
  unfold subGammaCgf
  field_simp [hlam_ne, hden_ne]
  ring

omit [DecidableEq ι] in
/-- Publication-facing certificate with the explicit sharp variance term. -/
theorem markovPACBayes_prequentialRisk_certificate
    (P : Z → PMF Z) (x0 : Z) {f : Z → ℝ} {q : ι → Z → ℝ}
    (hf : ∀ z, f z ∈ Set.Icc (0 : ℝ) 1)
    (hq : ∀ i z, q i z ∈ Set.Icc (0 : ℝ) 1)
    {prior : ι → ℝ} (hprior : IsFullSupportPMF prior)
    {lam delta : ℝ} (hdelta : 0 < delta) (hlam : 0 < lam) (hlam_three : lam < 3) :
    ∃ E : Set (ℕ → Z),
      MeasurableSet E ∧
      (markovPathMeasure P x0).real E ≤ delta ∧
      ∀ x ∉ E, ∀ posterior : ι → ℝ, IsPMF posterior →
        ∀ n : ℕ, 0 < n →
          markovPosteriorAverageConditionalRisk P f q posterior n x <
            markovPosteriorEmpiricalPrequentialRisk f q posterior n x +
              lam / (8 * (1 - lam / 3)) +
              (klDiv posterior prior + Real.log (1 / delta)) / ((n : ℝ) * lam) := by
  let E := markovPACBayesExceptionalEvent prior P x0 f q lam delta
  refine ⟨E, markovPACBayesExceptionalEvent_measurable
    prior P x0 f q lam delta, ?_, ?_⟩
  · exact markovPACBayesExceptionalEvent_mass_le_delta
      P x0 hf hq hprior hdelta hlam hlam_three
  · intro x hx posterior hposterior n hn
    have hbound := markovPosteriorAverageConditionalRisk_lt_of_not_mem
      prior P x0 f q hx posterior hposterior n hn
    rw [subGammaCgf_oneFourth_one_div hlam hlam_three] at hbound
    exact hbound

end

end FormalSLT.StochasticDynamics
