import FormalSLT

/-!
# Unit-interval total-bounded Dudley example

Checks the concrete non-finite index-space example used to exercise the
total-bounded finite-net bridge.
-/

#check FormalSLT.Covering.UnitIntervalDudley.UnitInterval
#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalZero
#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalOne

#check FormalSLT.Covering.UnitIntervalDudley.unitInterval_totallyBounded_univ
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitInterval_totallyBounded_univ

#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalFiniteNet
#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalFiniteNet_covers
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitIntervalFiniteNet_covers

#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalDyadicFiniteNet
#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalDyadicFiniteNet_covers
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitIntervalDyadicFiniteNet_covers

#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalQuarterMeshCenter
#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalQuarterMeshProject
#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalHalfMeshCenter
#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalHalfMeshProject

#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalZeroProcess
#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalZeroProcess_increment_mgf
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitIntervalZeroProcess_increment_mgf

#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalZeroProcess_globalBudget
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitIntervalZeroProcess_globalBudget

#check FormalSLT.Covering.UnitIntervalDudley.unitInterval_rademacherLinear_mgf_bound
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitInterval_rademacherLinear_mgf_bound

#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalRademacherLinearProcess
#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalRademacherLinearProcess_increment_mgf
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitIntervalRademacherLinearProcess_increment_mgf

#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalRademacherLinearSup
#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalRademacherLinearSup_expectation
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitIntervalRademacherLinearSup_expectation

#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalRademacherLinearSup_dudley_m0_bound
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitIntervalRademacherLinearSup_dudley_m0_bound

#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalRademacherLinearSup_dudley_m1_bound_of_entropy
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitIntervalRademacherLinearSup_dudley_m1_bound_of_entropy

#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalDyadicPair01_card_gt_one
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitIntervalDyadicPair01_card_gt_one
#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalDyadicPair01

#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalRademacherLinearSup_dudley_m1_bound
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitIntervalRademacherLinearSup_dudley_m1_bound

#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalDyadicEntropyM1Condition
#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalDyadicEntropyCapM1
#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalDyadicEntropyM1Condition_constCap
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitIntervalDyadicEntropyM1Condition_constCap

#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalRademacherLinearSup_dudley_m1_bound_constEntropy
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitIntervalRademacherLinearSup_dudley_m1_bound_constEntropy

#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalRademacherLinearSup_dudley_m1_bound_constEntropy_eval
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitIntervalRademacherLinearSup_dudley_m1_bound_constEntropy_eval

#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalQuarterMeshNet
#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalQuarterMeshNet_covers
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitIntervalQuarterMeshNet_covers

#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalQuarterMeshNet_coveringNumber
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitIntervalQuarterMeshNet_coveringNumber

#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalHalfMeshNet
#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalHalfMeshNet_covers
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitIntervalHalfMeshNet_covers

#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalHalfMeshNet_coveringNumber
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitIntervalHalfMeshNet_coveringNumber

#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalHalfQuarterPair_card_gt_one
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitIntervalHalfQuarterPair_card_gt_one

#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalHalfQuarter_coveringNumber_product
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitIntervalHalfQuarter_coveringNumber_product

#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalRademacherLinear_halfQuarter_increment_log15_bound
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitIntervalRademacherLinear_halfQuarter_increment_log15_bound

#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalRademacherLinear_projectedQuarterMesh_dudley_log15_bound
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitIntervalRademacherLinear_projectedQuarterMesh_dudley_log15_bound

#check FormalSLT.Covering.UnitIntervalDudley.unitIntervalRademacherLinearSup_projectedQuarterMesh_dudley_log15_bound
#print axioms FormalSLT.Covering.UnitIntervalDudley.unitIntervalRademacherLinearSup_projectedQuarterMesh_dudley_log15_bound
