import FormalSLT.AnytimeValid.FiniteStrategySleepingEProcessMixture

open FormalSLT.AnytimeValid

#check finiteStrategySleepingProcessMixture
#check finiteStrategySleepingProcessMixture_eq
#check finiteStrategySleepingProcessMixture_eq_tail_add_sum
#check finiteStrategySleepingProcessMixture_nonneg
#check finiteStrategySleepingProcessMixture_eProcess
#check finiteStrategySleepingProcessMixture_competes
#check finiteStrategySleepingProcessMixture_logWealth_regret_le

#print axioms finiteStrategySleepingProcessMixture_eq
#print axioms finiteStrategySleepingProcessMixture_eq_tail_add_sum
#print axioms finiteStrategySleepingProcessMixture_nonneg
#print axioms finiteStrategySleepingProcessMixture_eProcess
#print axioms finiteStrategySleepingProcessMixture_competes
#print axioms finiteStrategySleepingProcessMixture_logWealth_regret_le
