/-
Copyright (c) 2026 Robby Sneiderman. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Robby Sneiderman
-/
import FormalSLT.StochasticDynamics.MeasurableTrajectoryRisk

open MeasureTheory ProbabilityTheory

namespace FormalSLT.Examples.CheckMeasurableTrajectoryRisk

open StochasticDynamics

noncomputable section

/-! Public surface for arbitrary measurable trajectory state spaces. -/

#check StochasticDynamics.JointlyStronglyMeasurableTrajectoryScore
#check StochasticDynamics.stronglyMeasurable_observedTrajectoryScore_succ_of_joint
#check StochasticDynamics.measurable_observedTrajectoryScore_of_joint
#check StochasticDynamics.integrable_observedTrajectoryScore_of_joint
#check StochasticDynamics.integral_observedTrajectoryScore_traj_of_joint
#check StochasticDynamics.stronglyMeasurable_conditionalTrajectoryRisk_of_joint
#check StochasticDynamics.conditionalTrajectoryRisk_mem_Icc_of_joint
#check StochasticDynamics.integrable_conditionalTrajectoryRisk_of_joint
#check StochasticDynamics.observedTrajectoryScore_condExp_of_joint
#check StochasticDynamics.trajectoryRiskInnovation_incrementAdapted_of_joint
#check StochasticDynamics.integrable_trajectoryRiskInnovation_of_joint
#check StochasticDynamics.abs_trajectoryRiskInnovation_le_one_of_joint
#check StochasticDynamics.trajectoryRiskInnovation_condExp_eq_zero_of_joint
#check StochasticDynamics.trajectoryRiskInnovation_condSecondMoment_le_one_fourth_of_joint
#check StochasticDynamics.measurableTrajectoryRiskShortfall
#check StochasticDynamics.measurableTrajectoryRiskShortfall_eq_neg_innovation
#check StochasticDynamics.measurableTrajectoryRiskShortfall_incrementAdapted_of_joint
#check StochasticDynamics.abs_measurableTrajectoryRiskShortfall_le_one_of_joint
#check StochasticDynamics.measurableTrajectoryRiskShortfall_condExp_eq_zero_of_joint
#check StochasticDynamics.measurableTrajectoryRiskShortfall_condSecondMoment_le_one_fourth_of_joint

/-! The receipt really uses an infinite state space, not a finite surrogate. -/

#synth Infinite ℝ
#check StochasticDynamics.affineRealPrefixKernel
#check StochasticDynamics.clippedRealTrajectoryScore
#check StochasticDynamics.clippedRealTrajectoryScore_jointlyStronglyMeasurable
#check StochasticDynamics.clippedRealTrajectoryScore_mem_Icc
#check StochasticDynamics.clippedRealTrajectoryScore_condExp
#check StochasticDynamics.clippedRealTrajectoryRisk_zero_prefix

#print axioms StochasticDynamics.observedTrajectoryScore_condExp_of_joint
#print axioms StochasticDynamics.trajectoryRiskInnovation_incrementAdapted_of_joint
#print axioms StochasticDynamics.abs_trajectoryRiskInnovation_le_one_of_joint
#print axioms StochasticDynamics.trajectoryRiskInnovation_condExp_eq_zero_of_joint
#print axioms StochasticDynamics.trajectoryRiskInnovation_condSecondMoment_le_one_fourth_of_joint
#print axioms StochasticDynamics.measurableTrajectoryRiskShortfall_condExp_eq_zero_of_joint
#print axioms StochasticDynamics.measurableTrajectoryRiskShortfall_condSecondMoment_le_one_fourth_of_joint
#print axioms StochasticDynamics.clippedRealTrajectoryScore_condExp
#print axioms StochasticDynamics.clippedRealTrajectoryRisk_zero_prefix

end


end FormalSLT.Examples.CheckMeasurableTrajectoryRisk
