import FormalSLT.StochasticDynamics.TrajectoryHalfTiltOrdinaryRiskPACBayes

open FormalSLT.StochasticDynamics

#check trajectoryHalfTilt
#check trajectoryPosteriorForwardPredictorQuadraticVariation
#check trajectorySingletonStrategyPMF_isFullSupportPMF
#check trajectorySingletonStrategyPMF_kl_self
#check trajectorySingletonStrategyPMF_half_average
#check trajectoryHalfTilt_quadraticPenalty_eq
#check exists_trajectoryHalfTiltPACBayes_ordinaryRisk_selected_event

#print axioms trajectorySingletonStrategyPMF_isFullSupportPMF
#print axioms trajectorySingletonStrategyPMF_kl_self
#print axioms trajectorySingletonStrategyPMF_half_average
#print axioms trajectoryHalfTilt_quadraticPenalty_eq
#print axioms exists_trajectoryHalfTiltPACBayes_ordinaryRisk_selected_event
