import FormalSLT.Rademacher.Localized

/-!
# Localized Rademacher scaffold audit

Checks the finite-class localized Rademacher/Bernstein scaffold used as the
initial step toward fast-rate localized-complexity theorems.
-/

#check FormalSLT.Rademacher.Localized.excessLoss
#print axioms FormalSLT.Rademacher.Localized.excessLoss

#check FormalSLT.Rademacher.Localized.finiteSecondMoment
#print axioms FormalSLT.Rademacher.Localized.finiteSecondMoment

#check FormalSLT.Rademacher.Localized.finiteExcessRisk
#print axioms FormalSLT.Rademacher.Localized.finiteExcessRisk

#check FormalSLT.Rademacher.Localized.empiricalMean
#print axioms FormalSLT.Rademacher.Localized.empiricalMean

#check FormalSLT.Rademacher.Localized.empiricalExcessRisk
#print axioms FormalSLT.Rademacher.Localized.empiricalExcessRisk

#check FormalSLT.Rademacher.Localized.empiricalExcessRisk_self
#print axioms FormalSLT.Rademacher.Localized.empiricalExcessRisk_self

#check FormalSLT.Rademacher.Localized.BernsteinCondition
#print axioms FormalSLT.Rademacher.Localized.BernsteinCondition

#check FormalSLT.Rademacher.Localized.LocalizedBySecondMoment
#print axioms FormalSLT.Rademacher.Localized.LocalizedBySecondMoment

#check FormalSLT.Rademacher.Localized.LocalizedByExcessRisk
#print axioms FormalSLT.Rademacher.Localized.LocalizedByExcessRisk

#check FormalSLT.Rademacher.Localized.finiteSecondMoment_nonneg
#print axioms FormalSLT.Rademacher.Localized.finiteSecondMoment_nonneg

#check FormalSLT.Rademacher.Localized.excessLoss_self
#print axioms FormalSLT.Rademacher.Localized.excessLoss_self

#check FormalSLT.Rademacher.Localized.self_mem_localizedBySecondMoment
#print axioms FormalSLT.Rademacher.Localized.self_mem_localizedBySecondMoment

#check FormalSLT.Rademacher.Localized.self_mem_localizedByExcessRisk
#print axioms FormalSLT.Rademacher.Localized.self_mem_localizedByExcessRisk

#check FormalSLT.Rademacher.Localized.bernstein_excessRisk_nonneg
#print axioms FormalSLT.Rademacher.Localized.bernstein_excessRisk_nonneg

#check FormalSLT.Rademacher.Localized.localizedBySecondMoment_of_excessRisk_le
#print axioms FormalSLT.Rademacher.Localized.localizedBySecondMoment_of_excessRisk_le

#check FormalSLT.Rademacher.Localized.localizedEmpiricalRademacherComplexity
#print axioms FormalSLT.Rademacher.Localized.localizedEmpiricalRademacherComplexity

#check FormalSLT.Rademacher.Localized.localizedEmpiricalRademacherComplexity_nonneg_of_zero
#print axioms FormalSLT.Rademacher.Localized.localizedEmpiricalRademacherComplexity_nonneg_of_zero

#check FormalSLT.Rademacher.Localized.localizedEmpiricalRademacherComplexity_mono
#print axioms FormalSLT.Rademacher.Localized.localizedEmpiricalRademacherComplexity_mono

#check FormalSLT.Rademacher.Localized.localizedSecondMomentEmpiricalRademacherComplexity
#print axioms FormalSLT.Rademacher.Localized.localizedSecondMomentEmpiricalRademacherComplexity

#check FormalSLT.Rademacher.Localized.localizedExcessRiskEmpiricalRademacherComplexity
#print axioms FormalSLT.Rademacher.Localized.localizedExcessRiskEmpiricalRademacherComplexity

#check FormalSLT.Rademacher.Localized.localizedExcessRiskEmpiricalRademacherComplexity_nonneg
#print axioms FormalSLT.Rademacher.Localized.localizedExcessRiskEmpiricalRademacherComplexity_nonneg

#check FormalSLT.Rademacher.Localized.localizedExcessRiskEmpiricalRademacherComplexity_le_secondMoment
#print axioms FormalSLT.Rademacher.Localized.localizedExcessRiskEmpiricalRademacherComplexity_le_secondMoment

#check FormalSLT.Rademacher.Localized.FixedPointUpperCertificate
#print axioms FormalSLT.Rademacher.Localized.FixedPointUpperCertificate

#check FormalSLT.Rademacher.Localized.localizedSecondMomentEmpiricalRademacherComplexity_le_of_fixedPointCertificate
#print axioms FormalSLT.Rademacher.Localized.localizedSecondMomentEmpiricalRademacherComplexity_le_of_fixedPointCertificate

#check FormalSLT.Rademacher.Localized.localizedExcessRiskEmpiricalRademacherComplexity_le_of_bernstein_fixedPointCertificate
#print axioms FormalSLT.Rademacher.Localized.localizedExcessRiskEmpiricalRademacherComplexity_le_of_bernstein_fixedPointCertificate

#check FormalSLT.Rademacher.Localized.LocalizedDeviationCertificate
#print axioms FormalSLT.Rademacher.Localized.LocalizedDeviationCertificate

#check FormalSLT.Rademacher.Localized.localizedUpperDeviation
#print axioms FormalSLT.Rademacher.Localized.localizedUpperDeviation

#check FormalSLT.Rademacher.Localized.localizedUpperDeviationEvent
#print axioms FormalSLT.Rademacher.Localized.localizedUpperDeviationEvent

#check FormalSLT.Rademacher.Localized.localizedSampleDependentUpperDeviationEvent
#print axioms FormalSLT.Rademacher.Localized.localizedSampleDependentUpperDeviationEvent

#check FormalSLT.Rademacher.Localized.localizedPointwiseUpperDeviationBadEventMass
#print axioms FormalSLT.Rademacher.Localized.localizedPointwiseUpperDeviationBadEventMass

#check FormalSLT.Rademacher.Localized.localizedUpperDeviationBadEventMass
#print axioms FormalSLT.Rademacher.Localized.localizedUpperDeviationBadEventMass

#check FormalSLT.Rademacher.Localized.localizedSampleDependentUpperDeviationBadEventMass
#print axioms FormalSLT.Rademacher.Localized.localizedSampleDependentUpperDeviationBadEventMass

#check FormalSLT.Rademacher.Localized.localizedPointwiseUpperDeviationExpMoment
#print axioms FormalSLT.Rademacher.Localized.localizedPointwiseUpperDeviationExpMoment

#check FormalSLT.Rademacher.Localized.mem_localizedUpperDeviationEvent_iff
#print axioms FormalSLT.Rademacher.Localized.mem_localizedUpperDeviationEvent_iff

#check FormalSLT.Rademacher.Localized.mem_localizedSampleDependentUpperDeviationEvent_iff
#print axioms FormalSLT.Rademacher.Localized.mem_localizedSampleDependentUpperDeviationEvent_iff

#check FormalSLT.Rademacher.Localized.localizedPointwiseUpperDeviationBadEventMass_le_expMoment_div
#print axioms FormalSLT.Rademacher.Localized.localizedPointwiseUpperDeviationBadEventMass_le_expMoment_div

#check FormalSLT.Rademacher.Localized.localizedPointwiseUpperDeviationExpMoment_finiteProduct_le_of_single
#print axioms FormalSLT.Rademacher.Localized.localizedPointwiseUpperDeviationExpMoment_finiteProduct_le_of_single

#check FormalSLT.Rademacher.Localized.localizedOneCoordinateDeviationMGF_le_of_excessLoss_mem_Icc_neg_one_one
#print axioms FormalSLT.Rademacher.Localized.localizedOneCoordinateDeviationMGF_le_of_excessLoss_mem_Icc_neg_one_one

#check FormalSLT.Rademacher.Localized.localizedUpperDeviationBadEventMass_le_sum_pointwise
#print axioms FormalSLT.Rademacher.Localized.localizedUpperDeviationBadEventMass_le_sum_pointwise

#check FormalSLT.Rademacher.Localized.localizedUpperDeviationBadEventMass_le_sum_tails
#print axioms FormalSLT.Rademacher.Localized.localizedUpperDeviationBadEventMass_le_sum_tails

#check FormalSLT.Rademacher.Localized.localizedUpperDeviationBadEventMass_le_sum_expMoment_div
#print axioms FormalSLT.Rademacher.Localized.localizedUpperDeviationBadEventMass_le_sum_expMoment_div

#check FormalSLT.Rademacher.Localized.localizedUpperDeviationBadEventMass_finiteProduct_le_sum_singleMGF
#print axioms FormalSLT.Rademacher.Localized.localizedUpperDeviationBadEventMass_finiteProduct_le_sum_singleMGF

#check FormalSLT.Rademacher.Localized.localizedUpperDeviationBadEventMass_finiteProduct_le_sum_boundedExcess
#print axioms FormalSLT.Rademacher.Localized.localizedUpperDeviationBadEventMass_finiteProduct_le_sum_boundedExcess

#check FormalSLT.Rademacher.Localized.localizedUpperDeviationBadEventMass_finiteProduct_le_delta_boundedExcess
#print axioms FormalSLT.Rademacher.Localized.localizedUpperDeviationBadEventMass_finiteProduct_le_delta_boundedExcess

#check FormalSLT.Rademacher.Localized.localizedUpperDeviationBadEventMass_le_delta
#print axioms FormalSLT.Rademacher.Localized.localizedUpperDeviationBadEventMass_le_delta

#check FormalSLT.Rademacher.Localized.localizedSampleDependentUpperDeviationBadEventMass_le_fixed
#print axioms FormalSLT.Rademacher.Localized.localizedSampleDependentUpperDeviationBadEventMass_le_fixed

#check FormalSLT.Rademacher.Localized.localizedFastRateUpperDeviationBadEventMass
#print axioms FormalSLT.Rademacher.Localized.localizedFastRateUpperDeviationBadEventMass

#check FormalSLT.Rademacher.Localized.localizedFastRateUpperDeviationBadEventMass_le_fixed_epsilon
#print axioms FormalSLT.Rademacher.Localized.localizedFastRateUpperDeviationBadEventMass_le_fixed_epsilon

#check FormalSLT.Rademacher.Localized.localizedFastRateUpperDeviationBadEventMass_finiteProduct_le_delta_boundedExcess
#print axioms FormalSLT.Rademacher.Localized.localizedFastRateUpperDeviationBadEventMass_finiteProduct_le_delta_boundedExcess

#check FormalSLT.Rademacher.Localized.localizedFastRateHighConfidence_bernstein_fixedPoint_boundedExcess
#print axioms FormalSLT.Rademacher.Localized.localizedFastRateHighConfidence_bernstein_fixedPoint_boundedExcess

#check FormalSLT.Rademacher.Localized.localizedPointwiseSampleDependentUpperDeviationBadEventMass
#print axioms FormalSLT.Rademacher.Localized.localizedPointwiseSampleDependentUpperDeviationBadEventMass

#check FormalSLT.Rademacher.Localized.localizedPointwiseSampleDependentUpperDeviationShiftedExpMoment
#print axioms FormalSLT.Rademacher.Localized.localizedPointwiseSampleDependentUpperDeviationShiftedExpMoment

#check FormalSLT.Rademacher.Localized.localizedPointwiseSampleDependentUpperDeviationBadEventMass_le_shiftedExpMoment
#print axioms FormalSLT.Rademacher.Localized.localizedPointwiseSampleDependentUpperDeviationBadEventMass_le_shiftedExpMoment

#check FormalSLT.Rademacher.Localized.localizedPointwiseSampleDependentUpperDeviationShiftedExpMoment_le_fixedExpMoment_div
#print axioms FormalSLT.Rademacher.Localized.localizedPointwiseSampleDependentUpperDeviationShiftedExpMoment_le_fixedExpMoment_div

#check FormalSLT.Rademacher.Localized.localizedPointwiseSampleDependentUpperDeviationShiftedExpMoment_add_const
#print axioms FormalSLT.Rademacher.Localized.localizedPointwiseSampleDependentUpperDeviationShiftedExpMoment_add_const

#check FormalSLT.Rademacher.Localized.localizedSampleDependentUpperDeviationBadEventMass_le_sum_pointwise
#print axioms FormalSLT.Rademacher.Localized.localizedSampleDependentUpperDeviationBadEventMass_le_sum_pointwise

#check FormalSLT.Rademacher.Localized.localizedSampleDependentUpperDeviationBadEventMass_le_sum_tails
#print axioms FormalSLT.Rademacher.Localized.localizedSampleDependentUpperDeviationBadEventMass_le_sum_tails

#check FormalSLT.Rademacher.Localized.localizedSampleDependentUpperDeviationBadEventMass_le_sum_shiftedExpMoment
#print axioms FormalSLT.Rademacher.Localized.localizedSampleDependentUpperDeviationBadEventMass_le_sum_shiftedExpMoment

#check FormalSLT.Rademacher.Localized.localizedFastRateUpperDeviationBadEventMass_le_sum_shiftedExpMoment
#print axioms FormalSLT.Rademacher.Localized.localizedFastRateUpperDeviationBadEventMass_le_sum_shiftedExpMoment

#check FormalSLT.Rademacher.Localized.localizedFastRatePointwiseShiftedExpMoment_finiteProduct_le_boundedExcess
#print axioms FormalSLT.Rademacher.Localized.localizedFastRatePointwiseShiftedExpMoment_finiteProduct_le_boundedExcess

#check FormalSLT.Rademacher.Localized.localizedFastRatePointwiseShiftedExpMoment_le_centered_div
#print axioms FormalSLT.Rademacher.Localized.localizedFastRatePointwiseShiftedExpMoment_le_centered_div

#check FormalSLT.Rademacher.Localized.localizedFastRateUpperDeviationBadEventMass_le_sum_centeredShiftedExpMoment_div
#print axioms FormalSLT.Rademacher.Localized.localizedFastRateUpperDeviationBadEventMass_le_sum_centeredShiftedExpMoment_div

#check FormalSLT.Rademacher.Localized.localizedFastRateHighConfidence_bernstein_fixedPoint_of_centeredShiftedExpMoment
#print axioms FormalSLT.Rademacher.Localized.localizedFastRateHighConfidence_bernstein_fixedPoint_of_centeredShiftedExpMoment

#check FormalSLT.Rademacher.Localized.localizedFastRateHighConfidence_bernstein_fixedPoint_of_shiftedExpMoment
#print axioms FormalSLT.Rademacher.Localized.localizedFastRateHighConfidence_bernstein_fixedPoint_of_shiftedExpMoment

#check FormalSLT.Rademacher.Localized.localizedDeviationCertificate_mono
#print axioms FormalSLT.Rademacher.Localized.localizedDeviationCertificate_mono

#check FormalSLT.Rademacher.Localized.localizedDeviationCertificate_of_upperDeviation_le
#print axioms FormalSLT.Rademacher.Localized.localizedDeviationCertificate_of_upperDeviation_le

#check FormalSLT.Rademacher.Localized.localizedDeviationCertificate_of_mem_upperDeviationEvent
#print axioms FormalSLT.Rademacher.Localized.localizedDeviationCertificate_of_mem_upperDeviationEvent

#check FormalSLT.Rademacher.Localized.finiteExcessRisk_le_of_localizedDeviation_empirical_nonpos
#print axioms FormalSLT.Rademacher.Localized.finiteExcessRisk_le_of_localizedDeviation_empirical_nonpos

#check FormalSLT.Rademacher.Localized.finiteExcessRisk_le_of_localizedUpperDeviationEvent_empirical_nonpos
#print axioms FormalSLT.Rademacher.Localized.finiteExcessRisk_le_of_localizedUpperDeviationEvent_empirical_nonpos

#check FormalSLT.Rademacher.Localized.localizedFiniteClassHighConfidence_empirical_nonpos_boundedExcess
#print axioms FormalSLT.Rademacher.Localized.localizedFiniteClassHighConfidence_empirical_nonpos_boundedExcess

#check FormalSLT.Rademacher.Localized.finiteExcessRisk_le_of_localizedSampleDependentUpperDeviationEvent_empirical_nonpos
#print axioms FormalSLT.Rademacher.Localized.finiteExcessRisk_le_of_localizedSampleDependentUpperDeviationEvent_empirical_nonpos

#check FormalSLT.Rademacher.Localized.localizedSampleDependentHighConfidence_empirical_nonpos
#print axioms FormalSLT.Rademacher.Localized.localizedSampleDependentHighConfidence_empirical_nonpos

#check FormalSLT.Rademacher.Localized.localizedSampleDependentHighConfidence_empirical_nonpos_of_shiftedExpMoment
#print axioms FormalSLT.Rademacher.Localized.localizedSampleDependentHighConfidence_empirical_nonpos_of_shiftedExpMoment

#check FormalSLT.Rademacher.Localized.localizedFastRateUpperDeviationEvent
#print axioms FormalSLT.Rademacher.Localized.localizedFastRateUpperDeviationEvent

#check FormalSLT.Rademacher.Localized.finiteExcessRisk_le_of_localizedFastRateUpperDeviationEvent_bernstein_fixedPoint
#print axioms FormalSLT.Rademacher.Localized.finiteExcessRisk_le_of_localizedFastRateUpperDeviationEvent_bernstein_fixedPoint

#check FormalSLT.Rademacher.Localized.finiteExcessRisk_le_of_localizedDeviation_bernstein_fixedPoint
#print axioms FormalSLT.Rademacher.Localized.finiteExcessRisk_le_of_localizedDeviation_bernstein_fixedPoint

#check FormalSLT.Rademacher.Localized.finiteExcessRisk_le_of_localizedUpperDeviationEvent_bernstein_fixedPoint
#print axioms FormalSLT.Rademacher.Localized.finiteExcessRisk_le_of_localizedUpperDeviationEvent_bernstein_fixedPoint
