import FormalSLT.StochasticDynamics.EmpiricalTransitionConfidenceCountable

/-!
# Countable-tilt empirical transition-confidence checks

This checker enumerates every public theorem introduced by the countable
transition-confidence module.  The asymptotic kernel-budget theorem visibly
retains both required assumptions: positive limiting row-visit frequencies
and vanishing empirical candidate-row discrepancy.
-/

open FormalSLT.StochasticDynamics

#check countableTransitionCoordinateBoundary
#check countableTransitionCoordinateRadius
#check countableEmpiricalTransitionRowRadius
#check countableEmpiricalCandidateKernelTVBudget

#check countableTransitionCoordinateBoundary_selected_tendsto_zero
#check countableTransitionCoordinateRadius_selected_tendsto_zero_of_visitFrequency
#check countableEmpiricalTransitionRowRadius_selected_tendsto_zero_of_visitFrequency
#check countableEmpiricalCandidateKernelTVBudget_selected_tendsto_zero
#check exists_countableEmpiricalTransitionCoordinate_event
#check exists_countableEmpiricalTransitionFrequency_event
#check exists_countableEmpiricalCandidateRowTotalVariation_event
#check exists_selectedCountableEmpiricalCandidateRowTotalVariation_event
#check exists_countableEmpiricalCandidateKernelTV_event
#check exists_selectedCountableEmpiricalCandidateKernelTV_event
#check exists_countableEmpiricalTransitionGeometric_event
#check exists_selectedCountableEmpiricalCandidateKernelTVGeometric_event

#print axioms countableTransitionCoordinateBoundary_selected_tendsto_zero
#print axioms countableTransitionCoordinateRadius_selected_tendsto_zero_of_visitFrequency
#print axioms countableEmpiricalTransitionRowRadius_selected_tendsto_zero_of_visitFrequency
#print axioms countableEmpiricalCandidateKernelTVBudget_selected_tendsto_zero
#print axioms exists_countableEmpiricalTransitionCoordinate_event
#print axioms exists_countableEmpiricalTransitionFrequency_event
#print axioms exists_countableEmpiricalCandidateRowTotalVariation_event
#print axioms exists_selectedCountableEmpiricalCandidateRowTotalVariation_event
#print axioms exists_countableEmpiricalCandidateKernelTV_event
#print axioms exists_selectedCountableEmpiricalCandidateKernelTV_event
#print axioms exists_countableEmpiricalTransitionGeometric_event
#print axioms exists_selectedCountableEmpiricalCandidateKernelTVGeometric_event
