import FormalSLT.Covering.GuardedDudleyIntegral

/-!
# Guarded positive-radius Dudley integral checker

This checker records the positive-radius finite-to-integral layer that avoids
global antitonicity at zero.
-/

#check FormalSLT.Covering.GuardedDudleyIntegral.GuardedAntitoneOnDyadicAnnulus

#check FormalSLT.Covering.GuardedDudleyIntegral.guarded_dyadic_lowerEndpoint_mul_width_le_intervalIntegral
#print axioms FormalSLT.Covering.GuardedDudleyIntegral.guarded_dyadic_lowerEndpoint_mul_width_le_intervalIntegral

#check FormalSLT.Covering.GuardedDudleyIntegral.finiteDyadicEntropyAtRadiusUpperSum_le_two_mul_shifted_intervalIntegral_sum_guarded
#print axioms FormalSLT.Covering.GuardedDudleyIntegral.finiteDyadicEntropyAtRadiusUpperSum_le_two_mul_shifted_intervalIntegral_sum_guarded

#check FormalSLT.Covering.GuardedDudleyIntegral.finiteDyadicEntropyAtRadiusUpperSum_le_two_mul_truncatedIntervalIntegral_guarded
#print axioms FormalSLT.Covering.GuardedDudleyIntegral.finiteDyadicEntropyAtRadiusUpperSum_le_two_mul_truncatedIntervalIntegral_guarded

#check FormalSLT.Covering.GuardedDudleyIntegral.positiveRadiusReciprocalEntropy

#check FormalSLT.Covering.GuardedDudleyIntegral.positiveRadiusReciprocalEntropy_guarded
#print axioms FormalSLT.Covering.GuardedDudleyIntegral.positiveRadiusReciprocalEntropy_guarded

#check FormalSLT.Covering.GuardedDudleyIntegral.not_globalAntitone_positiveRadiusReciprocalEntropy
#print axioms FormalSLT.Covering.GuardedDudleyIntegral.not_globalAntitone_positiveRadiusReciprocalEntropy

#check FormalSLT.Covering.GuardedDudleyIntegral.positiveRadiusReciprocalEntropy_intervalIntegrable_dyadic
#print axioms FormalSLT.Covering.GuardedDudleyIntegral.positiveRadiusReciprocalEntropy_intervalIntegrable_dyadic

#check FormalSLT.Covering.GuardedDudleyIntegral.positiveRadiusReciprocalEntropy_truncated_bridge
#print axioms FormalSLT.Covering.GuardedDudleyIntegral.positiveRadiusReciprocalEntropy_truncated_bridge
