import FormalSLT.PACBayes.ContinuousJointMeanVarianceReversePACBayes

/-!
# Continuous reverse-epoch PAC-Bayes audit

This checker records the continuous-hypothesis load-bearing slice: prior
integration preserves the checked reverse submartingale, the endpoint moment
is derived from the fixed-hypothesis MGF by Fubini, the crossing event has mass
at most `delta`, and continuous Donsker--Varadhan yields the posterior score
bound without a finite hypothesis space.
-/

open FormalSLT.PACBayes.TimeUniformContinuous
open FormalSLT.PACBayes.FiniteJointMeanVarianceReverse
open FormalSLT.PACBayes.ContinuousJointMeanVarianceReverse

#check continuousPriorMixture_condExp_step_ge_of_fixed_hypothesis_steps
#check continuousPriorMixture_submartingale
#check reverseJointMeanVarianceEpochScore_samplePermutation
#check reverseJointMeanVarianceEpochExponentialProcess_samplePermutation
#check continuousReverseJointMeanVarianceEpochPriorMixture_stronglyAdapted
#check stronglyMeasurable_finitePopulationRisk_parameter
#check stronglyMeasurable_finiteEmpiricalRisk_parameter
#check stronglyMeasurable_finiteEmpiricalVariance_parameter
#check continuousReverseJointMeanVarianceEpochPriorMixture_submartingale_of_integrable
#check reverseJointMeanVarianceEpochExponentialProcess_integrable_prod
#check continuousReverseJointMeanVarianceEpochPriorMixture_submartingale_of_measurable_bounded
#check reverseJointMeanVarianceEpochScore_integrable_of_measurable_bounded
#check reverseJointMeanVarianceEpochExponential_integrable_of_measurable_bounded
#check continuousReverseJointMeanVarianceEpoch_endpoint_integrable
#check continuousReverseJointMeanVarianceEpochPriorMixture_submartingale
#check continuousReverseJointMeanVarianceEpochPriorMixture_endpoint_integral_le_one
#check continuousReverseJointMeanVarianceEpochPriorMixture_maximal_le_one
#check continuousReverseJointMeanVarianceEpochBadPaths_mass_le_delta
#check continuousReverseJointMeanVarianceEpochBadPaths_mass_le_delta_of_measurable_bounded
#check continuousReverseJointMeanVarianceEpoch_posteriorScore_lt_of_not_mem
#check continuousReverseJointMeanVarianceEpoch_posteriorScore_lt_of_not_mem_of_measurable_bounded
#check continuousReverseJointMeanVarianceEpoch_posteriorRisk_prefix_lt_of_not_mem_of_measurable_bounded

#print axioms continuousPriorMixture_condExp_step_ge_of_fixed_hypothesis_steps
#print axioms continuousPriorMixture_submartingale
#print axioms reverseJointMeanVarianceEpochScore_samplePermutation
#print axioms reverseJointMeanVarianceEpochExponentialProcess_samplePermutation
#print axioms continuousReverseJointMeanVarianceEpochPriorMixture_stronglyAdapted
#print axioms stronglyMeasurable_finitePopulationRisk_parameter
#print axioms stronglyMeasurable_finiteEmpiricalRisk_parameter
#print axioms stronglyMeasurable_finiteEmpiricalVariance_parameter
#print axioms continuousReverseJointMeanVarianceEpochPriorMixture_submartingale_of_integrable
#print axioms reverseJointMeanVarianceEpochExponentialProcess_integrable_prod
#print axioms continuousReverseJointMeanVarianceEpochPriorMixture_submartingale_of_measurable_bounded
#print axioms reverseJointMeanVarianceEpochScore_integrable_of_measurable_bounded
#print axioms reverseJointMeanVarianceEpochExponential_integrable_of_measurable_bounded
#print axioms continuousReverseJointMeanVarianceEpoch_endpoint_integrable
#print axioms continuousReverseJointMeanVarianceEpochPriorMixture_submartingale
#print axioms continuousReverseJointMeanVarianceEpochPriorMixture_endpoint_integral_le_one
#print axioms continuousReverseJointMeanVarianceEpochPriorMixture_maximal_le_one
#print axioms continuousReverseJointMeanVarianceEpochBadPaths_mass_le_delta
#print axioms continuousReverseJointMeanVarianceEpochBadPaths_mass_le_delta_of_measurable_bounded
#print axioms continuousReverseJointMeanVarianceEpoch_posteriorScore_lt_of_not_mem
#print axioms continuousReverseJointMeanVarianceEpoch_posteriorScore_lt_of_not_mem_of_measurable_bounded
#print axioms continuousReverseJointMeanVarianceEpoch_posteriorRisk_prefix_lt_of_not_mem_of_measurable_bounded
