import FormalSLT.AnytimeValid.SingularFractionObservableLIL

open FormalSLT.AnytimeValid

#check singularFractionObservablePenaltyFloor
#check singularFractionObservableLogPenaltyFloor
#check singularFractionObservableRawCost
#check singularFractionObservableCost
#check singularFractionObservableScale
#check singularFractionObservableTunedLambda
#check singularFractionObservableLILBoundary

#check singularFractionObservableTunedLambda_pos
#check singularFractionObservableTunedLambda_le_exp_neg_one
#check singularFraction_tunedLambda_logWindowCost_le
#check singularFraction_tunedBoundary_le_observableLIL
#check singularFractionLowerMixture_all_fraction_mean
#check singularFractionLowerMixture_timeUniform_all_fraction_mean
#check singularFractionLowerMixture_observableLIL_boundary
#check singularFractionLowerMixture_observableLIL_mean
#check singularFractionLowerMixture_timeUniform_observableLIL
#check singularFractionLowerMixture_timeUniform_observableLIL_mean

#print axioms singularFractionObservableTunedLambda_le_exp_neg_one
#print axioms singularFraction_tunedLambda_logWindowCost_le
#print axioms singularFraction_tunedBoundary_le_observableLIL
#print axioms singularFractionLowerMixture_timeUniform_all_fraction_mean
#print axioms singularFractionLowerMixture_timeUniform_observableLIL
#print axioms singularFractionLowerMixture_timeUniform_observableLIL_mean
