import FormalSLT.StochasticDynamics.ContinuousTrajectorySleepingSuffixVarianceOracle

open FormalSLT.StochasticDynamics

#check continuousTrajectoryPosteriorSuffixPredictorQuadraticVariation
#check continuousTrajectoryPosteriorConstantTiltSuffixPredictorQuadraticPenalty_eq
#check continuousTrajectoryPosteriorSuffixPredictorQuadraticVariation_mem_Icc
#check continuousTrajectorySleepingSuffixVarianceGeometricTiltExcess
#check continuousTrajectorySleepingSuffixVarianceGeometricTiltBoundary
#check continuousTrajectorySleepingGeometricTiltSuffixBoundary_eq_suffixVariance
#check continuousTrajectorySleepingSuffixVarianceMaxIndex
#check continuousTrajectorySleepingSuffixVarianceFinitePrefixArgmin
#check continuousTrajectorySleepingSuffixVarianceFinitePrefixArgmin_mem
#check continuousTrajectorySleepingSuffixVarianceFinitePrefixArgmin_le
#check continuousTrajectorySleepingSuffixVarianceSelectedExcess
#check continuousTrajectorySleepingSuffixVarianceSelectedBoundary
#check continuousTrajectorySleepingSuffixVarianceSelectedBoundary_eq
#check continuousTrajectorySleepingSuffixVarianceSelectedBoundary_le
#check continuousTrajectorySleepingSuffixVarianceGeometricTiltExcess_le_observableRate
#check continuousTrajectorySleepingSuffixVarianceGrowingPrefixComplexity
#check continuousTrajectorySleepingSuffixVarianceLILEnvelope
#check continuousTrajectorySleepingSuffixVarianceSelectedExcess_le_LILEnvelope
#check continuousTrajectorySleepingSuffixVarianceSelectedBoundary_le_LILEnvelope
#check exists_continuousTrajectorySleepingSuffixVarianceOracle_event

#print axioms continuousTrajectoryPosteriorConstantTiltSuffixPredictorQuadraticPenalty_eq
#print axioms continuousTrajectoryPosteriorSuffixPredictorQuadraticVariation_mem_Icc
#print axioms continuousTrajectorySleepingGeometricTiltSuffixBoundary_eq_suffixVariance
#print axioms continuousTrajectorySleepingSuffixVarianceFinitePrefixArgmin_mem
#print axioms continuousTrajectorySleepingSuffixVarianceFinitePrefixArgmin_le
#print axioms continuousTrajectorySleepingSuffixVarianceSelectedBoundary_eq
#print axioms continuousTrajectorySleepingSuffixVarianceSelectedBoundary_le
#print axioms continuousTrajectorySleepingSuffixVarianceGeometricTiltExcess_le_observableRate
#print axioms continuousTrajectorySleepingSuffixVarianceSelectedExcess_le_LILEnvelope
#print axioms continuousTrajectorySleepingSuffixVarianceSelectedBoundary_le_LILEnvelope
#print axioms exists_continuousTrajectorySleepingSuffixVarianceOracle_event
