import FormalSLT.Applications.ControlledQueueSharpStructuredRetrospectiveReceipt

open FormalSLT.Applications.ControlledQueue

#check SharpStructuredRetrospectivePathSummary
#check sharpStructuredRetrospectivePathSummary_of_suffixEdgeHistogram
#check sharpStructuredRetrospectivePersistenceBesselQ
#check sharpStructuredRetrospectivePersistenceAffinePenalty
#check sharpStructuredRetrospectiveRiskUpper
#check sharpStructuredRetrospectiveRiskUpper_eq
#check sharpStructuredRetrospectiveCandidateGap
#check sharpStructuredRetrospectiveCandidateGap_eq
#check sharpStructuredRetrospectivePersistenceRadiusUpper
#check sharpStructuredRetrospectivePersistenceRadiusUpper_eq
#check sharpStructuredRetrospectivePersistenceBudgetUpper
#check sharpStructuredRetrospectivePersistenceBudgetUpper_eq
#check sharpStructuredRetrospectiveResidualUpper
#check sharpStructuredRetrospectiveResidualUpper_eq
#check sharpStructuredRetrospectivePrimaryUpper
#check sharpStructuredRetrospectivePersistenceBesselQ_eq
#check sharpStructuredRetrospectivePersistenceAffinePenalty_eq
#check sharpStructuredRetrospectiveUpper_eq_primary
#check sharpStructuredRetrospectivePrimaryUpper_lt_sixtyNineThousandths
#check sharpStructuredRetrospectiveBoundary_le
#check sharpStructuredRetrospectiveBoundary_lt_sixtyNineThousandths
#check exists_controlledQueueSharpStructuredRetrospective_event
#check sharpStructuredRetrospectiveFailureEvent
#check sharpStructuredRetrospectiveFailureEvent_mass_le

#print axioms sharpStructuredRetrospectivePathSummary_of_suffixEdgeHistogram
#print axioms sharpStructuredRetrospectiveRiskUpper_eq
#print axioms sharpStructuredRetrospectivePersistenceBesselQ_eq
#print axioms sharpStructuredRetrospectivePersistenceAffinePenalty_eq
#print axioms sharpStructuredRetrospectiveCandidateGap_eq
#print axioms sharpStructuredRetrospectivePersistenceRadiusUpper_eq
#print axioms sharpStructuredRetrospectivePersistenceBudgetUpper_eq
#print axioms sharpStructuredRetrospectiveResidualUpper_eq
#print axioms sharpStructuredRetrospectiveUpper_eq_primary
#print axioms sharpStructuredRetrospectivePrimaryUpper_lt_sixtyNineThousandths
#print axioms sharpStructuredRetrospectiveBoundary_le
#print axioms sharpStructuredRetrospectiveBoundary_lt_sixtyNineThousandths
#print axioms exists_controlledQueueSharpStructuredRetrospective_event
#print axioms sharpStructuredRetrospectiveFailureEvent_mass_le

example : knownKernelReceiptHorizon = 199999 := by
  rfl

example :
    (sharpStructuredRetrospectivePrimaryUpper : ℝ) < 69 / 1000 := by
  exact sharpStructuredRetrospectivePrimaryUpper_lt_sixtyNineThousandths
