import FormalSLT.PACBayes
import FormalSLT.VC.VCDimension
import FormalSLT.VC.VCRademacher
import FormalSLT.VC.VCSampleComplexity
import FormalSLT.VC
import FormalSLT.Sequential
import FormalSLT.StochasticDynamics

/-!
# Stable topic-import smoke test

The three supported topic umbrellas expose representative finite, continuous,
Gaussian, VC, and sequential endpoints. Compatibility aliases remain usable
without carrying duplicate proof bodies.
-/

#check FormalSLT.PACBayes.TimeUniformGaussian.timeUniformSphericalGaussianPACBayes_bound
#check FormalSLT.PACBayesKL.informationTheory_klDiv_toPMF_eq_of_support
#check FormalSLT.PACBayes.TimeUniformIID.timeUniformIIDPACBayes_allPosteriors_bound
#check FormalSLT.PACBayes.TimeUniformScore.timeUniformScorePACBayes_allPosteriors_bound
#check FormalSLT.PACBayes.TimeUniformScore.posteriorTarget_le_of_not_mem_timeUniformScorePACBayesFailure
#check FormalSLT.PACBayes.TimeUniform.pacBayesPriorTiltMixture_eProcess
#check FormalSLT.PACBayes.TimeUniform.pacBayesPriorTiltMixture_optionalContinuation
#check FormalSLT.PACBayes.TimeUniform.timeUniformPACBayes_tiltMixture_allPosteriors_bound
#check FormalSLT.PACBayes.TimeUniform.timeUniformPACBayes_tiltMixture_selected_of_not_mem
#check FormalSLT.PACBayes.TimeUniformIIDTiltMixture.timeUniformIIDPACBayes_tiltMixture_measurableExceptionalEvent_spec
#check FormalSLT.PACBayes.TimeUniformIIDTiltMixture.timeUniformIIDPACBayes_tiltMixture_selected_of_not_mem_measurableExceptionalEvent
#check FormalSLT.PACBayes.IndicatorBernsteinLowRisk.indicator_posteriorRisk_le_twoThirds_of_not_mem
#check FormalSLT.PACBayes.IndicatorBernsteinTiltCatalog.indicator_posteriorRisk_le_weightedLowRiskCatalog_selected_of_not_mem
#check FormalSLT.PACBayes.FiniteEmpiricalVariance.finiteEmpiricalVariance_unbiased_finiteProduct
#check FormalSLT.PACBayes.FiniteEmpiricalVariance.finiteEmpiricalVariance_eq_pairwise
#check FormalSLT.PACBayes.FiniteEmpiricalVarianceMGF.finiteEmpiricalVariance_lowerTailMGF_tolstikhinSeldin
#check FormalSLT.PACBayes.FiniteEmpiricalVariancePACBayes.posteriorPopulationVariance_le_empiricalVariance_of_not_mem
#check FormalSLT.PACBayes.FiniteEmpiricalVarianceTiltCatalog.posteriorPopulationVariance_le_empiricalVariance_weightedCatalog_selected_of_not_mem
#check FormalSLT.PACBayes.FiniteEmpiricalBernsteinRisk.posteriorRisk_le_empiricalRisk_add_empiricalVariance_of_not_mem
#check FormalSLT.PACBayes.FiniteEmpiricalBernsteinRiskCatalog.posteriorRisk_le_empiricalRisk_add_empiricalVariance_weightedCatalog_selected_of_not_mem
#check FormalSLT.PACBayes.FiniteExponentialTilt.finiteExponentialTiltPMF_isPMF
#check FormalSLT.PACBayes.FiniteExponentialTilt.finiteExponentialTilt_changeOfMeasure
#check FormalSLT.PACBayes.FiniteExponentialTiltProduct.finiteProductSampleWeight_mul_exp_sum_eq
#check FormalSLT.PACBayes.FiniteExponentialTiltProduct.finiteProductExponentialTilt_changeOfMeasure
#check FormalSLT.PACBayes.FiniteBoundedLossExponentialTilt.finitePopulationVariance_mul_exp_neg_le_tilted
#check FormalSLT.PACBayes.FiniteBoundedLossExponentialTilt.finiteBoundedLoss_centeredBennettNormalizer_le
#check FormalSLT.PACBayes.FiniteJointMeanVarianceMGF.finiteJointMeanVarianceMGF_le
#check FormalSLT.PACBayes.FiniteJointMeanVarianceMGF.finiteJointMeanVariance_normalizedMGF_le_one
#check FormalSLT.PACBayes.FiniteJointMeanVariancePACBayes.finiteJointMeanVariance_catalogBadSamples_mass_le_delta
#check FormalSLT.PACBayes.FiniteJointMeanVariancePACBayes.finiteJointMeanVariance_posteriorGap_le_selected_of_not_mem
#check FormalSLT.PACBayes.FiniteJointMeanVariancePACBayes.finiteJointMeanVariance_posteriorRisk_le_empiricalRisk_add_empiricalVariance_zeroResidual_selected_of_not_mem
#check FormalSLT.PACBayes.FiniteEmpiricalBernsteinSqrt.finiteEmpiricalBernsteinSqrt_badSamples_mass_le_delta
#check FormalSLT.PACBayes.FiniteEmpiricalBernsteinSqrt.finiteEmpiricalBernsteinSqrt_posteriorRisk_le_of_not_mem
#check FormalSLT.VC.SampleComplexity.vc_erm_sample_complexity
#check FormalSLT.AnytimeValid.eProcess_typeI_control
#check FormalSLT.StochasticDynamics.markovPACBayes_prequentialRisk_certificate
#check FormalSLT.StochasticDynamics.markovPACBayesTiltMixtureExceptionalEvent_mass_le_delta
#check FormalSLT.StochasticDynamics.markovPACBayes_tiltMixture_prequentialRisk_certificate

#check FormalSLT.VC.VCDimension.sauerShelahFiniteSetFamily
#check FormalSLT.VC.VCRademacher.empiricalRademacherComplexity_le_massart_effective
#check FormalSLT.VC.VCSampleComplexity.vc_erm_excessRisk_tail

#print axioms FormalSLT.PACBayes.TimeUniformGaussian.timeUniformSphericalGaussianPACBayes_bound
#print axioms FormalSLT.PACBayes.TimeUniformScore.timeUniformScorePACBayes_allPosteriors_bound
#print axioms FormalSLT.PACBayes.TimeUniformScore.posteriorTarget_le_of_not_mem_timeUniformScorePACBayesFailure
#print axioms FormalSLT.PACBayes.TimeUniform.pacBayesPriorTiltMixture_eProcess
#print axioms FormalSLT.PACBayes.TimeUniform.pacBayesPriorTiltMixture_optionalContinuation
#print axioms FormalSLT.PACBayes.TimeUniform.timeUniformPACBayes_tiltMixture_allPosteriors_bound
#print axioms FormalSLT.PACBayes.TimeUniform.timeUniformPACBayes_tiltMixture_selected_of_not_mem
#print axioms FormalSLT.PACBayes.TimeUniformIIDTiltMixture.timeUniformIIDPACBayes_tiltMixture_measurableExceptionalEvent_spec
#print axioms FormalSLT.PACBayes.TimeUniformIIDTiltMixture.timeUniformIIDPACBayes_tiltMixture_selected_of_not_mem_measurableExceptionalEvent
#print axioms FormalSLT.PACBayes.IndicatorBernsteinLowRisk.indicator_posteriorRisk_le_twoThirds_of_not_mem
#print axioms FormalSLT.PACBayes.IndicatorBernsteinTiltCatalog.indicator_posteriorRisk_le_weightedLowRiskCatalog_selected_of_not_mem
#print axioms FormalSLT.PACBayes.FiniteEmpiricalVariance.finiteEmpiricalVariance_unbiased_finiteProduct
#print axioms FormalSLT.PACBayes.FiniteEmpiricalVariance.finiteEmpiricalVariance_eq_pairwise
#print axioms FormalSLT.PACBayes.FiniteEmpiricalVarianceMGF.finiteEmpiricalVariance_lowerTailMGF_tolstikhinSeldin
#print axioms FormalSLT.PACBayes.FiniteEmpiricalVariancePACBayes.posteriorPopulationVariance_le_empiricalVariance_of_not_mem
#print axioms FormalSLT.PACBayes.FiniteEmpiricalVarianceTiltCatalog.posteriorPopulationVariance_le_empiricalVariance_weightedCatalog_selected_of_not_mem
#print axioms FormalSLT.PACBayes.FiniteEmpiricalBernsteinRisk.posteriorRisk_le_empiricalRisk_add_empiricalVariance_of_not_mem
#print axioms FormalSLT.PACBayes.FiniteEmpiricalBernsteinRiskCatalog.posteriorRisk_le_empiricalRisk_add_empiricalVariance_weightedCatalog_selected_of_not_mem
#print axioms FormalSLT.PACBayes.FiniteExponentialTilt.finiteExponentialTiltPMF_isPMF
#print axioms FormalSLT.PACBayes.FiniteExponentialTilt.finiteExponentialTilt_changeOfMeasure
#print axioms FormalSLT.PACBayes.FiniteExponentialTiltProduct.finiteProductSampleWeight_mul_exp_sum_eq
#print axioms FormalSLT.PACBayes.FiniteExponentialTiltProduct.finiteProductExponentialTilt_changeOfMeasure
#print axioms FormalSLT.PACBayes.FiniteBoundedLossExponentialTilt.finitePopulationVariance_mul_exp_neg_le_tilted
#print axioms FormalSLT.PACBayes.FiniteBoundedLossExponentialTilt.finiteBoundedLoss_centeredBennettNormalizer_le
#print axioms FormalSLT.PACBayes.FiniteJointMeanVarianceMGF.finiteJointMeanVarianceMGF_le
#print axioms FormalSLT.PACBayes.FiniteJointMeanVarianceMGF.finiteJointMeanVariance_normalizedMGF_le_one
#print axioms FormalSLT.PACBayes.FiniteJointMeanVariancePACBayes.finiteJointMeanVariance_catalogBadSamples_mass_le_delta
#print axioms FormalSLT.PACBayes.FiniteJointMeanVariancePACBayes.finiteJointMeanVariance_posteriorGap_le_selected_of_not_mem
#print axioms FormalSLT.PACBayes.FiniteJointMeanVariancePACBayes.finiteJointMeanVariance_posteriorRisk_le_empiricalRisk_add_empiricalVariance_zeroResidual_selected_of_not_mem
#print axioms FormalSLT.PACBayes.FiniteEmpiricalBernsteinSqrt.finiteEmpiricalBernsteinSqrt_badSamples_mass_le_delta
#print axioms FormalSLT.PACBayes.FiniteEmpiricalBernsteinSqrt.finiteEmpiricalBernsteinSqrt_posteriorRisk_le_of_not_mem
#print axioms FormalSLT.VC.SampleComplexity.vc_erm_sample_complexity
#print axioms FormalSLT.AnytimeValid.eProcess_typeI_control
#print axioms FormalSLT.StochasticDynamics.markovPACBayes_prequentialRisk_certificate
#print axioms FormalSLT.StochasticDynamics.markovPACBayesTiltMixtureExceptionalEvent_mass_le_delta
#print axioms FormalSLT.StochasticDynamics.markovPACBayes_tiltMixture_prequentialRisk_certificate
