import FormalSLT.PACBayes.ContinuousEmpiricalBernsteinReverseSqrt

open FormalSLT.PACBayes.ContinuousEmpiricalBernsteinReverseSqrt

#check continuousEmpiricalBernsteinReverseDyadicFailure_mass_le_delta
#print axioms continuousEmpiricalBernsteinReverseDyadicFailure_mass_le_delta

#check continuousPosterior_finiteEmpiricalVariance_mem_Icc
#print axioms continuousPosterior_finiteEmpiricalVariance_mem_Icc

#check continuousEmpiricalBernsteinReverseDyadic_posteriorRisk_prefix_lt_sqrt_of_not_mem
#print axioms continuousEmpiricalBernsteinReverseDyadic_posteriorRisk_prefix_lt_sqrt_of_not_mem

#check continuousEmpiricalBernsteinReverseSqrtFailure_mass_le_delta
#print axioms continuousEmpiricalBernsteinReverseSqrtFailure_mass_le_delta

#check continuousEmpiricalBernsteinReverseGridDepth_coverage
#print axioms continuousEmpiricalBernsteinReverseGridDepth_coverage

#check continuousEmpiricalBernsteinReverseSqrt_posteriorRisk_prefix_lt_of_not_mem
#print axioms continuousEmpiricalBernsteinReverseSqrt_posteriorRisk_prefix_lt_of_not_mem
