import FormalSLT.PACBayes
import FormalSLT.VC.VCDimension
import FormalSLT.VC.VCRademacher
import FormalSLT.VC.VCSampleComplexity
import FormalSLT.VC
import FormalSLT.Sequential
import FormalSLT.StochasticDynamics

/-!
# Stable topic-import smoke test

The three supported topic umbrellas expose representative finite, continuous,
Gaussian, VC, and sequential endpoints. Compatibility aliases remain usable
without carrying duplicate proof bodies.
-/

#check FormalSLT.PACBayes.TimeUniformGaussian.timeUniformSphericalGaussianPACBayes_bound
#check FormalSLT.PACBayes.TimeUniformIID.timeUniformIIDPACBayes_allPosteriors_bound
#check FormalSLT.PACBayes.IndicatorBernsteinLowRisk.indicator_posteriorRisk_le_twoThirds_of_not_mem
#check FormalSLT.PACBayes.IndicatorBernsteinTiltCatalog.indicator_posteriorRisk_le_weightedLowRiskCatalog_selected_of_not_mem
#check FormalSLT.PACBayes.FiniteEmpiricalVariance.finiteEmpiricalVariance_unbiased_finiteProduct
#check FormalSLT.PACBayes.FiniteEmpiricalVariance.finiteEmpiricalVariance_eq_pairwise
#check FormalSLT.PACBayes.FiniteEmpiricalVarianceMGF.finiteEmpiricalVariance_lowerTailMGF_tolstikhinSeldin
#check FormalSLT.PACBayes.FiniteEmpiricalVariancePACBayes.posteriorPopulationVariance_le_empiricalVariance_of_not_mem
#check FormalSLT.PACBayes.FiniteEmpiricalVarianceTiltCatalog.posteriorPopulationVariance_le_empiricalVariance_weightedCatalog_selected_of_not_mem
#check FormalSLT.PACBayes.FiniteEmpiricalBernsteinRisk.posteriorRisk_le_empiricalRisk_add_empiricalVariance_of_not_mem
#check FormalSLT.PACBayes.FiniteEmpiricalBernsteinRiskCatalog.posteriorRisk_le_empiricalRisk_add_empiricalVariance_weightedCatalog_selected_of_not_mem
#check FormalSLT.PACBayes.FiniteExponentialTilt.finiteExponentialTiltPMF_isPMF
#check FormalSLT.PACBayes.FiniteExponentialTilt.finiteExponentialTilt_changeOfMeasure
#check FormalSLT.PACBayes.FiniteExponentialTiltProduct.finiteProductSampleWeight_mul_exp_sum_eq
#check FormalSLT.PACBayes.FiniteExponentialTiltProduct.finiteProductExponentialTilt_changeOfMeasure
#check FormalSLT.VC.SampleComplexity.vc_erm_sample_complexity
#check FormalSLT.AnytimeValid.eProcess_typeI_control
#check FormalSLT.StochasticDynamics.markovPACBayes_prequentialRisk_certificate

#check FormalSLT.VC.VCDimension.sauerShelahFiniteSetFamily
#check FormalSLT.VC.VCRademacher.empiricalRademacherComplexity_le_massart_effective
#check FormalSLT.VC.VCSampleComplexity.vc_erm_excessRisk_tail

#print axioms FormalSLT.PACBayes.TimeUniformGaussian.timeUniformSphericalGaussianPACBayes_bound
#print axioms FormalSLT.PACBayes.IndicatorBernsteinLowRisk.indicator_posteriorRisk_le_twoThirds_of_not_mem
#print axioms FormalSLT.PACBayes.IndicatorBernsteinTiltCatalog.indicator_posteriorRisk_le_weightedLowRiskCatalog_selected_of_not_mem
#print axioms FormalSLT.PACBayes.FiniteEmpiricalVariance.finiteEmpiricalVariance_unbiased_finiteProduct
#print axioms FormalSLT.PACBayes.FiniteEmpiricalVariance.finiteEmpiricalVariance_eq_pairwise
#print axioms FormalSLT.PACBayes.FiniteEmpiricalVarianceMGF.finiteEmpiricalVariance_lowerTailMGF_tolstikhinSeldin
#print axioms FormalSLT.PACBayes.FiniteEmpiricalVariancePACBayes.posteriorPopulationVariance_le_empiricalVariance_of_not_mem
#print axioms FormalSLT.PACBayes.FiniteEmpiricalVarianceTiltCatalog.posteriorPopulationVariance_le_empiricalVariance_weightedCatalog_selected_of_not_mem
#print axioms FormalSLT.PACBayes.FiniteEmpiricalBernsteinRisk.posteriorRisk_le_empiricalRisk_add_empiricalVariance_of_not_mem
#print axioms FormalSLT.PACBayes.FiniteEmpiricalBernsteinRiskCatalog.posteriorRisk_le_empiricalRisk_add_empiricalVariance_weightedCatalog_selected_of_not_mem
#print axioms FormalSLT.PACBayes.FiniteExponentialTilt.finiteExponentialTiltPMF_isPMF
#print axioms FormalSLT.PACBayes.FiniteExponentialTilt.finiteExponentialTilt_changeOfMeasure
#print axioms FormalSLT.PACBayes.FiniteExponentialTiltProduct.finiteProductSampleWeight_mul_exp_sum_eq
#print axioms FormalSLT.PACBayes.FiniteExponentialTiltProduct.finiteProductExponentialTilt_changeOfMeasure
#print axioms FormalSLT.VC.SampleComplexity.vc_erm_sample_complexity
#print axioms FormalSLT.AnytimeValid.eProcess_typeI_control
#print axioms FormalSLT.StochasticDynamics.markovPACBayes_prequentialRisk_certificate
