import FormalSLT.PACBayes.GaussianMeasureKL

/-!
# Gaussian measure-theoretic KL bridge audit

Checks the completed absolute-continuity and normalization slices preceding the
Gaussian `klDiv` identity. The remaining log-likelihood-ratio formula,
integrability proof, and closed-form KL identification are not claimed here.
-/

open FormalSLT.PACBayes

#check @gaussianCoordinateDensity_pos
#check @diagonalGaussianDensity_pos
#check @measurable_diagonalGaussianDensity
#check @measurable_diagonalGaussianENNRealDensity
#check @volume_absolutelyContinuous_diagonalGaussianMeasure
#check @diagonalGaussianMeasure_mutuallyAbsolutelyContinuous_volume
#check @volume_absolutelyContinuous_sphericalGaussianMeasure
#check @sphericalGaussianMeasure_mutuallyAbsolutelyContinuous_volume
#check @diagonalGaussianMeasure_mutuallyAbsolutelyContinuous
#check @sphericalGaussianMeasure_mutuallyAbsolutelyContinuous
#check @sphericalGaussianMeasure_absolutelyContinuous
#check @gaussianCoordinateDensity_eq_gaussianPDFReal
#check @integrable_gaussianCoordinateDensity
#check @integral_gaussianCoordinateDensity_eq_one
#check @integral_diagonalGaussianDensity_eq_one
#check @diagonalGaussianMeasure_apply_univ
#check @instIsProbabilityMeasureDiagonalGaussianMeasure
#check @sphericalGaussianMeasure_apply_univ
#check @instIsProbabilityMeasureSphericalGaussianMeasure

#print axioms gaussianCoordinateDensity_pos
#print axioms diagonalGaussianDensity_pos
#print axioms measurable_diagonalGaussianDensity
#print axioms measurable_diagonalGaussianENNRealDensity
#print axioms volume_absolutelyContinuous_diagonalGaussianMeasure
#print axioms diagonalGaussianMeasure_mutuallyAbsolutelyContinuous_volume
#print axioms volume_absolutelyContinuous_sphericalGaussianMeasure
#print axioms sphericalGaussianMeasure_mutuallyAbsolutelyContinuous_volume
#print axioms diagonalGaussianMeasure_mutuallyAbsolutelyContinuous
#print axioms sphericalGaussianMeasure_mutuallyAbsolutelyContinuous
#print axioms sphericalGaussianMeasure_absolutelyContinuous
#print axioms gaussianCoordinateDensity_eq_gaussianPDFReal
#print axioms integrable_gaussianCoordinateDensity
#print axioms integral_gaussianCoordinateDensity_eq_one
#print axioms integral_diagonalGaussianDensity_eq_one
#print axioms diagonalGaussianMeasure_apply_univ
#print axioms sphericalGaussianMeasure_apply_univ
