import FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering

#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalChainingPairCountEnvelope
#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalChainingPairCountEnvelopeENat
#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalPairCountEntropyAtRadius

#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalChainingPairCountEnvelope_dyadic
#print axioms FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalChainingPairCountEnvelope_dyadic

#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalChainingPairCountEnvelopeENat_ne_top
#print axioms FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalChainingPairCountEnvelopeENat_ne_top

#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalChainingPairCountEnvelopeENat_toReal
#print axioms FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalChainingPairCountEnvelopeENat_toReal

#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalPairCountEntropyAtRadius_nonneg
#print axioms FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalPairCountEntropyAtRadius_nonneg

#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalPairCountEntropyAtRadius_intervalIntegrable_zero_half
#print axioms FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalPairCountEntropyAtRadius_intervalIntegrable_zero_half

#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalPairCountEntropyAtRadius_guarded
#print axioms FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalPairCountEntropyAtRadius_guarded

#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalPairCountEntropy_eq_pair_count_sample
#print axioms FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalPairCountEntropy_eq_pair_count_sample

#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitInterval_pairCountEntropy_nonconstant
#print axioms FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitInterval_pairCountEntropy_nonconstant

#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitInterval_pairCountEntropy_integral_positive
#print axioms FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitInterval_pairCountEntropy_integral_positive

#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.continuous_dudley_oneStep_entropy_integral_iSup_unitInterval_pairCountEnvelope
#print axioms FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.continuous_dudley_oneStep_entropy_integral_iSup_unitInterval_pairCountEnvelope

example :
    FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalPairCountEntropyAtRadius
        ((1 : ℝ) / 2) ≠
      FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalPairCountEntropyAtRadius
        ((1 : ℝ) / 8) :=
  FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitInterval_pairCountEntropy_nonconstant
