import FormalSLT.StochasticDynamics.ContinuousMeasurableTrajectorySleepingPredictableTiltOrdinaryRisk

open FormalSLT.StochasticDynamics

#check StronglyMeasurableTrajectoryPredictableTiltCatalog
#check observedTrajectoryPredictableTilt_stronglyAdapted_of_stronglyMeasurable
#check stronglyMeasurable_continuousMeasurableTrajectorySleepingPredictableTiltMaster_filtered
#check stronglyMeasurable_continuousMeasurableTrajectorySleepingPredictableTiltMaster_ambient
#check continuousMeasurableTrajectorySleepingPredictableTiltMaster_le
#check exists_continuousMeasurableTrajectorySleepingPredictableTiltPACBayes_normalized_event
#check exists_continuousMeasurableTrajectorySleepingPredictableTiltPACBayes_ordinarySuffixRisk_event

-- This specialization witnesses that the endpoint needs neither a finite nor
-- a countable state-space instance.
#check exists_continuousMeasurableTrajectorySleepingPredictableTiltPACBayes_ordinarySuffixRisk_event
  (Theta := Real) (Z := Real)

#print axioms observedTrajectoryPredictableTilt_stronglyAdapted_of_stronglyMeasurable
#print axioms stronglyMeasurable_continuousMeasurableTrajectorySleepingPredictableTiltMaster_filtered
#print axioms stronglyMeasurable_continuousMeasurableTrajectorySleepingPredictableTiltMaster_ambient
#print axioms continuousMeasurableTrajectorySleepingPredictableTiltMaster_le
#print axioms exists_continuousMeasurableTrajectorySleepingPredictableTiltPACBayes_normalized_event
#print axioms exists_continuousMeasurableTrajectorySleepingPredictableTiltPACBayes_ordinarySuffixRisk_event
