import FormalSLT.PACBayes.ContinuousSleepingBettingPACBayes

/-!
# Executable sleeping-master continuous PAC-Bayes checks

The capstone mixes exact finite-prefix countable betting masters over an
arbitrary measurable hypothesis space. One common event supports every
positive reporting time and every eligible path-selected posterior. The
complemented-loss corollary gives an observable upper bound for a
posterior-average constant conditional-risk parameter.
-/

open FormalSLT.PACBayes.ContinuousSleepingBettingPACBayes

#check continuousSleepingBettingMasterProcess
#check continuousSleepingBettingPACBayesExceptionalEvent
#check continuousSleepingBettingMasterProcess_eProcess
#check continuousSleepingBettingMasterProcess_pos
#check forwardEmpiricalBernsteinBettingScore
#check forwardEmpiricalBernsteinScore_le_log_one_add
#check forwardEmpiricalBernsteinBettingScore_le_log_algebraicBettingWealth
#check forwardEmpiricalBernsteinBettingScore_le_log_countableSleepingMaster_sub_logWeight
#check forwardEmpiricalBernsteinBettingScore_le_log_continuousSleepingBettingMaster_sub_logWeight
#check continuousSleepingBettingPACBayesExceptionalEvent_mass_le_delta
#check continuousSleepingBettingPACBayes_allPosteriors_of_not_mem
#check continuousSleepingBettingPACBayes_selectedAtomScore_of_not_mem
#check sleepingStrategyExposure
#check forwardEmpiricalBernsteinBettingScore_oneSub_eq
#check integral_forwardEmpiricalBernsteinBettingScore_oneSub
#check continuousSleepingBettingPACBayesOrdinaryRiskBoundary
#check continuousSleepingBettingPACBayes_ordinaryRisk_allPosteriors_of_not_mem
#check continuousSleepingBettingPACBayesObservableOrdinaryRiskBoundary
#check sleepingStrategyEmpiricalBernsteinPenaltyAt_le_sumPsi
#check continuousSleepingPosteriorEmpiricalBernsteinPenalty_le_sumPsi
#check continuousSleepingBettingPACBayes_observableOrdinaryRisk_allPosteriors_of_not_mem
#check exists_continuousSleepingBettingPACBayes_event
#check exists_continuousSleepingBettingPACBayes_observableOrdinaryRisk_event

#check (exists_continuousSleepingBettingPACBayes_event (Theta := Real))
#check (exists_continuousSleepingBettingPACBayes_observableOrdinaryRisk_event
  (Theta := Real))

#print axioms forwardEmpiricalBernsteinScore_le_log_one_add
#print axioms forwardEmpiricalBernsteinBettingScore_le_log_countableSleepingMaster_sub_logWeight
#print axioms continuousSleepingBettingMasterProcess_eProcess
#print axioms continuousSleepingBettingMasterProcess_pos
#print axioms continuousSleepingBettingPACBayesExceptionalEvent_mass_le_delta
#print axioms continuousSleepingBettingPACBayes_allPosteriors_of_not_mem
#print axioms continuousSleepingBettingPACBayes_selectedAtomScore_of_not_mem
#print axioms forwardEmpiricalBernsteinBettingScore_oneSub_eq
#print axioms integral_forwardEmpiricalBernsteinBettingScore_oneSub
#print axioms continuousSleepingBettingPACBayes_ordinaryRisk_allPosteriors_of_not_mem
#print axioms sleepingStrategyEmpiricalBernsteinPenaltyAt_le_sumPsi
#print axioms continuousSleepingPosteriorEmpiricalBernsteinPenalty_le_sumPsi
#print axioms continuousSleepingBettingPACBayes_observableOrdinaryRisk_allPosteriors_of_not_mem
#print axioms exists_continuousSleepingBettingPACBayes_event
#print axioms exists_continuousSleepingBettingPACBayes_observableOrdinaryRisk_event
