import FormalSLT.PACBayes.ForwardBesselPACBayesCountable

open FormalSLT.AnytimeValid
open FormalSLT.PACBayes.ForwardBesselPACBayesCountable

/-! Every public theorem introduced by the countable-process and countable
forward-Bessel modules receives both a statement and axiom receipt here. -/

#check countableWeightedProcess_nonneg
#check countableWeightedProcess_zero
#check countableWeightedProcess_eProcess

#check countableForwardBesselPACBayesTiltComponent_eProcess_of_bounded
#check countableForwardBesselPACBayesTiltComponent_le_bound
#check countableForwardBesselPACBayesMasterProcess_pointwise_summable
#check countableForwardBesselPACBayesComponentBound_nonneg
#check countableForwardBesselPACBayesMasterProcess_nonneg
#check countableForwardBesselPACBayesMasterProcess_le_bound
#check countableForwardBesselPACBayesMasterProcess_stronglyAdapted
#check countableForwardBesselPACBayesMasterProcess_integrable
#check countableForwardBesselPACBayesMasterProcess_integralNorm_summable
#check countableForwardBesselPACBayesMasterProcess_eProcess_of_bounded
#check countableForwardBesselPACBayesExceptionalEvent_mass_le_delta
#check countableForwardBesselPACBayes_boundaryFailure_mem_exceptionalEvent
#check countableForwardBesselPACBayes_allPosteriors_of_not_mem
#check countableForwardBesselPACBayes_selected_of_not_mem
#check exists_countableForwardBesselPACBayes_event

#check polynomialForwardTiltWeight_pos
#check polynomialForwardTiltWeight_hasSum
#check geometricForwardTilt_pos
#check geometricForwardTilt_le_half
#check geometricForwardTilt_lt_one
#check geometricForwardTiltTime_mul_tilt
#check polynomialForwardTiltWeight_log_cost
#check exists_geometricForwardBesselPACBayes_event

#check forwardHybridBesselPenalty_le_card
#check forwardHybridBesselPenalty_nonneg_of_unit
#check forwardPosteriorHybridBesselPenalty_mem_Icc
#check forwardEmpiricalBernsteinPsi_le_two_mul_sq
#check polynomialForwardTilt_log_cost_div_geometric_tendsto_zero
#check geometricPolynomialForwardRate_tendsto_zero
#check countableForwardBesselPACBayesBoundary_le_geometricRate
#check countableForwardBesselPACBayesBoundary_tendsto_zero

#check geometricForwardTiltIndex_add_one
#check geometricForwardTiltIndex_floor
#check geometricForwardTiltIndex_tendsto_atTop
#check finitePMF_apply_le_one
#check finitePriorLogBarrier_nonneg
#check klDiv_term_le_neg_log_prior
#check klDiv_le_finitePriorLogBarrier
#check klDiv_div_geometricForwardTiltIndex_tendsto_zero
#check allTimeGeometricPolynomialForwardRate_tendsto_zero
#check countableForwardBesselPACBayesBoundary_nonneg
#check countableForwardBesselPACBayesBoundary_selected_le_allTimeRate
#check countableForwardBesselPACBayesBoundary_selected_tendsto_zero
#check exists_geometricForwardBesselPACBayes_allTime_vanishing_event

#print axioms countableWeightedProcess_nonneg
#print axioms countableWeightedProcess_zero
#print axioms countableWeightedProcess_eProcess

#print axioms countableForwardBesselPACBayesTiltComponent_eProcess_of_bounded
#print axioms countableForwardBesselPACBayesTiltComponent_le_bound
#print axioms countableForwardBesselPACBayesMasterProcess_pointwise_summable
#print axioms countableForwardBesselPACBayesComponentBound_nonneg
#print axioms countableForwardBesselPACBayesMasterProcess_nonneg
#print axioms countableForwardBesselPACBayesMasterProcess_le_bound
#print axioms countableForwardBesselPACBayesMasterProcess_stronglyAdapted
#print axioms countableForwardBesselPACBayesMasterProcess_integrable
#print axioms countableForwardBesselPACBayesMasterProcess_integralNorm_summable
#print axioms countableForwardBesselPACBayesMasterProcess_eProcess_of_bounded
#print axioms countableForwardBesselPACBayesExceptionalEvent_mass_le_delta
#print axioms countableForwardBesselPACBayes_boundaryFailure_mem_exceptionalEvent
#print axioms countableForwardBesselPACBayes_allPosteriors_of_not_mem
#print axioms countableForwardBesselPACBayes_selected_of_not_mem
#print axioms exists_countableForwardBesselPACBayes_event

#print axioms polynomialForwardTiltWeight_pos
#print axioms polynomialForwardTiltWeight_hasSum
#print axioms geometricForwardTilt_pos
#print axioms geometricForwardTilt_le_half
#print axioms geometricForwardTilt_lt_one
#print axioms geometricForwardTiltTime_mul_tilt
#print axioms polynomialForwardTiltWeight_log_cost
#print axioms exists_geometricForwardBesselPACBayes_event

#print axioms forwardHybridBesselPenalty_le_card
#print axioms forwardHybridBesselPenalty_nonneg_of_unit
#print axioms forwardPosteriorHybridBesselPenalty_mem_Icc
#print axioms forwardEmpiricalBernsteinPsi_le_two_mul_sq
#print axioms polynomialForwardTilt_log_cost_div_geometric_tendsto_zero
#print axioms geometricPolynomialForwardRate_tendsto_zero
#print axioms countableForwardBesselPACBayesBoundary_le_geometricRate
#print axioms countableForwardBesselPACBayesBoundary_tendsto_zero

#print axioms geometricForwardTiltIndex_add_one
#print axioms geometricForwardTiltIndex_floor
#print axioms geometricForwardTiltIndex_tendsto_atTop
#print axioms finitePMF_apply_le_one
#print axioms finitePriorLogBarrier_nonneg
#print axioms klDiv_term_le_neg_log_prior
#print axioms klDiv_le_finitePriorLogBarrier
#print axioms klDiv_div_geometricForwardTiltIndex_tendsto_zero
#print axioms allTimeGeometricPolynomialForwardRate_tendsto_zero
#print axioms countableForwardBesselPACBayesBoundary_nonneg
#print axioms countableForwardBesselPACBayesBoundary_selected_le_allTimeRate
#print axioms countableForwardBesselPACBayesBoundary_selected_tendsto_zero
#print axioms exists_geometricForwardBesselPACBayes_allTime_vanishing_event
