import FormalSLT.PACBayes
import FormalSLT.VC.VCDimension
import FormalSLT.VC.VCRademacher
import FormalSLT.VC.VCSampleComplexity
import FormalSLT.VC
import FormalSLT.Sequential
import FormalSLT.StochasticDynamics

/-!
# Stable topic-import smoke test

The three supported topic umbrellas expose representative finite, continuous,
Gaussian, VC, sequential, and forward-Bessel endpoints.  The forward master
is an actual predictable-residual e-process; its hybrid-Bessel term is only a
lower envelope.  Its finite-hypothesis, finite-declared-tilt and IID wrappers
control every eligible time `n >= 2` through one outer-mass event.
Compatibility aliases remain usable without carrying duplicate proof bodies.
-/

#check FormalSLT.PACBayes.TimeUniformGaussian.timeUniformSphericalGaussianPACBayes_bound
#check FormalSLT.PACBayesKL.informationTheory_klDiv_toPMF_eq_of_support
#check FormalSLT.PACBayes.TimeUniformIID.timeUniformIIDPACBayes_allPosteriors_bound
#check FormalSLT.PACBayes.TimeUniformScore.timeUniformScorePACBayes_allPosteriors_bound
#check FormalSLT.PACBayes.TimeUniformScore.posteriorTarget_le_of_not_mem_timeUniformScorePACBayesFailure
#check FormalSLT.PACBayes.TimeUniform.pacBayesPriorTiltMixture_eProcess
#check FormalSLT.PACBayes.TimeUniform.pacBayesPriorTiltMixture_optionalContinuation
#check FormalSLT.PACBayes.TimeUniform.timeUniformPACBayes_tiltMixture_allPosteriors_bound
#check FormalSLT.PACBayes.TimeUniform.timeUniformPACBayes_tiltMixture_selected_of_not_mem
#check FormalSLT.PACBayes.TimeUniformIIDTiltMixture.timeUniformIIDPACBayes_tiltMixture_measurableExceptionalEvent_spec
#check FormalSLT.PACBayes.TimeUniformIIDTiltMixture.timeUniformIIDPACBayes_tiltMixture_selected_of_not_mem_measurableExceptionalEvent
#check FormalSLT.PACBayes.IndicatorBernsteinLowRisk.indicator_posteriorRisk_le_twoThirds_of_not_mem
#check FormalSLT.PACBayes.IndicatorBernsteinTiltCatalog.indicator_posteriorRisk_le_weightedLowRiskCatalog_selected_of_not_mem
#check FormalSLT.PACBayes.FiniteEmpiricalVariance.finiteEmpiricalVariance_unbiased_finiteProduct
#check FormalSLT.PACBayes.FiniteEmpiricalVariance.finiteEmpiricalVariance_eq_pairwise
#check FormalSLT.PACBayes.FiniteEmpiricalVarianceMGF.finiteEmpiricalVariance_lowerTailMGF_tolstikhinSeldin
#check FormalSLT.PACBayes.FiniteEmpiricalVariancePACBayes.posteriorPopulationVariance_le_empiricalVariance_of_not_mem
#check FormalSLT.PACBayes.FiniteEmpiricalVarianceTiltCatalog.posteriorPopulationVariance_le_empiricalVariance_weightedCatalog_selected_of_not_mem
#check FormalSLT.PACBayes.FiniteEmpiricalBernsteinRisk.posteriorRisk_le_empiricalRisk_add_empiricalVariance_of_not_mem
#check FormalSLT.PACBayes.FiniteEmpiricalBernsteinRiskCatalog.posteriorRisk_le_empiricalRisk_add_empiricalVariance_weightedCatalog_selected_of_not_mem
#check FormalSLT.PACBayes.FiniteExponentialTilt.finiteExponentialTiltPMF_isPMF
#check FormalSLT.PACBayes.FiniteExponentialTilt.finiteExponentialTilt_changeOfMeasure
#check FormalSLT.PACBayes.FiniteExponentialTiltProduct.finiteProductSampleWeight_mul_exp_sum_eq
#check FormalSLT.PACBayes.FiniteExponentialTiltProduct.finiteProductExponentialTilt_changeOfMeasure
#check FormalSLT.PACBayes.FiniteBoundedLossExponentialTilt.finitePopulationVariance_mul_exp_neg_le_tilted
#check FormalSLT.PACBayes.FiniteBoundedLossExponentialTilt.finiteBoundedLoss_centeredBennettNormalizer_le
#check FormalSLT.PACBayes.FiniteJointMeanVarianceMGF.finiteJointMeanVarianceMGF_le
#check FormalSLT.PACBayes.FiniteJointMeanVarianceMGF.finiteJointMeanVariance_normalizedMGF_le_one
#check FormalSLT.PACBayes.FiniteJointMeanVariancePACBayes.finiteJointMeanVariance_catalogBadSamples_mass_le_delta
#check FormalSLT.PACBayes.FiniteJointMeanVariancePACBayes.finiteJointMeanVariance_posteriorGap_le_selected_of_not_mem
#check FormalSLT.PACBayes.FiniteJointMeanVariancePACBayes.finiteJointMeanVariance_posteriorRisk_le_empiricalRisk_add_empiricalVariance_zeroResidual_selected_of_not_mem
#check FormalSLT.PACBayes.FiniteEmpiricalVarianceReverse.reverseBesselEpoch_posteriorVariance_prefix_lt_of_not_mem
#check FormalSLT.PACBayes.FiniteJointMeanVarianceReverse.exists_reverseJointMeanVarianceEpoch_event
#check FormalSLT.PACBayes.FiniteJointMeanVarianceReverse.reverseJointMeanVarianceEpochCatalog_posteriorRisk_prefix_lt_selected_of_not_mem
#check FormalSLT.PACBayes.FiniteEmpiricalBernsteinSqrt.finiteEmpiricalBernsteinSqrt_badSamples_mass_le_delta
#check FormalSLT.PACBayes.FiniteEmpiricalBernsteinSqrt.finiteEmpiricalBernsteinSqrt_posteriorRisk_le_of_not_mem
#check FormalSLT.PACBayes.FiniteEmpiricalBernsteinReverseSqrt.exists_finiteEmpiricalBernsteinReverseSqrt_event
#check FormalSLT.PACBayes.InfiniteEmpiricalBernsteinStitch.infiniteEmpiricalBernsteinReverseSqrtFailure_mass_le_delta
#check FormalSLT.PACBayes.InfiniteEmpiricalBernsteinStitch.infiniteEmpiricalBernstein_posteriorRisk_lt_n_of_not_mem
#check FormalSLT.PACBayes.InfiniteEmpiricalBernsteinStitch.exists_infiniteEmpiricalBernstein_event
#check FormalSLT.AnytimeValid.forwardPredictableQuadratic_le_hybrid_bessel
#check FormalSLT.AnytimeValid.forwardEmpiricalBernsteinProcess_eProcess_of_bounded
#check FormalSLT.AnytimeValid.forwardEmpiricalBernsteinLowerBesselEnvelope_le_lowerProcess
#check FormalSLT.AnytimeValid.exists_forwardEmpiricalBernsteinLowerTiltCatalog_selected_event
#check FormalSLT.PACBayes.ForwardBesselPACBayes.forwardBesselPACBayesMasterProcess_eProcess_of_bounded
#check FormalSLT.PACBayes.ForwardBesselPACBayes.exists_forwardBesselPACBayes_event
#check FormalSLT.PACBayes.ForwardBesselPACBayesIID.forwardIIDBesselPACBayesExceptionalEvent_mass_le_delta
#check FormalSLT.PACBayes.ForwardBesselPACBayesIID.forwardIIDBesselPACBayes_selected_of_not_mem
#check FormalSLT.PACBayes.ForwardBesselPACBayesIID.exists_forwardIIDBesselPACBayes_event
#check FormalSLT.VC.SampleComplexity.vc_erm_sample_complexity
#check FormalSLT.AnytimeValid.eProcess_typeI_control
#check FormalSLT.StochasticDynamics.observedTrajectoryScore_condExp
#check FormalSLT.StochasticDynamics.trajectoryRiskInnovation_condSecondMoment_le_one_fourth
#check FormalSLT.StochasticDynamics.markovPACBayes_prequentialRisk_certificate
#check FormalSLT.StochasticDynamics.markovPACBayesTiltMixtureExceptionalEvent_mass_le_delta
#check FormalSLT.StochasticDynamics.markovPACBayes_tiltMixture_prequentialRisk_certificate
#check FormalSLT.StochasticDynamics.trajectoryRiskShortfall_condSecondMoment_le_one_fourth
#check FormalSLT.StochasticDynamics.trajectoryPACBayesTiltMixtureExceptionalEvent_mass_le_delta
#check FormalSLT.StochasticDynamics.trajectoryPACBayes_tiltMixture_prequentialRisk_certificate
#check FormalSLT.StochasticDynamics.exists_trajectoryEmpiricalBernsteinPACBayes_event
#check FormalSLT.StochasticDynamics.exists_trajectoryEmpiricalBernsteinPACBayes_selected_event
#check FormalSLT.StochasticDynamics.conditionalTrajectoryRisk_poissonCorrectedTrajectoryScore
#check FormalSLT.StochasticDynamics.sum_poissonPotential_increment
#check FormalSLT.StochasticDynamics.trajectoryEmpiricalPrequentialRisk_poissonCorrected
#check FormalSLT.StochasticDynamics.exists_stationaryPoissonEmpiricalBernsteinPACBayes_event
#check FormalSLT.StochasticDynamics.exists_stationaryPoissonEmpiricalBernsteinPACBayes_envelope_event
#check FormalSLT.StochasticDynamics.exists_stationaryExactPoissonEmpiricalBernsteinPACBayes_event
#check FormalSLT.StochasticDynamics.exists_stationaryExactPoissonEmpiricalBernsteinPACBayes_span_event
#check FormalSLT.StochasticDynamics.finiteDepthPoisson_residual_identity
#check FormalSLT.StochasticDynamics.iteratedMarkovPotentialMean_oscillation_le
#check FormalSLT.StochasticDynamics.finiteDepthPoissonResidual_le
#check FormalSLT.StochasticDynamics.exists_stationaryFiniteDepthPoissonEmpiricalBernsteinPACBayes_closed_event
#check FormalSLT.StochasticDynamics.finiteDobrushinCoefficient_le_candidate_add_two_mul_rowTV
#check FormalSLT.StochasticDynamics.finiteDobrushinCoefficient_lt_one_of_candidate_rowTV
#check FormalSLT.StochasticDynamics.invariantPMF_unique_of_candidate_rowTV
#check FormalSLT.StochasticDynamics.stationaryMarkovRisk_eq_of_candidate_rowTV
#check FormalSLT.StochasticDynamics.exists_empiricalTransitionCoordinate_event
#check FormalSLT.StochasticDynamics.exists_empiricalTransitionFrequency_event
#check FormalSLT.StochasticDynamics.exists_empiricalCandidateRowTotalVariation_event
#check FormalSLT.StochasticDynamics.exists_selectedEmpiricalCandidateRowTotalVariation_event
#check FormalSLT.StochasticDynamics.exists_empiricalCandidateKernelTV_event
#check FormalSLT.StochasticDynamics.exists_selectedEmpiricalKernelContraction_event

#check FormalSLT.VC.VCDimension.sauerShelahFiniteSetFamily
#check FormalSLT.VC.VCRademacher.empiricalRademacherComplexity_le_massart_effective
#check FormalSLT.VC.VCSampleComplexity.vc_erm_excessRisk_tail

#print axioms FormalSLT.PACBayes.TimeUniformGaussian.timeUniformSphericalGaussianPACBayes_bound
#print axioms FormalSLT.PACBayes.TimeUniformScore.timeUniformScorePACBayes_allPosteriors_bound
#print axioms FormalSLT.PACBayes.TimeUniformScore.posteriorTarget_le_of_not_mem_timeUniformScorePACBayesFailure
#print axioms FormalSLT.PACBayes.TimeUniform.pacBayesPriorTiltMixture_eProcess
#print axioms FormalSLT.PACBayes.TimeUniform.pacBayesPriorTiltMixture_optionalContinuation
#print axioms FormalSLT.PACBayes.TimeUniform.timeUniformPACBayes_tiltMixture_allPosteriors_bound
#print axioms FormalSLT.PACBayes.TimeUniform.timeUniformPACBayes_tiltMixture_selected_of_not_mem
#print axioms FormalSLT.PACBayes.TimeUniformIIDTiltMixture.timeUniformIIDPACBayes_tiltMixture_measurableExceptionalEvent_spec
#print axioms FormalSLT.PACBayes.TimeUniformIIDTiltMixture.timeUniformIIDPACBayes_tiltMixture_selected_of_not_mem_measurableExceptionalEvent
#print axioms FormalSLT.PACBayes.IndicatorBernsteinLowRisk.indicator_posteriorRisk_le_twoThirds_of_not_mem
#print axioms FormalSLT.PACBayes.IndicatorBernsteinTiltCatalog.indicator_posteriorRisk_le_weightedLowRiskCatalog_selected_of_not_mem
#print axioms FormalSLT.PACBayes.FiniteEmpiricalVariance.finiteEmpiricalVariance_unbiased_finiteProduct
#print axioms FormalSLT.PACBayes.FiniteEmpiricalVariance.finiteEmpiricalVariance_eq_pairwise
#print axioms FormalSLT.PACBayes.FiniteEmpiricalVarianceMGF.finiteEmpiricalVariance_lowerTailMGF_tolstikhinSeldin
#print axioms FormalSLT.PACBayes.FiniteEmpiricalVariancePACBayes.posteriorPopulationVariance_le_empiricalVariance_of_not_mem
#print axioms FormalSLT.PACBayes.FiniteEmpiricalVarianceTiltCatalog.posteriorPopulationVariance_le_empiricalVariance_weightedCatalog_selected_of_not_mem
#print axioms FormalSLT.PACBayes.FiniteEmpiricalBernsteinRisk.posteriorRisk_le_empiricalRisk_add_empiricalVariance_of_not_mem
#print axioms FormalSLT.PACBayes.FiniteEmpiricalBernsteinRiskCatalog.posteriorRisk_le_empiricalRisk_add_empiricalVariance_weightedCatalog_selected_of_not_mem
#print axioms FormalSLT.PACBayes.FiniteExponentialTilt.finiteExponentialTiltPMF_isPMF
#print axioms FormalSLT.PACBayes.FiniteExponentialTilt.finiteExponentialTilt_changeOfMeasure
#print axioms FormalSLT.PACBayes.FiniteExponentialTiltProduct.finiteProductSampleWeight_mul_exp_sum_eq
#print axioms FormalSLT.PACBayes.FiniteExponentialTiltProduct.finiteProductExponentialTilt_changeOfMeasure
#print axioms FormalSLT.PACBayes.FiniteBoundedLossExponentialTilt.finitePopulationVariance_mul_exp_neg_le_tilted
#print axioms FormalSLT.PACBayes.FiniteBoundedLossExponentialTilt.finiteBoundedLoss_centeredBennettNormalizer_le
#print axioms FormalSLT.PACBayes.FiniteJointMeanVarianceMGF.finiteJointMeanVarianceMGF_le
#print axioms FormalSLT.PACBayes.FiniteJointMeanVarianceMGF.finiteJointMeanVariance_normalizedMGF_le_one
#print axioms FormalSLT.PACBayes.FiniteJointMeanVariancePACBayes.finiteJointMeanVariance_catalogBadSamples_mass_le_delta
#print axioms FormalSLT.PACBayes.FiniteJointMeanVariancePACBayes.finiteJointMeanVariance_posteriorGap_le_selected_of_not_mem
#print axioms FormalSLT.PACBayes.FiniteJointMeanVariancePACBayes.finiteJointMeanVariance_posteriorRisk_le_empiricalRisk_add_empiricalVariance_zeroResidual_selected_of_not_mem
#print axioms FormalSLT.PACBayes.FiniteEmpiricalVarianceReverse.reverseBesselEpoch_posteriorVariance_prefix_lt_of_not_mem
#print axioms FormalSLT.PACBayes.FiniteJointMeanVarianceReverse.exists_reverseJointMeanVarianceEpoch_event
#print axioms FormalSLT.PACBayes.FiniteJointMeanVarianceReverse.reverseJointMeanVarianceEpochCatalog_posteriorRisk_prefix_lt_selected_of_not_mem
#print axioms FormalSLT.PACBayes.FiniteEmpiricalBernsteinSqrt.finiteEmpiricalBernsteinSqrt_badSamples_mass_le_delta
#print axioms FormalSLT.PACBayes.FiniteEmpiricalBernsteinSqrt.finiteEmpiricalBernsteinSqrt_posteriorRisk_le_of_not_mem
#print axioms FormalSLT.PACBayes.FiniteEmpiricalBernsteinReverseSqrt.exists_finiteEmpiricalBernsteinReverseSqrt_event
#print axioms FormalSLT.PACBayes.InfiniteEmpiricalBernsteinStitch.infiniteEmpiricalBernsteinReverseSqrtFailure_mass_le_delta
#print axioms FormalSLT.PACBayes.InfiniteEmpiricalBernsteinStitch.infiniteEmpiricalBernstein_posteriorRisk_lt_n_of_not_mem
#print axioms FormalSLT.PACBayes.InfiniteEmpiricalBernsteinStitch.exists_infiniteEmpiricalBernstein_event
#print axioms FormalSLT.AnytimeValid.forwardPredictableQuadratic_le_hybrid_bessel
#print axioms FormalSLT.AnytimeValid.forwardEmpiricalBernsteinProcess_eProcess_of_bounded
#print axioms FormalSLT.AnytimeValid.forwardEmpiricalBernsteinLowerBesselEnvelope_le_lowerProcess
#print axioms FormalSLT.AnytimeValid.exists_forwardEmpiricalBernsteinLowerTiltCatalog_selected_event
#print axioms FormalSLT.PACBayes.ForwardBesselPACBayes.forwardBesselPACBayesMasterProcess_eProcess_of_bounded
#print axioms FormalSLT.PACBayes.ForwardBesselPACBayes.exists_forwardBesselPACBayes_event
#print axioms FormalSLT.PACBayes.ForwardBesselPACBayesIID.forwardIIDBesselPACBayesExceptionalEvent_mass_le_delta
#print axioms FormalSLT.PACBayes.ForwardBesselPACBayesIID.forwardIIDBesselPACBayes_selected_of_not_mem
#print axioms FormalSLT.PACBayes.ForwardBesselPACBayesIID.exists_forwardIIDBesselPACBayes_event
#print axioms FormalSLT.VC.SampleComplexity.vc_erm_sample_complexity
#print axioms FormalSLT.AnytimeValid.eProcess_typeI_control
#print axioms FormalSLT.StochasticDynamics.observedTrajectoryScore_condExp
#print axioms FormalSLT.StochasticDynamics.trajectoryRiskInnovation_condSecondMoment_le_one_fourth
#print axioms FormalSLT.StochasticDynamics.markovPACBayes_prequentialRisk_certificate
#print axioms FormalSLT.StochasticDynamics.markovPACBayesTiltMixtureExceptionalEvent_mass_le_delta
#print axioms FormalSLT.StochasticDynamics.markovPACBayes_tiltMixture_prequentialRisk_certificate
#print axioms FormalSLT.StochasticDynamics.trajectoryRiskShortfall_condSecondMoment_le_one_fourth
#print axioms FormalSLT.StochasticDynamics.trajectoryPACBayesTiltMixtureExceptionalEvent_mass_le_delta
#print axioms FormalSLT.StochasticDynamics.trajectoryPACBayes_tiltMixture_prequentialRisk_certificate
#print axioms FormalSLT.StochasticDynamics.exists_trajectoryEmpiricalBernsteinPACBayes_event
#print axioms FormalSLT.StochasticDynamics.exists_trajectoryEmpiricalBernsteinPACBayes_selected_event
#print axioms FormalSLT.StochasticDynamics.conditionalTrajectoryRisk_poissonCorrectedTrajectoryScore
#print axioms FormalSLT.StochasticDynamics.sum_poissonPotential_increment
#print axioms FormalSLT.StochasticDynamics.trajectoryEmpiricalPrequentialRisk_poissonCorrected
#print axioms FormalSLT.StochasticDynamics.exists_stationaryPoissonEmpiricalBernsteinPACBayes_event
#print axioms FormalSLT.StochasticDynamics.exists_stationaryPoissonEmpiricalBernsteinPACBayes_envelope_event
#print axioms FormalSLT.StochasticDynamics.exists_stationaryExactPoissonEmpiricalBernsteinPACBayes_event
#print axioms FormalSLT.StochasticDynamics.exists_stationaryExactPoissonEmpiricalBernsteinPACBayes_span_event
#print axioms FormalSLT.StochasticDynamics.finiteDepthPoisson_residual_identity
#print axioms FormalSLT.StochasticDynamics.iteratedMarkovPotentialMean_oscillation_le
#print axioms FormalSLT.StochasticDynamics.finiteDepthPoissonResidual_le
#print axioms FormalSLT.StochasticDynamics.exists_stationaryFiniteDepthPoissonEmpiricalBernsteinPACBayes_closed_event
#print axioms FormalSLT.StochasticDynamics.finiteDobrushinCoefficient_le_candidate_add_two_mul_rowTV
#print axioms FormalSLT.StochasticDynamics.finiteDobrushinCoefficient_lt_one_of_candidate_rowTV
#print axioms FormalSLT.StochasticDynamics.invariantPMF_unique_of_candidate_rowTV
#print axioms FormalSLT.StochasticDynamics.stationaryMarkovRisk_eq_of_candidate_rowTV
#print axioms FormalSLT.StochasticDynamics.exists_empiricalTransitionCoordinate_event
#print axioms FormalSLT.StochasticDynamics.exists_empiricalTransitionFrequency_event
#print axioms FormalSLT.StochasticDynamics.exists_empiricalCandidateRowTotalVariation_event
#print axioms FormalSLT.StochasticDynamics.exists_selectedEmpiricalCandidateRowTotalVariation_event
#print axioms FormalSLT.StochasticDynamics.exists_empiricalCandidateKernelTV_event
#print axioms FormalSLT.StochasticDynamics.exists_selectedEmpiricalKernelContraction_event
