import FormalSLT.Applications.BrierMonitorSyntheticProofOfLifeReceipt

open FormalSLT.Applications.BrierMonitorSyntheticProofOfLifeReceipt

#check declared_first_segment_predictions
#check declared_second_segment_predictions
#check declaredSelectedBrierLossQ_eq
#check declaredForwardPredictorQ_zero
#check declaredForwardPredictorQ_eq
#check declaredEmpiricalBrierRiskQ_eq
#check declaredSuffixPredictorQuadraticVariationQ_eq
#check observed_selectedBrierLoss_eq
#check selectedBrier_forwardPredictor_eq
#check selectedPosterior_kl_eq_log_two
#check selected_empiricalSuffixRisk_eq
#check selected_suffixPredictorQuadraticVariation_eq
#check tracked_empiricalRisk_matches_reconstruction
#check tracked_quadraticVariation_matches_reconstruction
#check trackedBoundaryUpper_lt_ninetyOneThousandths
#check trackedSelectionMargin_pos
#check supportedAtomBoundary_eq
#check supportedAtomBoundary_lt_trackedUpper
#check selectedBoundary_lt_trackedUpper
#check selectedBoundary_lt_ninetyOneThousandths
#check conditionalRisk_lt_ninetyOneThousandths_of_goodEventInequality

#print axioms declaredEmpiricalBrierRiskQ_eq
#print axioms declaredSuffixPredictorQuadraticVariationQ_eq
#print axioms selected_empiricalSuffixRisk_eq
#print axioms selected_suffixPredictorQuadraticVariation_eq
#print axioms trackedBoundaryUpper_lt_ninetyOneThousandths
#print axioms trackedSelectionMargin_pos
#print axioms supportedAtomBoundary_lt_trackedUpper
#print axioms selectedBoundary_lt_trackedUpper
#print axioms selectedBoundary_lt_ninetyOneThousandths
#print axioms conditionalRisk_lt_ninetyOneThousandths_of_goodEventInequality
