import FormalSLT.StochasticDynamics.ContinuousMeasurableTrajectorySleepingCountableTiltPACBayes

open FormalSLT.StochasticDynamics

#check stronglyMeasurable_continuousMeasurableTrajectorySleepingConstantTiltMaster_filtered
#check stronglyMeasurable_continuousMeasurableTrajectorySleepingConstantTiltMaster_ambient
#check continuousMeasurableTrajectorySleepingConstantTiltMaster_le
#check exists_continuousMeasurableTrajectorySleepingConstantTiltPACBayes_suffixRisk_event
#check exists_continuousMeasurableTrajectorySleepingCountableTiltPACBayes_suffixRisk_event
#check exists_continuousMeasurableTrajectorySleepingGeometricTiltPACBayes_suffixRisk_event
#check exists_continuousMeasurableTrajectorySleepingCountableTiltPACBayes_suffixRisk_event
  (Theta := Real) (Z := Real)

#print axioms stronglyMeasurable_continuousMeasurableTrajectorySleepingConstantTiltMaster_filtered
#print axioms stronglyMeasurable_continuousMeasurableTrajectorySleepingConstantTiltMaster_ambient
#print axioms continuousMeasurableTrajectorySleepingConstantTiltMaster_le
#print axioms exists_continuousMeasurableTrajectorySleepingConstantTiltPACBayes_suffixRisk_event
#print axioms exists_continuousMeasurableTrajectorySleepingCountableTiltPACBayes_suffixRisk_event
#print axioms exists_continuousMeasurableTrajectorySleepingGeometricTiltPACBayes_suffixRisk_event
