import FormalSLT.Covering.ContinuousDudleyCovering

/-!
# Covering-number full-supremum Dudley checker

This checker records the covering-number specialization whose left side is the
full pointwise supremum over the infinite index type.
-/

#check FormalSLT.Covering.ContinuousDudleyCovering.continuous_dudley_entropy_integral_iSup_of_coveringNumber
#print axioms FormalSLT.Covering.ContinuousDudleyCovering.continuous_dudley_entropy_integral_iSup_of_coveringNumber

#check FormalSLT.Covering.ContinuousDudleyCovering.continuous_dudley_entropy_integral_iSup_of_coveringNumber_uniformModulus_eventually
#print axioms FormalSLT.Covering.ContinuousDudleyCovering.continuous_dudley_entropy_integral_iSup_of_coveringNumber_uniformModulus_eventually

#check FormalSLT.Covering.TotalBoundedDudley.dyadicChaining_eventual_card_coarse_obligations
#print axioms FormalSLT.Covering.TotalBoundedDudley.dyadicChaining_eventual_card_coarse_obligations

#check @FormalSLT.Covering.TotalBoundedDudley.radiusScale_quarter_separated_or_smallDiameter
#print axioms FormalSLT.Covering.TotalBoundedDudley.radiusScale_quarter_separated_or_smallDiameter

#check @FormalSLT.Covering.FiniteSubGaussianChaining.finite_expectedSup_le_of_subGaussian_mgf_sqrt_nonempty
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.finite_expectedSup_le_of_subGaussian_mgf_sqrt_nonempty

#check @FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.projection_increment_expectedSup_le_of_radius_sqrt_nonempty
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.projection_increment_expectedSup_le_of_radius_sqrt_nonempty

#check @FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.increment_family_expectedSup_le_of_radius_sqrt_nonempty
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.increment_family_expectedSup_le_of_radius_sqrt_nonempty

#check @FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.net_increment_expectedSup_le_pair_sqrt_nonempty
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.net_increment_expectedSup_le_pair_sqrt_nonempty

#check @FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.net_increment_expectedSup_le_coveringNumber_sqrt_nonempty
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.net_increment_expectedSup_le_coveringNumber_sqrt_nonempty

#check @FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projected_chaining_expectation_bound_of_increment_families_sqrt_over_nonempty
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projected_chaining_expectation_bound_of_increment_families_sqrt_over_nonempty

#check @FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projected_chaining_expectation_bound_of_increment_families_sqrt_nonempty
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projected_chaining_expectation_bound_of_increment_families_sqrt_nonempty

#check @FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_chaining_expectation_bound_of_net_sequence_pairs_sqrt_nonempty
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_chaining_expectation_bound_of_net_sequence_pairs_sqrt_nonempty

#check @FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_chaining_expectation_bound_of_net_sequence_coveringNumbers_sqrt_nonempty
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_chaining_expectation_bound_of_net_sequence_coveringNumbers_sqrt_nonempty

#check @FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projected_chaining_expectation_bound_of_net_sequence_coveringNumbers_sqrt_nonempty
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projected_chaining_expectation_bound_of_net_sequence_coveringNumbers_sqrt_nonempty

#check @FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projectedNet_chaining_expectation_bound_of_net_sequence_coveringNumbers_sqrt_nonempty
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projectedNet_chaining_expectation_bound_of_net_sequence_coveringNumbers_sqrt_nonempty

#check @FormalSLT.Covering.FiniteSubGaussianChaining.FiniteNet.coveringNumber_pos
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteNet.coveringNumber_pos

#check @FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projectedNet_dudley_entropy_sum_coveringNumbers_geometric_integral_budget_prefix_envelope_nonempty
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projectedNet_dudley_entropy_sum_coveringNumbers_geometric_integral_budget_prefix_envelope_nonempty

#check @FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_coveringNumbers_nonempty
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_coveringNumbers_nonempty

#check @FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projectedNet_dudley_entropy_sum_coveringNumbers_geometric_entropy_integral_comparison_nonempty
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projectedNet_dudley_entropy_sum_coveringNumbers_geometric_entropy_integral_comparison_nonempty

#check @FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projectedNet_dudley_entropy_sum_coveringNumbers_geometric_entropy_intervalIntegral_comparison_nonempty
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projectedNet_dudley_entropy_sum_coveringNumbers_geometric_entropy_intervalIntegral_comparison_nonempty

#check @FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projectedNet_dudley_entropy_sum_coveringNumbers_geometric_entropy_truncatedIntervalIntegral_comparison_nonempty
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projectedNet_dudley_entropy_sum_coveringNumbers_geometric_entropy_truncatedIntervalIntegral_comparison_nonempty

#check @FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_entropy_integral_comparison_nonempty
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_entropy_integral_comparison_nonempty

#check @FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_entropy_intervalIntegral_comparison_nonempty
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_entropy_intervalIntegral_comparison_nonempty

#check @FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison_nonempty
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison_nonempty

#check @FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_supFunctional_dudley_entropy_sum_coveringNumbers_geometric_entropy_truncatedIntervalIntegral_comparison_nonempty
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_supFunctional_dudley_entropy_sum_coveringNumbers_geometric_entropy_truncatedIntervalIntegral_comparison_nonempty

#check @FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_separableSupFunctional_dudley_entropy_sum_coveringNumbers_geometric_entropy_truncatedIntervalIntegral_comparison_nonempty
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_separableSupFunctional_dudley_entropy_sum_coveringNumbers_geometric_entropy_truncatedIntervalIntegral_comparison_nonempty

#check @FormalSLT.Covering.TotalBoundedDudley.finite_supFunctional_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison_nonempty
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_supFunctional_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison_nonempty

#check @FormalSLT.Covering.TotalBoundedDudley.finite_separableSupFunctional_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison_nonempty
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_separableSupFunctional_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison_nonempty

#check @FormalSLT.Covering.TotalBoundedDudley.finite_witnessedSup_modulus_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison_nonempty
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_witnessedSup_modulus_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison_nonempty

#check FormalSLT.Covering.TotalBoundedDudley.EpsilonizedSupremumBoundaryChoiceNonempty

#check FormalSLT.Covering.TotalBoundedDudley.finite_epsilonizedSup_modulus_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison_nonempty
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_epsilonizedSup_modulus_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison_nonempty

#check FormalSLT.Covering.TotalBoundedDudley.FiniteCoverSupremumBoundaryChoiceNonempty

#check FormalSLT.Covering.TotalBoundedDudley.epsilonizedSupremumBoundaryChoiceNonempty_of_finiteCoverSupremumBoundaryChoiceNonempty
#print axioms FormalSLT.Covering.TotalBoundedDudley.epsilonizedSupremumBoundaryChoiceNonempty_of_finiteCoverSupremumBoundaryChoiceNonempty

#check FormalSLT.Covering.TotalBoundedDudley.finite_epsilonizedSup_dudley_totalBounded_of_finiteCoverSupremumBoundaryChoice_nonempty
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_epsilonizedSup_dudley_totalBounded_of_finiteCoverSupremumBoundaryChoice_nonempty

#check FormalSLT.Covering.TotalBoundedDudley.finite_epsilonizedSup_modulus_dudley_totalBounded_globalBudget_nonempty
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_epsilonizedSup_modulus_dudley_totalBounded_globalBudget_nonempty

#check FormalSLT.Covering.TotalBoundedDudley.finite_epsilonizedSup_dudley_totalBounded_globalBudget_of_finiteCoverSupremumBoundaryChoice_nonempty
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_epsilonizedSup_dudley_totalBounded_globalBudget_of_finiteCoverSupremumBoundaryChoice_nonempty

#check FormalSLT.Covering.TotalBoundedDudley.SeparableTerminalSupremumBoundaryChoiceNonempty

#check FormalSLT.Covering.TotalBoundedDudley.separableTerminalSupremumBoundaryChoiceNonempty_of_pathwiseTerminalModulus
#print axioms FormalSLT.Covering.TotalBoundedDudley.separableTerminalSupremumBoundaryChoiceNonempty_of_pathwiseTerminalModulus

#check FormalSLT.Covering.TotalBoundedDudley.separableTerminalSupremumBoundaryChoiceNonempty_of_finiteCoverSupremumBoundaryChoiceNonempty
#print axioms FormalSLT.Covering.TotalBoundedDudley.separableTerminalSupremumBoundaryChoiceNonempty_of_finiteCoverSupremumBoundaryChoiceNonempty

#check FormalSLT.Covering.TotalBoundedDudley.finite_epsilonizedSup_separableTerminal_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison_nonempty
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_epsilonizedSup_separableTerminal_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison_nonempty

#check FormalSLT.Covering.TotalBoundedDudley.finite_separableTerminal_dudley_totalBounded_globalBudget_nonempty
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_separableTerminal_dudley_totalBounded_globalBudget_nonempty

#check FormalSLT.Covering.TotalBoundedDudley.dyadicChaining_eventual_coarse_obligations
#print axioms FormalSLT.Covering.TotalBoundedDudley.dyadicChaining_eventual_coarse_obligations

#check FormalSLT.Covering.ContinuousDudley.continuous_dudley_entropy_integral_nonempty
#print axioms FormalSLT.Covering.ContinuousDudley.continuous_dudley_entropy_integral_nonempty

#check FormalSLT.Covering.ContinuousDudley.continuous_dudley_entropy_integral_iSup_of_uniformModulus_eventually_nonempty
#print axioms FormalSLT.Covering.ContinuousDudley.continuous_dudley_entropy_integral_iSup_of_uniformModulus_eventually_nonempty

#check FormalSLT.Covering.ContinuousDudleyCovering.continuous_dudley_entropy_integral_iSup_of_coveringNumber_uniformModulus_eventually_nonempty
#print axioms FormalSLT.Covering.ContinuousDudleyCovering.continuous_dudley_entropy_integral_iSup_of_coveringNumber_uniformModulus_eventually_nonempty

#check FormalSLT.Covering.ContinuousDudleyCovering.continuous_dudley_entropy_integral_iSup_of_coveringNumber_uniformModulus_concrete_nonempty
#print axioms FormalSLT.Covering.ContinuousDudleyCovering.continuous_dudley_entropy_integral_iSup_of_coveringNumber_uniformModulus_concrete_nonempty

#check FormalSLT.Covering.ContinuousDudleyCovering.continuous_dudley_entropy_integral_iSup_of_coveringNumber_uniformModulus_concrete_bdd_nonempty
#print axioms FormalSLT.Covering.ContinuousDudleyCovering.continuous_dudley_entropy_integral_iSup_of_coveringNumber_uniformModulus_concrete_bdd_nonempty

#check FormalSLT.Covering.ContinuousDudleyCovering.continuous_dudley_entropy_integral_iSup_of_coveringNumber_uniformModulus_concrete
#print axioms FormalSLT.Covering.ContinuousDudleyCovering.continuous_dudley_entropy_integral_iSup_of_coveringNumber_uniformModulus_concrete

#check FormalSLT.Covering.ContinuousDudleyCovering.continuous_dudley_entropy_integral_iSup_of_coveringNumber_uniformModulus_concrete_bdd
#print axioms FormalSLT.Covering.ContinuousDudleyCovering.continuous_dudley_entropy_integral_iSup_of_coveringNumber_uniformModulus_concrete_bdd
