import FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering

#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalCoveringNumber
#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalCoveringNumberENat
#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalCoveringEntropyAtRadius

#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalCoveringNumber_dyadic
#print axioms FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalCoveringNumber_dyadic

#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalCoveringNumberENat_ne_top
#print axioms FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalCoveringNumberENat_ne_top

#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalCoveringNumberENat_toReal
#print axioms FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalCoveringNumberENat_toReal

#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalCoveringEntropyAtRadius_nonneg
#print axioms FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalCoveringEntropyAtRadius_nonneg

#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalCoveringEntropyAtRadius_intervalIntegrable_zero_half
#print axioms FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalCoveringEntropyAtRadius_intervalIntegrable_zero_half

#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalCoveringEntropyAtRadius_guarded
#print axioms FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalCoveringEntropyAtRadius_guarded

#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalCoveringEntropy_eq_genuine_count_sample
#print axioms FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalCoveringEntropy_eq_genuine_count_sample

#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitInterval_coveringEntropy_nonconstant
#print axioms FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitInterval_coveringEntropy_nonconstant

#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitInterval_coveringEntropy_integral_positive
#print axioms FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitInterval_coveringEntropy_integral_positive

#check FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.continuous_dudley_entropy_integral_iSup_unitInterval_coveringNumber
#print axioms FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.continuous_dudley_entropy_integral_iSup_unitInterval_coveringNumber

example :
    FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalCoveringEntropyAtRadius
        ((1 : ℝ) / 2) ≠
      FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitIntervalCoveringEntropyAtRadius
        ((1 : ℝ) / 8) :=
  FormalSLT.Covering.ContinuousDudleyUnitIntervalCovering.unitInterval_coveringEntropy_nonconstant
