import FormalSLT.StochasticDynamics.ContinuousTrajectorySleepingCountableTiltPACBayesOracle

open FormalSLT.StochasticDynamics

#check continuousTrajectorySleepingSuffixGeometricTiltIndex
#check continuousTrajectorySleepingSuffixEffectiveConfidence
#check continuousTrajectorySleepingSuffixGeometricTiltExcess
#check continuousTrajectorySleepingSuffixGeometricTiltBoundary
#check continuousTrajectorySleeping_geometricTiltWake_log_cost
#check continuousTrajectoryPosteriorConstantTiltSuffixPredictorQuadraticPenalty_mem_Icc
#check continuousTrajectorySleepingSuffixGeometricTiltExcess_le_allTimeRate
#check continuousTrajectorySleepingSuffixGeometricTiltExcess_nonneg
#check exists_continuousTrajectorySleepingSuffixGeometricTiltPACBayes_event
#check continuousTrajectorySleepingSuffixGeometricTiltExcess_tendsto_zero_fixedWake

#print axioms continuousTrajectoryPosteriorConstantTiltSuffixPredictorQuadraticPenalty_mem_Icc
#print axioms continuousTrajectorySleepingSuffixGeometricTiltExcess_le_allTimeRate
#print axioms exists_continuousTrajectorySleepingSuffixGeometricTiltPACBayes_event
#print axioms continuousTrajectorySleepingSuffixGeometricTiltExcess_tendsto_zero_fixedWake
