import FormalSLT.Applications.GJPBrierMonitorReplayReceipt

open FormalSLT.Applications.GJPBrierMonitorReplayReceipt

#check uniformPrior_isFullSupportPMF
#check selectedPosterior_isPMF
#check selectedPosterior_pos
#check selectedPosterior_le_one
#check reconstructedPosteriorEmpiricalBrierRiskQ_eq
#check reconstructedPosteriorQuadraticVariationQ_eq
#check selectedPosterior_kl_lt_seven_fifths
#check tracked_empiricalBrierRisk_lt_fortyEight_thousandths
#check tracked_quadraticVariation_nonneg
#check tracked_quadraticVariation_lt_four
#check summaryInstantiatedEndpoint
#check summaryInstantiatedEndpoint_lt_oneHundredFortyEight_thousandths
#check trackedBoundaryUpper_lt_oneHundredThirtyNine_thousandths
#check summaryEndpoint_lt_constantModelMonitorEmpiricalBrier
#check summaryEndpoint_lt_trainBaseRateBrierThreshold
#check conditionalMonitoredRisk_lt_oneHundredFortyEight_thousandths

#print axioms uniformPrior_isFullSupportPMF
#print axioms selectedPosterior_isPMF
#print axioms reconstructedPosteriorEmpiricalBrierRiskQ_eq
#print axioms reconstructedPosteriorQuadraticVariationQ_eq
#print axioms selectedPosterior_kl_lt_seven_fifths
#print axioms tracked_empiricalBrierRisk_lt_fortyEight_thousandths
#print axioms tracked_quadraticVariation_lt_four
#print axioms summaryInstantiatedEndpoint_lt_oneHundredFortyEight_thousandths
#print axioms trackedBoundaryUpper_lt_oneHundredThirtyNine_thousandths
#print axioms summaryEndpoint_lt_constantModelMonitorEmpiricalBrier
#print axioms summaryEndpoint_lt_trainBaseRateBrierThreshold
#print axioms conditionalMonitoredRisk_lt_oneHundredFortyEight_thousandths
