import FormalSLT.StochasticDynamics.ContinuousTrajectoryEmpiricalBernsteinPACBayes

/-!
# Continuous-hypothesis trajectory empirical-Bernstein checks

This audit checks the arbitrary measurable-hypothesis, finite-state trajectory
endpoint.  The public theorem has no `Fintype` assumption on the hypothesis
space: in particular, the final `#check` fixes the hypothesis type to `Real`
while leaving the prior and posterior as arbitrary probability measures.

The endpoint mixes the actual forward predictable-mean e-process over the
prior.  For finite state, coordinatewise hypothesis measurability of the score
now derives joint strong measurability of that parameterized process in both
the time-`n` filtration product and the ambient product sigma algebra.  The
capstone therefore exposes no separate process-measurability assumption.
-/

open MeasureTheory ProbabilityTheory
open FormalSLT.AnytimeValid
open FormalSLT.PACBayes.ContinuousForwardPredictableMeanBesselPACBayes
open FormalSLT.StochasticDynamics

#check continuousForwardPredictableMeanBesselPriorProcess
#check continuousForwardPredictableMeanBesselMasterProcess
#check continuousForwardPosteriorHybridBesselPenalty
#check continuousForwardPredictableMeanBesselBoundary
#check continuousForwardPredictableMeanBesselScore
#check continuousForwardPredictableMeanBesselExceptionalEvent
#check forwardPredictableMeanEmpiricalBernsteinLowerProcess_le_exp_card
#check stronglyMeasurable_forwardPrefixMean_parameter
#check stronglyMeasurable_forwardBesselQ_parameter
#check stronglyMeasurable_forwardHybridBesselPenalty_parameter
#check forwardPrefixMean_mem_Icc_of_unit
#check forwardHybridBesselPenalty_nonneg_of_unit
#check forwardHybridBesselPenalty_le_of_unit
#check continuousForwardPredictableMeanBesselPriorProcess_eProcess
#check continuousForwardPredictableMeanBesselMasterProcess_eProcess
#check continuousForwardPredictableMeanBesselExceptionalEvent_mass_le_delta
#check stronglyMeasurable_continuousForwardPredictableMeanBesselScore
#check continuousForwardPredictableMeanBesselScore_eq_prefixMeans
#check integrable_forwardPrefixMean_parameter_of_unit
#check integrable_forwardHybridBesselPenalty_parameter_of_unit
#check integrable_continuousForwardPredictableMeanBesselScore
#check integrable_exp_continuousForwardPredictableMeanBesselScore
#check integral_continuousForwardPredictableMeanBesselScore
#check continuousForwardPredictableMeanBessel_boundaryFailure_mem_exceptionalEvent
#check continuousForwardPredictableMeanBessel_allPosteriors_of_not_mem
#check exists_continuousForwardPredictableMeanBesselPACBayes_event

#check stronglyMeasurable_uncurry_of_finite_discrete_right
#check stronglyMeasurable_conditionalTrajectoryRisk_parameter
#check measurableSpace_prod_piLE_le_ambient
#check stronglyMeasurable_observedTrajectoryScore_parameter_prod
#check stronglyMeasurable_conditionalTrajectoryRisk_parameter_prod
#check stronglyMeasurable_continuousTrajectoryLowerProcess_filtered
#check stronglyMeasurable_continuousTrajectoryLowerProcess_ambient
#check continuousTrajectoryPosteriorAverageConditionalRisk
#check continuousTrajectoryPosteriorEmpiricalPrequentialRisk
#check continuousTrajectoryPosteriorHybridBesselPenalty
#check continuousTrajectoryEmpiricalBernsteinPACBayesBoundary
#check continuousTrajectoryEmpiricalBernsteinPACBayesBoundary_eq_generic
#check continuousTrajectoryPosteriorAverageConditionalRisk_eq_generic
#check continuousTrajectoryPosteriorEmpiricalPrequentialRisk_eq_generic
#check continuousTrajectoryPosteriorHybridBesselPenalty_eq_generic
#check exists_continuousTrajectoryEmpiricalBernsteinPACBayes_event

#check (exists_continuousTrajectoryEmpiricalBernsteinPACBayes_event
  (Theta := Real))

#print axioms forwardPredictableMeanEmpiricalBernsteinLowerProcess_le_exp_card
#print axioms stronglyMeasurable_forwardPrefixMean_parameter
#print axioms stronglyMeasurable_forwardBesselQ_parameter
#print axioms stronglyMeasurable_forwardHybridBesselPenalty_parameter
#print axioms forwardPrefixMean_mem_Icc_of_unit
#print axioms forwardHybridBesselPenalty_nonneg_of_unit
#print axioms forwardHybridBesselPenalty_le_of_unit
#print axioms continuousForwardPredictableMeanBesselPriorProcess_eProcess
#print axioms continuousForwardPredictableMeanBesselMasterProcess_eProcess
#print axioms continuousForwardPredictableMeanBesselExceptionalEvent_mass_le_delta
#print axioms stronglyMeasurable_continuousForwardPredictableMeanBesselScore
#print axioms continuousForwardPredictableMeanBesselScore_eq_prefixMeans
#print axioms integrable_forwardPrefixMean_parameter_of_unit
#print axioms integrable_forwardHybridBesselPenalty_parameter_of_unit
#print axioms integrable_continuousForwardPredictableMeanBesselScore
#print axioms integrable_exp_continuousForwardPredictableMeanBesselScore
#print axioms integral_continuousForwardPredictableMeanBesselScore
#print axioms continuousForwardPredictableMeanBessel_boundaryFailure_mem_exceptionalEvent
#print axioms continuousForwardPredictableMeanBessel_allPosteriors_of_not_mem
#print axioms exists_continuousForwardPredictableMeanBesselPACBayes_event
#print axioms stronglyMeasurable_uncurry_of_finite_discrete_right
#print axioms stronglyMeasurable_conditionalTrajectoryRisk_parameter
#print axioms measurableSpace_prod_piLE_le_ambient
#print axioms stronglyMeasurable_observedTrajectoryScore_parameter_prod
#print axioms stronglyMeasurable_conditionalTrajectoryRisk_parameter_prod
#print axioms stronglyMeasurable_continuousTrajectoryLowerProcess_filtered
#print axioms stronglyMeasurable_continuousTrajectoryLowerProcess_ambient
#print axioms continuousTrajectoryEmpiricalBernsteinPACBayesBoundary_eq_generic
#print axioms continuousTrajectoryPosteriorAverageConditionalRisk_eq_generic
#print axioms continuousTrajectoryPosteriorEmpiricalPrequentialRisk_eq_generic
#print axioms continuousTrajectoryPosteriorHybridBesselPenalty_eq_generic
#print axioms exists_continuousTrajectoryEmpiricalBernsteinPACBayes_event
