import FormalSLT.AnytimeValid.SingularFractionObservableLIL

open FormalSLT.AnytimeValid

#check singularFractionObservablePenaltyFloor
#check singularFractionObservableLogPenaltyFloor
#check singularFractionObservableRawCost
#check singularFractionObservableCost
#check singularFractionObservableScale
#check singularFractionObservableTunedLambda
#check singularFractionObservableLILBoundary

#check le_singularFractionObservablePenaltyFloor
#check exp_two_le_singularFractionObservablePenaltyFloor
#check singularFractionObservablePenaltyFloor_pos
#check two_le_singularFractionObservableLogPenaltyFloor
#check singularFractionObservableRawCost_pos
#check one_le_singularFractionObservableCost
#check singularFractionObservableRawCost_le_cost
#check singularFractionObservableCost_pos
#check singularFractionObservablePenaltyFloor_le_scale
#check exp_two_mul_cost_le_singularFractionObservableScale
#check singularFractionObservableScale_pos
#check singularFractionObservableScale_div_cost_le_penaltyFloor
#check singularFractionObservableTunedLambda_pos
#check singularFractionObservableTunedLambda_sq
#check singularFractionObservableTunedLambda_le_exp_neg_one
#check singularFractionLogScale_tunedLambda_eq
#check singularFractionLogScale_tunedLambda_le_half_logPenaltyFloor
#check singularFraction_tunedLambda_logWindowCost_le
#check singularFraction_tunedBoundary_le_observableLIL
#check singularFractionLowerMixture_all_fraction_mean
#check singularFractionLowerMixture_timeUniform_all_fraction_mean
#check singularFractionLowerMixture_observableLIL_boundary
#check singularFractionLowerMixture_observableLIL_mean
#check singularFractionLowerMixture_timeUniform_observableLIL
#check singularFractionLowerMixture_timeUniform_observableLIL_mean

#print axioms le_singularFractionObservablePenaltyFloor
#print axioms exp_two_le_singularFractionObservablePenaltyFloor
#print axioms singularFractionObservablePenaltyFloor_pos
#print axioms two_le_singularFractionObservableLogPenaltyFloor
#print axioms singularFractionObservableRawCost_pos
#print axioms one_le_singularFractionObservableCost
#print axioms singularFractionObservableRawCost_le_cost
#print axioms singularFractionObservableCost_pos
#print axioms singularFractionObservablePenaltyFloor_le_scale
#print axioms exp_two_mul_cost_le_singularFractionObservableScale
#print axioms singularFractionObservableScale_pos
#print axioms singularFractionObservableScale_div_cost_le_penaltyFloor
#print axioms singularFractionObservableTunedLambda_pos
#print axioms singularFractionObservableTunedLambda_sq
#print axioms singularFractionObservableTunedLambda_le_exp_neg_one
#print axioms singularFractionLogScale_tunedLambda_eq
#print axioms singularFractionLogScale_tunedLambda_le_half_logPenaltyFloor
#print axioms singularFraction_tunedLambda_logWindowCost_le
#print axioms singularFraction_tunedBoundary_le_observableLIL
#print axioms singularFractionLowerMixture_timeUniform_all_fraction_mean
#print axioms singularFractionLowerMixture_timeUniform_observableLIL
#print axioms singularFractionLowerMixture_timeUniform_observableLIL_mean
