import FormalSLT.StochasticDynamics.FiniteTrajectorySleepingStrategyOrdinaryRiskPACBayes

/-!
# Finite sleeping-strategy posterior ordinary-risk checks

The checked endpoint uses one predeclared common wake and a finite strategy
catalog. Model and strategy posteriors may be selected from the observed path;
their KL costs remain separate. The conclusion is ordinary encountered
conditional risk on the monitored suffix after an explicit finite-TV surcharge.
It does not provide countable or post-data wake selection.
-/

open FormalSLT.StochasticDynamics

#check finiteStrategyPosteriorEffectiveTrajectoryWeight
#check finiteStrategyPosteriorSleepingExposure
#check finiteStrategyPosteriorSleepingUniformDiscrepancy
#check finiteTrajectorySleepingStrategyPosteriorNormalizedConditionalSuffixRisk
#check finiteTrajectorySleepingStrategyPosteriorNormalizedEmpiricalSuffixRisk
#check trajectorySleepingStrategyPosteriorTotalWeight_commonWake_factorized
#check trajectorySleepingStrategyPosteriorNormalizedConditionalRisk_commonWake_factorized
#check trajectorySleepingStrategyPosteriorNormalizedEmpiricalRisk_commonWake_factorized
#check abs_finiteTrajectoryPosteriorConditionalSuffixRisk_sub_sleepingStrategyPosteriorNormalized_le
#check abs_finiteTrajectoryPosteriorEmpiricalSuffixRisk_sub_sleepingStrategyPosteriorNormalized_le
#check finiteTrajectorySleepingStrategyPosteriorExcess
#check finiteTrajectorySleepingStrategyPosteriorOrdinarySuffixBoundary
#check finiteTrajectorySleepingStrategyPosterior_ordinaryRisk_of_weighted
#check exists_finiteTrajectorySleepingStrategyPACBayes_factorized_ordinarySuffixRisk_selected_event

#print axioms trajectorySleepingStrategyPosteriorTotalWeight_commonWake_factorized
#print axioms trajectorySleepingStrategyPosteriorNormalizedConditionalRisk_commonWake_factorized
#print axioms trajectorySleepingStrategyPosteriorNormalizedEmpiricalRisk_commonWake_factorized
#print axioms abs_finiteTrajectoryPosteriorConditionalSuffixRisk_sub_sleepingStrategyPosteriorNormalized_le
#print axioms abs_finiteTrajectoryPosteriorEmpiricalSuffixRisk_sub_sleepingStrategyPosteriorNormalized_le
#print axioms finiteTrajectorySleepingStrategyPosterior_ordinaryRisk_of_weighted
#print axioms exists_finiteTrajectorySleepingStrategyPACBayes_factorized_ordinarySuffixRisk_selected_event
