import FormalSLT.PACBayes.ContinuousForwardPredictableMeanBesselPACBayesOracle

/-!
# Countable continuous-hypothesis forward PAC-Bayes checks

The capstone has no finite hypothesis-space assumption. The final check fixes
the hypothesis type to `Real`; posterior measures may still be selected after
the path subject to the displayed absolute-continuity and log-density
integrability conditions.
-/

open FormalSLT.PACBayes.ContinuousForwardPredictableMeanBesselPACBayesCountable
open FormalSLT.PACBayes.ContinuousForwardPredictableMeanBesselPACBayesOracle

#check countableContinuousForwardPredictableMeanBesselTiltComponent
#check countableContinuousForwardPredictableMeanBesselMasterProcess
#check countableContinuousForwardPredictableMeanBesselBoundary
#check countableContinuousForwardPredictableMeanBesselExceptionalEvent
#check countableContinuousForwardPredictableMeanBesselTiltComponent_eProcess
#check countableContinuousForwardPredictableMeanBesselTiltComponent_nonneg
#check countableContinuousForwardPredictableMeanBesselTiltComponent_le_exp_card
#check countableContinuousForwardPredictableMeanBesselMasterProcess_pointwise_summable
#check countableContinuousForwardPredictableMeanBesselMasterProcess_nonneg
#check countableContinuousForwardPredictableMeanBesselMasterProcess_le_exp_card
#check countableContinuousForwardPredictableMeanBesselMasterProcess_stronglyAdapted
#check countableContinuousForwardPredictableMeanBesselMasterProcess_integrable
#check countableContinuousForwardPredictableMeanBesselMasterProcess_integralNorm_summable
#check countableContinuousForwardPredictableMeanBesselMasterProcess_eProcess
#check countableContinuousForwardPredictableMeanBesselExceptionalEvent_mass_le_delta
#check countableContinuousForwardPredictableMeanBessel_boundaryFailure_mem_exceptionalEvent
#check countableContinuousForwardPredictableMeanBessel_allPosteriors_of_not_mem
#check countableContinuousForwardPredictableMeanBessel_selected_of_not_mem
#check exists_countableContinuousForwardPredictableMeanBesselPACBayes_event

#check countableContinuousForwardPredictableMeanBesselFinitePrefixArgmin
#check countableContinuousForwardPredictableMeanBesselFinitePrefixArgmin_mem
#check countableContinuousForwardPredictableMeanBesselFinitePrefixArgmin_le
#check continuousGeometricForwardBesselPACBayesComplexity
#check continuousGeometricForwardBesselPACBayesComplexity_mono
#check continuousGrowingPrefixForwardBesselPACBayesComplexity
#check continuousGrowingPrefixForwardBesselPACBayesComplexity_half_le
#check continuousGrowingPrefixForwardBesselPACBayesComplexity_eq_logLog
#check continuousForwardPosteriorHybridBesselPenalty_mem_Icc
#check continuousGrowingPrefixForwardBesselPACBayesLILEnvelope
#check continuousGrowingPrefixForwardBesselPACBayesArgmin
#check continuousGrowingPrefixForwardBesselPACBayesArgmin_mem
#check continuousGrowingPrefixForwardBesselPACBayesArgmin_le
#check countableContinuousForwardPredictableMeanBesselBoundary_le_observableRate
#check continuousGrowingPrefixForwardBesselPACBayesBoundary_le_LILEnvelope
#check countableContinuousForwardPredictableMeanBesselBoundary_le_geometricRate
#check countableContinuousForwardPredictableMeanBesselBoundary_nonneg
#check continuousGrowingPrefixForwardBesselPACBayesBoundary_le_allTimeRate
#check continuousGrowingPrefixForwardBesselPACBayesBoundary_tendsto_zero
#check exists_continuousGrowingPrefixForwardBesselPACBayesOracle_event

#check (exists_countableContinuousForwardPredictableMeanBesselPACBayes_event
  (Theta := Real))
#check (exists_continuousGrowingPrefixForwardBesselPACBayesOracle_event
  (Theta := Real))

#print axioms countableContinuousForwardPredictableMeanBesselTiltComponent_eProcess
#print axioms countableContinuousForwardPredictableMeanBesselTiltComponent_le_exp_card
#print axioms countableContinuousForwardPredictableMeanBesselMasterProcess_pointwise_summable
#print axioms countableContinuousForwardPredictableMeanBesselMasterProcess_stronglyAdapted
#print axioms countableContinuousForwardPredictableMeanBesselMasterProcess_integrable
#print axioms countableContinuousForwardPredictableMeanBesselMasterProcess_integralNorm_summable
#print axioms countableContinuousForwardPredictableMeanBesselMasterProcess_eProcess
#print axioms countableContinuousForwardPredictableMeanBesselExceptionalEvent_mass_le_delta
#print axioms countableContinuousForwardPredictableMeanBessel_boundaryFailure_mem_exceptionalEvent
#print axioms countableContinuousForwardPredictableMeanBessel_allPosteriors_of_not_mem
#print axioms countableContinuousForwardPredictableMeanBessel_selected_of_not_mem
#print axioms exists_countableContinuousForwardPredictableMeanBesselPACBayes_event

#print axioms FormalSLT.PACBayes.ForwardBesselPACBayesOracle.exists_dyadic_quadratic_oracle
#print axioms continuousForwardPosteriorHybridBesselPenalty_mem_Icc
#print axioms continuousGrowingPrefixForwardBesselPACBayesBoundary_le_LILEnvelope
#print axioms countableContinuousForwardPredictableMeanBesselBoundary_le_geometricRate
#print axioms countableContinuousForwardPredictableMeanBesselBoundary_nonneg
#print axioms continuousGrowingPrefixForwardBesselPACBayesBoundary_le_allTimeRate
#print axioms continuousGrowingPrefixForwardBesselPACBayesBoundary_tendsto_zero
#print axioms exists_continuousGrowingPrefixForwardBesselPACBayesOracle_event
