import FormalSLT.TestTimeMeta.FlagshipComposition
import FormalSLT.TestTimeMeta.FlagshipFourComponentAssembly

/-!
# Axiom audit for component-to-flagship composition
-/

open FormalSLT.TestTimeMeta

#print axioms flagshipMcAllesterContribution_from_compileGeneralWidth
#print axioms flagshipOnlineIidContribution_from_iidRegretConversion
#print axioms flagshipGaussianBernsteinContribution_from_sphericalGaussian
#print axioms flagshipDerivedContributions_from_components
#print axioms flagshipScalarAssembly_from_componentInequalities
#print axioms flagshipCertificate_from_components
#print axioms flagshipFourComponent_population_le_bound_from_incrementModel
#print axioms flagshipFourComponent_conclusion_from_incrementModel

#check @flagshipMcAllesterContribution
#check @flagshipOnlineIidContribution
#check @flagshipGaussianBernsteinContribution
#check @FlagshipScalarComponentBounds
#check @flagshipMcAllesterContribution_from_compileGeneralWidth
#check @flagshipOnlineIidContribution_from_iidRegretConversion
#check @flagshipGaussianBernsteinContribution_from_sphericalGaussian
#check @flagshipDerivedContributions_from_components
#check @flagshipScalarAssembly_from_componentInequalities
#check @flagshipCertificate_from_components
#check @flagshipFourComponent_population_le_bound_from_incrementModel
#check @flagshipFourComponent_conclusion_from_incrementModel
