import FormalSLT.Covering.TotalBoundedDudleyMinimalCapstone

/-!
Checks for the total-bounded Dudley capstone using the cardinal-minimal
dyadic selected-net schedule.
-/

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalCapstone.minimalDyadicChainingCoverCount

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalCapstone.minimalDyadicChainingCoverCount_eq_minimalMetricCoveringNumber_mul

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalCapstone.minimalDyadicChainingCoverCount_pos

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalCapstone.minimalDyadicChainingFiniteNetOfTotallyBoundedUniv_pair_radius_pos

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalCapstone.minimalDyadicChainingFiniteNetOfTotallyBoundedUniv_pair_radius_le

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalCapstone.minimalDyadicCoverCountEnvelope

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalCapstone.minimalDyadicCoverCountEnvelopeAtRadius

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalCapstone.minimalDyadicCoverCountEntropyAtRadius

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalCapstone.minimalDyadicCoverCountEnvelopeAtRadius_dyadic

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalCapstone.minimalDyadicCoverCountEnvelopeAtRadius_const_on_halfOpenAnnulus

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalCapstone.minimalDyadicCoverCountEnvelope_pos

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalCapstone.monotone_minimalDyadicCoverCountEnvelope

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalCapstone.monotone_minimalDyadicCoverCountEntropyAtScale

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalCapstone.minimalDyadicCoverCountEntropyAtRadius_nonneg

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalCapstone.minimalDyadicCoverCountEntropyAtRadius_guarded

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalCapstone.minimalDyadicCoverCountEntropy_dominates_dyadicEnvelope_sample

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalCapstone.finite_projectedNet_dudley_entropy_sum_totalBounded_minimalDyadic_entropy_integral_comparison_nonempty

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalCapstone.MinimalSeparableTerminalSupremumBoundaryChoiceNonempty

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalCapstone.totalBoundedMinimalDyadicCoverCount_dyadicProfileBound_of_boundaryChoice

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalCapstone.continuous_dudley_entropy_integral_iSup_totalBounded_minimalDyadicCoverCountEnvelope

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalCapstone.unitInterval_minimalDyadicCoverCountEnvelope_sample_positive
