import FormalSLT.Covering.TotalBoundedDudleyCovering

/-!
# Total-bounded covering-number staircase checker

This checker records the generic selected-cover-count staircase used by the
totally-bounded Dudley lane.
-/

#check FormalSLT.Covering.TotalBoundedDudleyCovering.totalBoundedCoveringIndex

#check FormalSLT.Covering.TotalBoundedDudleyCovering.totalBoundedDyadicCoverCountEnvelope
#print axioms FormalSLT.Covering.TotalBoundedDudleyCovering.totalBoundedDyadicCoverCountEnvelope

#check FormalSLT.Covering.TotalBoundedDudleyCovering.totalBoundedCoveringNumberAtRadius

#check FormalSLT.Covering.TotalBoundedDudleyCovering.totalBoundedCoveringNumberAtRadiusENat

#check FormalSLT.Covering.TotalBoundedDudleyCovering.totalBoundedCoveringEntropyAtRadius

#check FormalSLT.Covering.TotalBoundedDudleyCovering.totalBoundedCoveringNumberAtRadius_dyadic
#print axioms FormalSLT.Covering.TotalBoundedDudleyCovering.totalBoundedCoveringNumberAtRadius_dyadic

#check FormalSLT.Covering.TotalBoundedDudleyCovering.totalBoundedCoveringNumberAtRadius_const_on_halfOpenAnnulus
#print axioms FormalSLT.Covering.TotalBoundedDudleyCovering.totalBoundedCoveringNumberAtRadius_const_on_halfOpenAnnulus

#check FormalSLT.Covering.TotalBoundedDudleyCovering.totalBoundedCoveringNumberAtRadiusENat_ne_top
#print axioms FormalSLT.Covering.TotalBoundedDudleyCovering.totalBoundedCoveringNumberAtRadiusENat_ne_top

#check FormalSLT.Covering.TotalBoundedDudleyCovering.totalBoundedCoveringNumberAtRadiusENat_toReal
#print axioms FormalSLT.Covering.TotalBoundedDudleyCovering.totalBoundedCoveringNumberAtRadiusENat_toReal

#check FormalSLT.Covering.TotalBoundedDudleyCovering.totalBoundedCoveringEntropyAtRadius_nonneg
#print axioms FormalSLT.Covering.TotalBoundedDudleyCovering.totalBoundedCoveringEntropyAtRadius_nonneg

#check FormalSLT.Covering.TotalBoundedDudleyCovering.totalBoundedCoveringEntropyAtRadius_guarded
#print axioms FormalSLT.Covering.TotalBoundedDudleyCovering.totalBoundedCoveringEntropyAtRadius_guarded

#check FormalSLT.Covering.TotalBoundedDudleyCovering.totalBoundedCoveringEntropy_dominates_dyadicEnvelope_sample
#print axioms FormalSLT.Covering.TotalBoundedDudleyCovering.totalBoundedCoveringEntropy_dominates_dyadicEnvelope_sample

#check FormalSLT.Covering.TotalBoundedDudleyCovering.unitInterval_totalBoundedCoveringNumber_sample_positive
#print axioms FormalSLT.Covering.TotalBoundedDudleyCovering.unitInterval_totalBoundedCoveringNumber_sample_positive
