import FormalSLT.StochasticDynamics.ContinuousTrajectorySleepingPredictableTiltOrdinaryRisk

/-!
# Time-varying predictable-tilt ordinary-risk bridge checks

The checked endpoint converts the existing normalized tilt-weighted theorem
to ordinary encountered conditional suffix risk. It pays twice the realized
uniform-weight discrepancy and does not assert future, stationary, population,
or deployment risk.
-/

open FormalSLT.StochasticDynamics

#check finiteUniformNormalizedWeightDiscrepancy
#check abs_weightedSum_sub_weightedSum_le_half_l1
#check abs_uniformAverage_sub_normalizedWeightedAverage_le_discrepancy
#check continuousTrajectorySleepingPredictableTiltUniformDiscrepancy
#check continuousTrajectorySleepingPredictableTiltExposure_eq_sum_Ico
#check abs_trajectoryConditionalSuffixAverage_sub_sleepingNormalizedConditionalMeanAt_le
#check abs_trajectoryEmpiricalSuffixAverage_sub_sleepingNormalizedObservationAt_le
#check abs_continuousTrajectoryPosteriorAverageConditionalSuffixRisk_sub_normalized_le
#check abs_continuousTrajectoryPosteriorEmpiricalSuffixRisk_sub_normalized_le
#check continuousTrajectorySleepingPredictableTiltExcess
#check continuousTrajectorySleepingPredictableTiltOrdinarySuffixBoundary
#check continuousTrajectorySleepingPredictableTilt_ordinaryRisk_of_weighted
#check exists_continuousTrajectorySleepingPredictableTiltPACBayes_ordinarySuffixRisk_event_of_parameterMeasurable
#check continuousTrajectorySleepingPredictableTiltUniformDiscrepancy_countableConstant

#check (exists_continuousTrajectorySleepingPredictableTiltPACBayes_ordinarySuffixRisk_event_of_parameterMeasurable
  (Theta := Real))

#print axioms abs_weightedSum_sub_weightedSum_le_half_l1
#print axioms abs_uniformAverage_sub_normalizedWeightedAverage_le_discrepancy
#print axioms continuousTrajectorySleepingPredictableTiltExposure_eq_sum_Ico
#print axioms abs_trajectoryConditionalSuffixAverage_sub_sleepingNormalizedConditionalMeanAt_le
#print axioms abs_trajectoryEmpiricalSuffixAverage_sub_sleepingNormalizedObservationAt_le
#print axioms abs_continuousTrajectoryPosteriorAverageConditionalSuffixRisk_sub_normalized_le
#print axioms abs_continuousTrajectoryPosteriorEmpiricalSuffixRisk_sub_normalized_le
#print axioms continuousTrajectorySleepingPredictableTilt_ordinaryRisk_of_weighted
#print axioms exists_continuousTrajectorySleepingPredictableTiltPACBayes_ordinarySuffixRisk_event_of_parameterMeasurable
#print axioms continuousTrajectorySleepingPredictableTiltUniformDiscrepancy_countableConstant
