import FormalSLT.PACBayes.ForwardBesselPACBayesCountable

open FormalSLT.AnytimeValid
open FormalSLT.PACBayes.ForwardBesselPACBayesCountable

#check countableWeightedProcess_eProcess
#check countableForwardBesselPACBayesMasterProcess_eProcess_of_bounded
#check exists_countableForwardBesselPACBayes_event
#check exists_geometricForwardBesselPACBayes_event
#check geometricPolynomialForwardRate_tendsto_zero
#check countableForwardBesselPACBayesBoundary_tendsto_zero

#print axioms countableWeightedProcess_eProcess
#print axioms countableForwardBesselPACBayesMasterProcess_eProcess_of_bounded
#print axioms exists_countableForwardBesselPACBayes_event
#print axioms exists_geometricForwardBesselPACBayes_event
#print axioms geometricPolynomialForwardRate_tendsto_zero
#print axioms countableForwardBesselPACBayesBoundary_tendsto_zero
