import FormalSLT.TestTimeMeta.FlagshipFourComponentAssembly

/-!
# Axiom audit for the public four-component PAC-Bayes test-time flagship theorem
-/

open FormalSLT.TestTimeMeta

#print axioms flagshipBound_eq_testTimeMetaBound
#print axioms flagshipFourComponent_four_slots_positive
#print axioms flagshipFourComponent_scalarBounds_from_incrementModel
#print axioms flagshipFourComponent_population_le_bound_from_incrementModel
#print axioms flagshipFourComponent_conclusion_from_incrementModel

#check @FlagshipUserSupplied
#check @FlagshipDerivedContributions
#check @FlagshipCertificate
#check @flagshipFourComponent_four_slots_positive
#check @flagshipFourComponent_scalarBounds_from_incrementModel
#check @flagshipFourComponent_population_le_bound_from_incrementModel
#check @flagshipFourComponent_conclusion_from_incrementModel
