import FormalSLT.PACBayes.FiniteJointMeanVarianceReverseCatalog

/-!
# Finite reverse-epoch joint tilt catalog API receipt

This checker audits the public catalog mixture, its one Doob event, the
all-atom/all-prefix/all-posterior mass statement, and pointwise selection of a
predeclared atom after the path and posterior are observed.
-/

open FormalSLT.PACBayes.FiniteJointMeanVarianceReverse

#check reverseJointMeanVarianceEpochCatalogMixture_nonneg
#check reverseJointMeanVarianceEpochCatalogMixture_submartingale
#check reverseJointMeanVarianceEpochCatalogMixture_endpoint_integral_le_one
#check reverseJointMeanVarianceEpochCatalogAnyPosteriorFailure_subset_badPaths
#check reverseJointMeanVarianceEpochCatalogMixture_maximal_le_one
#check reverseJointMeanVarianceEpochCatalogAnyPosteriorFailure_mass_le_delta
#check reverseJointMeanVarianceEpochCatalog_posteriorRisk_prefix_lt_of_not_mem
#check reverseJointMeanVarianceEpochCatalog_posteriorRisk_prefix_lt_selected_of_not_mem

#print axioms reverseJointMeanVarianceEpochCatalogMixture_nonneg
#print axioms reverseJointMeanVarianceEpochCatalogMixture_submartingale
#print axioms reverseJointMeanVarianceEpochCatalogMixture_endpoint_integral_le_one
#print axioms reverseJointMeanVarianceEpochCatalogAnyPosteriorFailure_subset_badPaths
#print axioms reverseJointMeanVarianceEpochCatalogMixture_maximal_le_one
#print axioms reverseJointMeanVarianceEpochCatalogAnyPosteriorFailure_mass_le_delta
#print axioms reverseJointMeanVarianceEpochCatalog_posteriorRisk_prefix_lt_of_not_mem
#print axioms reverseJointMeanVarianceEpochCatalog_posteriorRisk_prefix_lt_selected_of_not_mem
