import FormalSLT

/-!
# Showcase theorem audit

This file checks the public theorem families used in the README and prints the
axioms for representative declarations. It is intentionally separate from the
library target so reviewers can run it directly:

```bash
lake env lean examples/CheckShowcaseTheorems.lean
```
-/

#check FormalSLT.Rademacher.Symmetrization.expected_genGap_le_two_expected_empiricalRademacherComplexity
#print axioms FormalSLT.Rademacher.Symmetrization.expected_genGap_le_two_expected_empiricalRademacherComplexity

#check FormalSLT.Rademacher.HighProbability.genGap_highProb_rademacher
#print axioms FormalSLT.Rademacher.HighProbability.genGap_highProb_rademacher

#check FormalSLT.Rademacher.Massart.massart_finite_class
#print axioms FormalSLT.Rademacher.Massart.massart_finite_class

#check FormalSLT.VC.SampleComplexity.vc_erm_excessRisk_tail
#print axioms FormalSLT.VC.SampleComplexity.vc_erm_excessRisk_tail

#check FormalSLT.VC.SampleComplexity.vc_erm_sample_complexity
#print axioms FormalSLT.VC.SampleComplexity.vc_erm_sample_complexity

#check FormalSLT.Rademacher.Contraction.empiricalRademacherComplexity_contraction_lipschitz
#print axioms FormalSLT.Rademacher.Contraction.empiricalRademacherComplexity_contraction_lipschitz

#check FormalSLT.Rademacher.LinearPredictor.linearPredictor_rademacher_finiteDim
#print axioms FormalSLT.Rademacher.LinearPredictor.linearPredictor_rademacher_finiteDim

#check FormalSLT.Rademacher.LinearPredictor.linearPredictor_rademacher_uniform_finiteDim
#print axioms FormalSLT.Rademacher.LinearPredictor.linearPredictor_rademacher_uniform_finiteDim

#check FormalSLT.Rademacher.Localized.localizedExcessRiskEmpiricalRademacherComplexity_le_secondMoment
#print axioms FormalSLT.Rademacher.Localized.localizedExcessRiskEmpiricalRademacherComplexity_le_secondMoment

#check FormalSLT.Covering.FiniteSubGaussianChaining.finite_expectedSup_le_of_mgf_log
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.finite_expectedSup_le_of_mgf_log

#check FormalSLT.Covering.FiniteSubGaussianChaining.finite_expectedSup_le_of_subGaussian_mgf_sqrt
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.finite_expectedSup_le_of_subGaussian_mgf_sqrt

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_dudley_entropy_sum_coveringNumbers_geometric_entropy_budget
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_dudley_entropy_sum_coveringNumbers_geometric_entropy_budget

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_dudley_entropy_sum_projection_pairs_geometric_uniform_entropy
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_dudley_entropy_sum_projection_pairs_geometric_uniform_entropy

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_dudley_entropy_sum_coveringNumbers_geometric_uniform_entropy
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_dudley_entropy_sum_coveringNumbers_geometric_uniform_entropy

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_dudley_entropy_sum_projection_pairs_geometric_annulus_budget
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_dudley_entropy_sum_projection_pairs_geometric_annulus_budget

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_dudley_entropy_sum_coveringNumbers_geometric_annulus_budget
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_dudley_entropy_sum_coveringNumbers_geometric_annulus_budget

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finiteDyadicEntropyIntegralBudget
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finiteDyadicEntropyIntegralBudget

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finiteDyadicEntropyAtRadiusUpperSum
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finiteDyadicEntropyAtRadiusUpperSum

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finiteDyadicEntropyIntegralBudget_le_entropyAtRadiusUpperSum
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finiteDyadicEntropyIntegralBudget_le_entropyAtRadiusUpperSum

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finiteDyadicEntropyIntegralBudget_le_of_entropyAtRadiusUpperSum_le
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finiteDyadicEntropyIntegralBudget_le_of_entropyAtRadiusUpperSum_le

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_dudley_entropy_sum_projection_pairs_geometric_integral_budget
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_dudley_entropy_sum_projection_pairs_geometric_integral_budget

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_dudley_entropy_sum_coveringNumbers_geometric_integral_budget
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_dudley_entropy_sum_coveringNumbers_geometric_integral_budget

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finitePrefixSupEnvelope
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finitePrefixSupEnvelope

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.monotone_finitePrefixSupEnvelope
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.monotone_finitePrefixSupEnvelope

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_dudley_entropy_sum_coveringNumbers_geometric_integral_budget_prefix_envelope
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_dudley_entropy_sum_coveringNumbers_geometric_integral_budget_prefix_envelope

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projected_dudley_entropy_sum_coveringNumbers_geometric_integral_budget_prefix_envelope
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projected_dudley_entropy_sum_coveringNumbers_geometric_integral_budget_prefix_envelope

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projectedNet_dudley_entropy_sum_coveringNumbers_geometric_integral_budget_prefix_envelope
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projectedNet_dudley_entropy_sum_coveringNumbers_geometric_integral_budget_prefix_envelope

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projectedNet_dudley_entropy_sum_coveringNumbers_geometric_entropy_integral_comparison
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projectedNet_dudley_entropy_sum_coveringNumbers_geometric_entropy_integral_comparison

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finiteDyadicEntropyAtRadiusUpperSum_le_two_mul_shifted_intervalIntegral_sum
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finiteDyadicEntropyAtRadiusUpperSum_le_two_mul_shifted_intervalIntegral_sum

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finiteDyadicEntropyAtRadiusUpperSum_le_two_mul_intervalIntegralBudget
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finiteDyadicEntropyAtRadiusUpperSum_le_two_mul_intervalIntegralBudget

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.shiftedDyadicIntervalIntegralSum_eq_truncatedIntervalIntegral
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.shiftedDyadicIntervalIntegralSum_eq_truncatedIntervalIntegral

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finiteDyadicEntropyAtRadiusUpperSum_le_two_mul_truncatedIntervalIntegral
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finiteDyadicEntropyAtRadiusUpperSum_le_two_mul_truncatedIntervalIntegral

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projectedNet_dudley_entropy_sum_coveringNumbers_geometric_entropy_intervalIntegral_comparison
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projectedNet_dudley_entropy_sum_coveringNumbers_geometric_entropy_intervalIntegral_comparison

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projectedNet_dudley_entropy_sum_coveringNumbers_geometric_entropy_truncatedIntervalIntegral_comparison
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_projectedNet_dudley_entropy_sum_coveringNumbers_geometric_entropy_truncatedIntervalIntegral_comparison

#check FormalSLT.Covering.FiniteSubGaussianChaining.finiteExpectation_supFunctional_le_projected_add_terminalError
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.finiteExpectation_supFunctional_le_projected_add_terminalError

#check FormalSLT.Covering.FiniteSubGaussianChaining.finiteSup_skeleton_le_projectedSup_add_terminalError
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.finiteSup_skeleton_le_projectedSup_add_terminalError

#check FormalSLT.Covering.FiniteSubGaussianChaining.finiteExpectation_supFunctional_le_projected_add_skeleton_terminalError
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.finiteExpectation_supFunctional_le_projected_add_skeleton_terminalError

#check FormalSLT.Covering.FiniteSubGaussianChaining.terminalApprox_of_pathwise_modulus
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.terminalApprox_of_pathwise_modulus

#check FormalSLT.Covering.FiniteSubGaussianChaining.terminalApprox_of_pathwise_modulus_radiusBound
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.terminalApprox_of_pathwise_modulus_radiusBound

#check FormalSLT.Covering.FiniteSubGaussianChaining.finiteSup_le_skeletonSup_add_of_pointwise_approx
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.finiteSup_le_skeletonSup_add_of_pointwise_approx

#check FormalSLT.Covering.FiniteSubGaussianChaining.supFunctional_le_skeletonSup_add_of_witnessed_pointwise_approx
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.supFunctional_le_skeletonSup_add_of_witnessed_pointwise_approx

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_supFunctional_dudley_entropy_sum_coveringNumbers_geometric_entropy_truncatedIntervalIntegral_comparison
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_supFunctional_dudley_entropy_sum_coveringNumbers_geometric_entropy_truncatedIntervalIntegral_comparison

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_separableSupFunctional_dudley_entropy_sum_coveringNumbers_geometric_entropy_truncatedIntervalIntegral_comparison
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.finite_separableSupFunctional_dudley_entropy_sum_coveringNumbers_geometric_entropy_truncatedIntervalIntegral_comparison

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.dyadic_inverse_sum_le_two
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.dyadic_inverse_sum_le_two

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.dyadic_radius_eq_two_mul_annulus_width
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.dyadic_radius_eq_two_mul_annulus_width

#check FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.dyadic_annulus_width_nonneg
#print axioms FormalSLT.Covering.FiniteSubGaussianChaining.FiniteSubGaussianProcess.dyadic_annulus_width_nonneg

#check FormalSLT.Covering.TotalBoundedDudley.dyadicChainingFiniteNetOfTotallyBoundedUniv_pair_radius_le
#print axioms FormalSLT.Covering.TotalBoundedDudley.dyadicChainingFiniteNetOfTotallyBoundedUniv_pair_radius_le

#check FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_coveringNumbers
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_coveringNumbers

#check FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_entropy_integral_comparison
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_entropy_integral_comparison

#check FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_entropy_intervalIntegral_comparison
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_entropy_intervalIntegral_comparison

#check FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison

#check FormalSLT.Covering.TotalBoundedDudley.finite_supFunctional_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_supFunctional_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison

#check FormalSLT.Covering.TotalBoundedDudley.finite_separableSupFunctional_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_separableSupFunctional_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison

#check FormalSLT.Covering.TotalBoundedDudley.finite_witnessedSup_modulus_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_witnessedSup_modulus_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison

#check FormalSLT.Covering.TotalBoundedDudley.EpsilonizedSupremumBoundaryChoice
#check FormalSLT.Covering.TotalBoundedDudley.finite_epsilonizedSup_modulus_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_epsilonizedSup_modulus_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison

#check FormalSLT.Covering.TotalBoundedDudley.skeletonApprox_of_finiteCover_pathwiseModulus
#print axioms FormalSLT.Covering.TotalBoundedDudley.skeletonApprox_of_finiteCover_pathwiseModulus

#check FormalSLT.Covering.TotalBoundedDudley.FiniteCoverSupremumBoundaryChoice

#check FormalSLT.Covering.TotalBoundedDudley.epsilonizedSupremumBoundaryChoice_of_finiteCoverSupremumBoundaryChoice
#print axioms FormalSLT.Covering.TotalBoundedDudley.epsilonizedSupremumBoundaryChoice_of_finiteCoverSupremumBoundaryChoice

#check FormalSLT.Covering.TotalBoundedDudley.finite_epsilonizedSup_dudley_totalBounded_of_finiteCoverSupremumBoundaryChoice
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_epsilonizedSup_dudley_totalBounded_of_finiteCoverSupremumBoundaryChoice

#check FormalSLT.Covering.TotalBoundedDudley.finite_projected_dudley_entropy_sum_totalBounded_dyadic_coveringNumbers
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_projected_dudley_entropy_sum_totalBounded_dyadic_coveringNumbers

#check FormalSLT.Covering.TotalBoundedDudley.finite_dudley_entropy_sum_totalBounded_dyadic_coveringNumbers
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_dudley_entropy_sum_totalBounded_dyadic_coveringNumbers

#check FormalSLT.AlgorithmicStability.FiniteCoordinateSwapIdentity
#print axioms FormalSLT.AlgorithmicStability.FiniteCoordinateSwapIdentity

#check FormalSLT.AlgorithmicStability.finiteProductSampleWeight
#print axioms FormalSLT.AlgorithmicStability.finiteProductSampleWeight

#check FormalSLT.AlgorithmicStability.finiteProductSampleWeight_coordinateSwapIdentity
#print axioms FormalSLT.AlgorithmicStability.finiteProductSampleWeight_coordinateSwapIdentity

#check FormalSLT.AlgorithmicStability.expectedFiniteStabilityGap_le_uniformStability_finiteProduct
#print axioms FormalSLT.AlgorithmicStability.expectedFiniteStabilityGap_le_uniformStability_finiteProduct

#check FormalSLT.AlgorithmicStability.expectedFiniteStabilityGap_le_uniformStability_of_coordinateSwap
#print axioms FormalSLT.AlgorithmicStability.expectedFiniteStabilityGap_le_uniformStability_of_coordinateSwap

#check FormalSLT.AlgorithmicStability.expectedFiniteGeneralizationGap_le_uniformStability_finiteProduct
#print axioms FormalSLT.AlgorithmicStability.expectedFiniteGeneralizationGap_le_uniformStability_finiteProduct

#check FormalSLT.AlgorithmicStability.expectedFiniteGeneralizationGap_le_uniformStability_of_coordinateSwap
#print axioms FormalSLT.AlgorithmicStability.expectedFiniteGeneralizationGap_le_uniformStability_of_coordinateSwap

#check FormalSLT.AlgorithmicStability.abs_expectedFiniteStabilityGap_le_uniformStability_finiteProduct
#print axioms FormalSLT.AlgorithmicStability.abs_expectedFiniteStabilityGap_le_uniformStability_finiteProduct

#check FormalSLT.AlgorithmicStability.abs_expectedFiniteGeneralizationGap_le_uniformStability_finiteProduct
#print axioms FormalSLT.AlgorithmicStability.abs_expectedFiniteGeneralizationGap_le_uniformStability_finiteProduct

#check FormalSLT.AlgorithmicStability.expectedStabilityGap_le_uniformStability_piMeasure_of_boundedLoss
#print axioms FormalSLT.AlgorithmicStability.expectedStabilityGap_le_uniformStability_piMeasure_of_boundedLoss

#check FormalSLT.AlgorithmicStability.abs_expectedStabilityGap_le_uniformStability_piMeasure_of_boundedLoss
#print axioms FormalSLT.AlgorithmicStability.abs_expectedStabilityGap_le_uniformStability_piMeasure_of_boundedLoss

#check FormalSLT.AlgorithmicStability.mcdiarmid_inequality_iid_const_width
#print axioms FormalSLT.AlgorithmicStability.mcdiarmid_inequality_iid_const_width

#check FormalSLT.AlgorithmicStability.bousquet_elisseeff_expectedGap_variant
#print axioms FormalSLT.AlgorithmicStability.bousquet_elisseeff_expectedGap_variant

#check FormalSLT.AlgorithmicStability.boundedLoss_hypothesisLoss_integrable
#print axioms FormalSLT.AlgorithmicStability.boundedLoss_hypothesisLoss_integrable

#check FormalSLT.AlgorithmicStability.finiteClass_trainingLoss_measurable
#print axioms FormalSLT.AlgorithmicStability.finiteClass_trainingLoss_measurable

#check FormalSLT.AlgorithmicStability.finiteClass_stabilityGap_stronglyMeasurable
#print axioms FormalSLT.AlgorithmicStability.finiteClass_stabilityGap_stronglyMeasurable

#check FormalSLT.AlgorithmicStability.boundedLoss_stabilityGap_integrable
#print axioms FormalSLT.AlgorithmicStability.boundedLoss_stabilityGap_integrable

#check FormalSLT.AlgorithmicStability.bousquet_elisseeff_expectedGap_variant_of_boundedLoss
#print axioms FormalSLT.AlgorithmicStability.bousquet_elisseeff_expectedGap_variant_of_boundedLoss

#check FormalSLT.AlgorithmicStability.bousquet_elisseeff_uniform_stability_corollary
#print axioms FormalSLT.AlgorithmicStability.bousquet_elisseeff_uniform_stability_corollary

#check FormalSLT.AlgorithmicStability.bousquet_elisseeff_uniform_stability_corollary_of_boundedLoss
#print axioms FormalSLT.AlgorithmicStability.bousquet_elisseeff_uniform_stability_corollary_of_boundedLoss

#check FormalSLT.PACBayesKL.klDiv_nonneg
#print axioms FormalSLT.PACBayesKL.klDiv_nonneg

#check FormalSLT.PACBayesKL.donsker_varadhan
#print axioms FormalSLT.PACBayesKL.donsker_varadhan

#check FormalSLT.PACBayesMcAllester.pacbayes_changeOfMeasure
#print axioms FormalSLT.PACBayesMcAllester.pacbayes_changeOfMeasure

#check FormalSLT.PACBayesMcAllester.pacbayes_mcallester_deterministic
#print axioms FormalSLT.PACBayesMcAllester.pacbayes_mcallester_deterministic

#check FormalSLT.PACBayesMcAllester.pacbayes_mcallester_subGaussian
#print axioms FormalSLT.PACBayesMcAllester.pacbayes_mcallester_subGaussian

#check FormalSLT.PACBayesMcAllester.pacbayes_mcallester_sqrt
#print axioms FormalSLT.PACBayesMcAllester.pacbayes_mcallester_sqrt

#check FormalSLT.PACBayesFiniteProductMGF.finiteProduct_mgf_empiricalRiskDeviation_eq_pow
#print axioms FormalSLT.PACBayesFiniteProductMGF.finiteProduct_mgf_empiricalRiskDeviation_eq_pow

#check FormalSLT.PACBayesFiniteProductMGF.finiteProduct_mgf_empiricalRiskDeviation_le_of_single
#print axioms FormalSLT.PACBayesFiniteProductMGF.finiteProduct_mgf_empiricalRiskDeviation_le_of_single

#check FormalSLT.PACBayesFiniteProductMGF.finitePriorAveraged_mgf_empiricalRiskDeviation_le
#print axioms FormalSLT.PACBayesFiniteProductMGF.finitePriorAveraged_mgf_empiricalRiskDeviation_le

#check FormalSLT.PACBayesBoundedLoss.oneCoordinate_boundedLoss_mgf
#print axioms FormalSLT.PACBayesBoundedLoss.oneCoordinate_boundedLoss_mgf

#check FormalSLT.PACBayesBoundedLoss.sampleAverage_boundedLoss_mgf
#print axioms FormalSLT.PACBayesBoundedLoss.sampleAverage_boundedLoss_mgf

#check FormalSLT.PACBayesBoundedLoss.priorAveraged_boundedLoss_mgf
#print axioms FormalSLT.PACBayesBoundedLoss.priorAveraged_boundedLoss_mgf

#check FormalSLT.PACBayesBoundedLoss.priorAveraged_boundedLoss_mgf_badEventMass_le_delta
#print axioms FormalSLT.PACBayesBoundedLoss.priorAveraged_boundedLoss_mgf_badEventMass_le_delta

#check FormalSLT.PACBayesBoundedLoss.posteriorRisk_bound_of_priorDeviationMGF_le
#print axioms FormalSLT.PACBayesBoundedLoss.posteriorRisk_bound_of_priorDeviationMGF_le

#check FormalSLT.PACBayesBoundedLoss.finiteCatoni_badEventMass_le_delta
#print axioms FormalSLT.PACBayesBoundedLoss.finiteCatoni_badEventMass_le_delta

#check FormalSLT.PACBayesBoundedLoss.finiteMcAllesterBoundedComplexity_badEventMass_le_delta
#print axioms FormalSLT.PACBayesBoundedLoss.finiteMcAllesterBoundedComplexity_badEventMass_le_delta

#check FormalSLT.PACBayesBoundedLoss.finiteMcAllesterGridPeeling_badEventMass_le_delta
#print axioms FormalSLT.PACBayesBoundedLoss.finiteMcAllesterGridPeeling_badEventMass_le_delta

#check FormalSLT.PACBayesBoundedLoss.finiteMcAllesterGridOptimized_badEventMass_le_delta
#print axioms FormalSLT.PACBayesBoundedLoss.finiteMcAllesterGridOptimized_badEventMass_le_delta

#check FormalSLT.PACBayesBoundedLoss.pac_bayes_generalization
#print axioms FormalSLT.PACBayesBoundedLoss.pac_bayes_generalization
