import FormalSLT.StochasticDynamics.ContinuousTrajectorySleepingOrdinaryRiskPACBayes

/-!
# Ordinary wake-selected trajectory-risk checks

The main endpoint controls the posterior-averaged conditional risk encountered
on a path-selected suffix. It does not assert future, stationary, population,
or deployment risk.
-/

open FormalSLT.StochasticDynamics

#check countableConstantTrajectoryTiltCatalog
#check continuousTrajectoryPosteriorAverageConditionalSuffixRisk
#check continuousTrajectoryPosteriorEmpiricalPrequentialSuffixRisk
#check continuousTrajectorySleepingExposure_countableConstant
#check continuousSleepingWeightedConditionalMeanAt_countableConstant
#check continuousSleepingWeightedObservationAt_countableConstant
#check continuousSleepingPredictorQuadraticPenaltyAt_countableConstant
#check continuousSleepingPosteriorWeightedConditionalMean_countableConstant
#check continuousSleepingPosteriorWeightedObservation_countableConstant
#check continuousTrajectoryPosteriorConstantTiltSuffixPredictorQuadraticPenalty
#check continuousSleepingPosteriorPredictorQuadraticPenalty_countableConstant
#check continuousTrajectorySleepingPosteriorNormalizedConditionalRisk_countableConstant
#check continuousTrajectorySleepingPosteriorNormalizedEmpiricalRisk_countableConstant
#check continuousTrajectorySleepingConstantTiltSuffixBoundary
#check continuousTrajectorySleepingPredictableTiltBoundary_countableConstant
#check exists_continuousTrajectorySleepingConstantTiltPACBayes_suffixRisk_event_of_parameterMeasurable
#check continuousTrajectoryPosteriorAverageConditionalSuffixRisk_zero
#check continuousTrajectoryPosteriorEmpiricalPrequentialSuffixRisk_zero
#check continuousTrajectorySleepingConstantTiltPrefixBoundary
#check exists_continuousTrajectorySleepingConstantTiltPACBayes_prefixRisk_event_of_parameterMeasurable

#check (exists_continuousTrajectorySleepingConstantTiltPACBayes_suffixRisk_event_of_parameterMeasurable
  (Theta := Real))
#check (exists_continuousTrajectorySleepingConstantTiltPACBayes_prefixRisk_event_of_parameterMeasurable
  (Theta := Real))

#print axioms continuousTrajectorySleepingExposure_countableConstant
#print axioms continuousSleepingWeightedConditionalMeanAt_countableConstant
#print axioms continuousSleepingWeightedObservationAt_countableConstant
#print axioms continuousSleepingPredictorQuadraticPenaltyAt_countableConstant
#print axioms continuousSleepingPosteriorWeightedConditionalMean_countableConstant
#print axioms continuousSleepingPosteriorWeightedObservation_countableConstant
#print axioms continuousSleepingPosteriorPredictorQuadraticPenalty_countableConstant
#print axioms continuousTrajectorySleepingPosteriorNormalizedConditionalRisk_countableConstant
#print axioms continuousTrajectorySleepingPosteriorNormalizedEmpiricalRisk_countableConstant
#print axioms continuousTrajectorySleepingPredictableTiltBoundary_countableConstant
#print axioms exists_continuousTrajectorySleepingConstantTiltPACBayes_suffixRisk_event_of_parameterMeasurable
#print axioms continuousTrajectoryPosteriorAverageConditionalSuffixRisk_zero
#print axioms continuousTrajectoryPosteriorEmpiricalPrequentialSuffixRisk_zero
#print axioms exists_continuousTrajectorySleepingConstantTiltPACBayes_prefixRisk_event_of_parameterMeasurable
