import FormalSLT.Covering.TotalBoundedMinimalCovering

/-!
Checks for the totally bounded genuine minimal-covering-number bridge.
-/

open FormalSLT.Covering.TotalBoundedMinimalCovering

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.MetricCoverCardinalityLe

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.minimalMetricCoveringNumber

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.minimalMetricCoveringNumber_spec

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.minimalMetricCoveringNumber_le_of_metricCoverCardinalityLe

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.minimalMetricCoveringNumber_pos

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.metricCoverCardinalityLe_of_bundledFiniteNet

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.minimalMetricCoveringNumber_le_bundledFiniteNet_coveringNumber

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.minimalMetricCoveringNumber_le_dyadicSelectedCoveringNumber

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.minimalMetricCoveringNumber_le_totalBoundedDyadicCoverCountEnvelope

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.unitInterval_minimalMetricCoveringNumber_sample_positive

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.minimalMetricCoverOfTotallyBoundedUniv

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.minimalMetricCoverOfTotallyBoundedUniv_cover

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.minimalMetricCoverOfTotallyBoundedUniv_card_le

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.minimalMetricCoverOfTotallyBoundedUniv_card_eq

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.minimalMetricCoverOfTotallyBoundedUniv_card_minimal

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.minimalFiniteNetOfTotallyBoundedUniv

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.minimalFiniteNetOfTotallyBoundedUniv_radius

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.minimalFiniteNetOfTotallyBoundedUniv_dist

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.minimalFiniteNetOfTotallyBoundedUniv_coveringNumber_eq

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.minimalDyadicChainingFiniteNetOfTotallyBoundedUniv

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.minimalDyadicChainingFiniteNetOfTotallyBoundedUniv_radius

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.minimalDyadicChainingFiniteNetOfTotallyBoundedUniv_dist

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.minimalDyadicChainingFiniteNetOfTotallyBoundedUniv_coveringNumber_eq

#print axioms FormalSLT.Covering.TotalBoundedMinimalCovering.unitInterval_minimalMetricCoverOfTotallyBoundedUniv_sample_card_positive
