import FormalSLT.Covering.TotalBoundedDudleyMinimalShift

/-!
Checks for the shifted single-radius minimal-cover entropy bridge.
-/

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalShift.minimalMetricCoveringNumber_antitone

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalShift.minimalDyadicChainingCoverCount_le_next_minimalMetricCoveringNumber_sq

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalShift.minimalDyadicChainingCoverCount_entropy_le_sqrt_two_mul_next_minimalMetricCoveringEntropy

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalShift.shiftedMinimalMetricCoveringEntropyAtRadius

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalShift.minimalDyadicChainingCoverCountEntropy_dominates_shiftedMinimalEntropy_sample

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalShift.finiteDyadicEntropyAtRadiusUpperSum_shifted_div_four_le_eight_mul_full_integral

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalShift.continuous_dudley_entropy_integral_iSup_totalBounded_minimalMetricCoveringNumber_shifted

#check FormalSLT.Covering.TotalBoundedDudleyMinimalShift.unitInterval_shiftedMinimalMetricCoveringEntropy_sample_nonneg

#print axioms FormalSLT.Covering.TotalBoundedDudleyMinimalShift.unitInterval_shiftedMinimalMetricCoveringEntropy_sample_nonneg
