import FormalSLT.StochasticDynamics.ContinuousMeasurableTrajectorySleepingPredictableTiltMasterProcess

open FormalSLT.StochasticDynamics

#check StronglyMeasurableTrajectoryPredictableTiltCatalog
#check observedTrajectoryPredictableTilt_stronglyAdapted_of_stronglyMeasurable
#check stronglyMeasurable_continuousMeasurableTrajectorySleepingPredictableTiltComponentProcess_filtered
#check stronglyMeasurable_continuousMeasurableTrajectorySleepingPredictableTiltComponentProcess_ambient
#check stronglyMeasurable_continuousMeasurableTrajectorySleepingPredictableTiltMasterProcess_filtered
#check stronglyMeasurable_continuousMeasurableTrajectorySleepingPredictableTiltMasterProcess_ambient
#check continuousMeasurableTrajectorySleepingPredictableTiltMasterProcess_le

-- This specialization witnesses that the process foundation needs neither a
-- finite nor a countable state-space instance.
#check stronglyMeasurable_continuousMeasurableTrajectorySleepingPredictableTiltMasterProcess_filtered
  (Theta := Real) (Z := Real)

#print axioms observedTrajectoryPredictableTilt_stronglyAdapted_of_stronglyMeasurable
#print axioms stronglyMeasurable_continuousMeasurableTrajectorySleepingPredictableTiltComponentProcess_filtered
#print axioms stronglyMeasurable_continuousMeasurableTrajectorySleepingPredictableTiltComponentProcess_ambient
#print axioms stronglyMeasurable_continuousMeasurableTrajectorySleepingPredictableTiltMasterProcess_filtered
#print axioms stronglyMeasurable_continuousMeasurableTrajectorySleepingPredictableTiltMasterProcess_ambient
#print axioms continuousMeasurableTrajectorySleepingPredictableTiltMasterProcess_le
