import FormalSLT.StochasticDynamics.ContinuousTrajectorySleepingCountableTiltPACBayes

open MeasureTheory
open FormalSLT.StochasticDynamics

#check continuousTrajectorySleepingCountableTiltSuffixBoundary
#check continuousTrajectorySleepingCountableTiltSuffixBoundary_eq_constant
#check exists_continuousTrajectorySleepingCountableTiltPACBayes_suffixRisk_event_of_parameterMeasurable
#check continuousTrajectorySleepingGeometricTiltSuffixBoundary
#check exists_continuousTrajectorySleepingGeometricTiltPACBayes_suffixRisk_event_of_parameterMeasurable

#print axioms continuousTrajectorySleepingCountableTiltSuffixBoundary_eq_constant
#print axioms exists_continuousTrajectorySleepingCountableTiltPACBayes_suffixRisk_event_of_parameterMeasurable
#print axioms exists_continuousTrajectorySleepingGeometricTiltPACBayes_suffixRisk_event_of_parameterMeasurable
