import FormalSLT.Applications.ControlledQueueSharpStructuredReceiptCore

open FormalSLT.Applications.ControlledQueue

#check PhysicalTransitionHistogram
#check HasPhysicalTransitionHistogram
#check sharpStructuredHistogramScoreSum
#check sharpStructuredHistogramSquaredScoreSum
#check sharpStructuredHistogramPersistenceHitCount
#check sharpStructuredHistogramScoreBesselQ
#check sharpStructuredHistogramScoreAffinePenalty
#check sharpStructuredHistogramPersistenceBesselQ
#check sharpStructuredHistogramPersistenceAffinePenalty
#check sharpStructuredHistogramRiskUpper
#check sharpStructuredHistogramPersistenceRadiusUpper
#check sharpStructuredHistogramPersistenceBudgetUpper
#check sharpStructuredHistogramResidualUpper
#check sharpStructuredHistogramUpper
#check sharpStructuredReceiptBoundary_evaluation_of_histogram

#print axioms sharpStructuredReceiptBoundary_evaluation_of_histogram
