import FormalSLT.StochasticDynamics.TrajectorySleepingStrategyPACBayes

open FormalSLT.StochasticDynamics

#check sleepingTrajectoryStrategyCatalog
#check sleepingTrajectoryStrategyCatalog_apply_of_lt
#check sleepingTrajectoryStrategyCatalog_apply_of_le
#check sleepingTrajectoryStrategyCatalog_mem_Icc
#check exists_trajectorySleepingStrategyPACBayes_factorized_normalized_selected_event

#print axioms sleepingTrajectoryStrategyCatalog_apply_of_lt
#print axioms sleepingTrajectoryStrategyCatalog_apply_of_le
#print axioms sleepingTrajectoryStrategyCatalog_mem_Icc
#print axioms exists_trajectorySleepingStrategyPACBayes_factorized_normalized_selected_event
