import FormalSLT.StochasticDynamics.ContinuousTrajectoryEmpiricalBernsteinPACBayes

/-!
# Continuous-hypothesis trajectory empirical-Bernstein checks

This audit checks the arbitrary measurable-hypothesis, finite-state trajectory
endpoint.  The public theorem has no `Fintype` assumption on the hypothesis
space: in particular, the final `#check` fixes the hypothesis type to `Real`
while leaving the prior and posterior as arbitrary probability measures.

The endpoint mixes the actual forward predictable-mean e-process over the
prior.  For finite state, coordinatewise hypothesis measurability of the score
now derives joint strong measurability of that parameterized process in both
the time-`n` filtration product and the ambient product sigma algebra.  The
capstone therefore exposes no separate process-measurability assumption.
-/

open MeasureTheory ProbabilityTheory
open FormalSLT.AnytimeValid
open FormalSLT.PACBayes.ContinuousForwardPredictableMeanBesselPACBayes
open FormalSLT.StochasticDynamics

#check continuousForwardPredictableMeanBesselPriorProcess_eProcess
#check continuousForwardPredictableMeanBesselMasterProcess_eProcess
#check continuousForwardPredictableMeanBesselExceptionalEvent_mass_le_delta
#check continuousForwardPredictableMeanBessel_boundaryFailure_mem_exceptionalEvent
#check continuousForwardPredictableMeanBessel_allPosteriors_of_not_mem
#check exists_continuousForwardPredictableMeanBesselPACBayes_event

#check stronglyMeasurable_conditionalTrajectoryRisk_parameter
#check measurableSpace_prod_piLE_le_ambient
#check stronglyMeasurable_observedTrajectoryScore_parameter_prod
#check stronglyMeasurable_conditionalTrajectoryRisk_parameter_prod
#check stronglyMeasurable_continuousTrajectoryLowerProcess_filtered
#check stronglyMeasurable_continuousTrajectoryLowerProcess_ambient
#check continuousTrajectoryPosteriorAverageConditionalRisk
#check continuousTrajectoryPosteriorEmpiricalPrequentialRisk
#check continuousTrajectoryPosteriorHybridBesselPenalty
#check continuousTrajectoryEmpiricalBernsteinPACBayesBoundary
#check exists_continuousTrajectoryEmpiricalBernsteinPACBayes_event

#check (exists_continuousTrajectoryEmpiricalBernsteinPACBayes_event
  (Theta := Real))

#print axioms continuousForwardPredictableMeanBesselPriorProcess_eProcess
#print axioms continuousForwardPredictableMeanBesselMasterProcess_eProcess
#print axioms continuousForwardPredictableMeanBesselExceptionalEvent_mass_le_delta
#print axioms continuousForwardPredictableMeanBessel_boundaryFailure_mem_exceptionalEvent
#print axioms continuousForwardPredictableMeanBessel_allPosteriors_of_not_mem
#print axioms exists_continuousForwardPredictableMeanBesselPACBayes_event
#print axioms stronglyMeasurable_conditionalTrajectoryRisk_parameter
#print axioms stronglyMeasurable_observedTrajectoryScore_parameter_prod
#print axioms stronglyMeasurable_conditionalTrajectoryRisk_parameter_prod
#print axioms stronglyMeasurable_continuousTrajectoryLowerProcess_filtered
#print axioms stronglyMeasurable_continuousTrajectoryLowerProcess_ambient
#print axioms exists_continuousTrajectoryEmpiricalBernsteinPACBayes_event
