import FormalSLT.Applications.GJPBrierMonitorCountableStrategyCertificate

open FormalSLT.Applications.GJPBrierMonitorCountableStrategyCertificate

#check halfTiltStrategy_mem_Icc
#check firstAtomPosterior_isPMF
#check firstAtomPosterior_kl_eq_log_two
#check selectedPosterior_kl_lt_seven_tenths
#check halfTilt_exposure_eq
#check halfTilt_uniformDiscrepancy_eq_zero
#check halfTilt_quadraticPenalty_eq
#check countableStrategySummaryEndpoint
#check countableStrategySummaryEndpoint_lt_oneHundredThirtyOne_thousandths
#check replay_countableBoundary_eq_summary
#check replay_conditionalRisk_lt_oneHundredThirtyOne_thousandths_of_summary
#check replayCountableStrategyRiskEvent
#check replayCountableStrategyRiskEvent_failureMass_le
#check replayPath_conditionalRisk_lt_oneHundredThirtyOne_thousandths

#print axioms firstAtomPosterior_isPMF
#print axioms halfTiltStrategy_mem_Icc
#print axioms firstAtomPosterior_kl_eq_log_two
#print axioms selectedPosterior_kl_lt_seven_tenths
#print axioms halfTilt_exposure_eq
#print axioms halfTilt_uniformDiscrepancy_eq_zero
#print axioms halfTilt_quadraticPenalty_eq
#print axioms countableStrategySummaryEndpoint_lt_oneHundredThirtyOne_thousandths
#print axioms replay_countableBoundary_eq_summary
#print axioms replay_conditionalRisk_lt_oneHundredThirtyOne_thousandths_of_summary
#print axioms replayCountableStrategyRiskEvent_failureMass_le
#print axioms replayPath_conditionalRisk_lt_oneHundredThirtyOne_thousandths
