import FormalSLT.Covering.ContinuousDudleyUnitInterval

/-!
# Continuous Dudley unit-interval checker

This checker records the guarded unit-interval capstone surface.
-/

#check FormalSLT.Covering.ContinuousDudleyUnitInterval.continuous_dudley_entropy_integral_iSup_of_dyadicProfile_guarded
#print axioms FormalSLT.Covering.ContinuousDudleyUnitInterval.continuous_dudley_entropy_integral_iSup_of_dyadicProfile_guarded

#check FormalSLT.Covering.ContinuousDudleyUnitInterval.unitInterval_coverProfile_eq_roundedDyadicGridCoverCount
#print axioms FormalSLT.Covering.ContinuousDudleyUnitInterval.unitInterval_coverProfile_eq_roundedDyadicGridCoverCount

#check FormalSLT.Covering.ContinuousDudleyUnitInterval.continuous_dudley_entropy_integral_iSup_unitInterval
#print axioms FormalSLT.Covering.ContinuousDudleyUnitInterval.continuous_dudley_entropy_integral_iSup_unitInterval

#check FormalSLT.Covering.ContinuousDudleyUnitInterval.unitInterval_entropyProfile_nonconstant
#print axioms FormalSLT.Covering.ContinuousDudleyUnitInterval.unitInterval_entropyProfile_nonconstant

#check FormalSLT.Covering.ContinuousDudleyUnitInterval.unitInterval_entropyProfile_integral_positive
#print axioms FormalSLT.Covering.ContinuousDudleyUnitInterval.unitInterval_entropyProfile_integral_positive

#check FormalSLT.Covering.ContinuousDudleyUnitInterval.unitIntervalDivergingEntropyProfile

#check FormalSLT.Covering.ContinuousDudleyUnitInterval.unitInterval_divergingEntropyProfile_dominates_roundedDyadicEntropy
#print axioms FormalSLT.Covering.ContinuousDudleyUnitInterval.unitInterval_divergingEntropyProfile_dominates_roundedDyadicEntropy

#check FormalSLT.Covering.ContinuousDudleyUnitInterval.unitInterval_divergingEntropyProfile_integral_positive
#print axioms FormalSLT.Covering.ContinuousDudleyUnitInterval.unitInterval_divergingEntropyProfile_integral_positive

#check FormalSLT.Covering.ContinuousDudleyUnitInterval.continuous_dudley_entropy_integral_iSup_unitInterval_diverging
#print axioms FormalSLT.Covering.ContinuousDudleyUnitInterval.continuous_dudley_entropy_integral_iSup_unitInterval_diverging
