import FormalSLT.StochasticDynamics.FiniteTrajectorySleepingSuffixVarianceOracle

open FormalSLT.StochasticDynamics

#check finiteTrajectoryPosteriorSuffixPredictorQuadraticVariation
#check continuousTrajectoryPosteriorSuffixPredictorQuadraticVariation_toPMF
#check finiteTrajectoryPosteriorConstantTiltSuffixPredictorQuadraticPenalty_eq
#check finiteTrajectoryPosteriorSuffixPredictorQuadraticVariation_mem_Icc
#check finiteTrajectorySleepingSuffixVarianceGeometricTiltExcess
#check finiteTrajectorySleepingSuffixVarianceGeometricTiltBoundary
#check continuousTrajectorySleepingSuffixVarianceGeometricTiltExcess_toPMF
#check continuousTrajectorySleepingSuffixVarianceGeometricTiltBoundary_toPMF
#check finiteTrajectorySleepingSuffixVarianceMaxIndex
#check finiteTrajectorySleepingSuffixVarianceFinitePrefixArgmin
#check finiteTrajectorySleepingSuffixVarianceFinitePrefixArgmin_mem
#check finiteTrajectorySleepingSuffixVarianceFinitePrefixArgmin_le
#check finiteTrajectorySleepingSuffixVarianceSelectedExcess
#check finiteTrajectorySleepingSuffixVarianceSelectedBoundary
#check finiteTrajectorySleepingSuffixVarianceSelectedBoundary_le
#check continuousTrajectorySleepingSuffixVarianceSelectedExcess_toPMF
#check continuousTrajectorySleepingSuffixVarianceSelectedBoundary_toPMF
#check finiteTrajectorySleepingSuffixVarianceGrowingPrefixComplexity
#check finiteTrajectorySleepingSuffixVarianceLILEnvelope
#check continuousTrajectorySleepingSuffixVarianceLILEnvelope_toPMF
#check finiteTrajectorySleepingSuffixVarianceSelectedExcess_le_LILEnvelope
#check finiteTrajectorySleepingSuffixVarianceSelectedBoundary_le_LILEnvelope
#check exists_finiteTrajectorySleepingSuffixVarianceOracle_event
#check exists_finitePMFTrajectorySleepingSuffixVarianceOracle_event

#print axioms finiteTrajectoryPosteriorConstantTiltSuffixPredictorQuadraticPenalty_eq
#print axioms finiteTrajectoryPosteriorSuffixPredictorQuadraticVariation_mem_Icc
#print axioms continuousTrajectorySleepingSuffixVarianceGeometricTiltExcess_toPMF
#print axioms finiteTrajectorySleepingSuffixVarianceFinitePrefixArgmin_mem
#print axioms finiteTrajectorySleepingSuffixVarianceFinitePrefixArgmin_le
#print axioms finiteTrajectorySleepingSuffixVarianceSelectedBoundary_le
#print axioms continuousTrajectorySleepingSuffixVarianceSelectedExcess_toPMF
#print axioms finiteTrajectorySleepingSuffixVarianceSelectedExcess_le_LILEnvelope
#print axioms finiteTrajectorySleepingSuffixVarianceSelectedBoundary_le_LILEnvelope
#print axioms exists_finiteTrajectorySleepingSuffixVarianceOracle_event
#print axioms exists_finitePMFTrajectorySleepingSuffixVarianceOracle_event
