import FormalSLT.AlgorithmicStability

/-!
# Algorithmic stability expected-gap audit

Checks the public finite expected-generalization-gap wrappers:

* finite coordinate-swap adapter;
* finite iid product-weight specialization;
* finite two-sided expected-gap wrappers;
* product-measure coordinate swap and measure-theoretic iid expected-gap
  wrappers with explicit integrability assumptions.
-/

#check FormalSLT.AlgorithmicStability.finiteStabilityGeneralizationGap
#check FormalSLT.AlgorithmicStability.expectedFiniteGeneralizationGap

#check FormalSLT.AlgorithmicStability.expectedFiniteGeneralizationGap_eq_expectedFiniteStabilityGap
#print axioms FormalSLT.AlgorithmicStability.expectedFiniteGeneralizationGap_eq_expectedFiniteStabilityGap

#check FormalSLT.AlgorithmicStability.expectedFiniteGeneralizationGap_le_uniformStability_of_coordinateSwap
#print axioms FormalSLT.AlgorithmicStability.expectedFiniteGeneralizationGap_le_uniformStability_of_coordinateSwap

#check FormalSLT.AlgorithmicStability.expectedFiniteGeneralizationGap_le_uniformStability_finiteProduct
#print axioms FormalSLT.AlgorithmicStability.expectedFiniteGeneralizationGap_le_uniformStability_finiteProduct

#check FormalSLT.AlgorithmicStability.neg_beta_le_expectedFiniteStabilityGap_of_coordinateSwap
#print axioms FormalSLT.AlgorithmicStability.neg_beta_le_expectedFiniteStabilityGap_of_coordinateSwap

#check FormalSLT.AlgorithmicStability.abs_expectedFiniteStabilityGap_le_uniformStability_of_coordinateSwap
#print axioms FormalSLT.AlgorithmicStability.abs_expectedFiniteStabilityGap_le_uniformStability_of_coordinateSwap

#check FormalSLT.AlgorithmicStability.abs_expectedFiniteStabilityGap_le_uniformStability_finiteProduct
#print axioms FormalSLT.AlgorithmicStability.abs_expectedFiniteStabilityGap_le_uniformStability_finiteProduct

#check FormalSLT.AlgorithmicStability.neg_beta_le_expectedFiniteGeneralizationGap_of_coordinateSwap
#print axioms FormalSLT.AlgorithmicStability.neg_beta_le_expectedFiniteGeneralizationGap_of_coordinateSwap

#check FormalSLT.AlgorithmicStability.abs_expectedFiniteGeneralizationGap_le_uniformStability_of_coordinateSwap
#print axioms FormalSLT.AlgorithmicStability.abs_expectedFiniteGeneralizationGap_le_uniformStability_of_coordinateSwap

#check FormalSLT.AlgorithmicStability.abs_expectedFiniteGeneralizationGap_le_uniformStability_finiteProduct
#print axioms FormalSLT.AlgorithmicStability.abs_expectedFiniteGeneralizationGap_le_uniformStability_finiteProduct

#check FormalSLT.AlgorithmicStability.sampleCoordinateSwap
#check FormalSLT.AlgorithmicStability.measurePreserving_sampleCoordinateSwap
#check FormalSLT.AlgorithmicStability.integral_sampleCoordinateSwap

#check FormalSLT.AlgorithmicStability.expectedStabilityGap_le_uniformStability_piMeasure
#print axioms FormalSLT.AlgorithmicStability.expectedStabilityGap_le_uniformStability_piMeasure

#check FormalSLT.AlgorithmicStability.abs_expectedStabilityGap_le_uniformStability_piMeasure
#print axioms FormalSLT.AlgorithmicStability.abs_expectedStabilityGap_le_uniformStability_piMeasure

#check FormalSLT.AlgorithmicStability.finiteClass_loss_measurable
#print axioms FormalSLT.AlgorithmicStability.finiteClass_loss_measurable

#check FormalSLT.AlgorithmicStability.boundedLoss_selectedLoss_integrable
#print axioms FormalSLT.AlgorithmicStability.boundedLoss_selectedLoss_integrable

#check FormalSLT.AlgorithmicStability.boundedLoss_updateSelectedLoss_integrable
#print axioms FormalSLT.AlgorithmicStability.boundedLoss_updateSelectedLoss_integrable

#check FormalSLT.AlgorithmicStability.boundedLoss_coordinateSelectedLoss_integrable
#print axioms FormalSLT.AlgorithmicStability.boundedLoss_coordinateSelectedLoss_integrable

#check FormalSLT.AlgorithmicStability.expectedStabilityGap_le_uniformStability_piMeasure_of_boundedLoss
#print axioms FormalSLT.AlgorithmicStability.expectedStabilityGap_le_uniformStability_piMeasure_of_boundedLoss

#check FormalSLT.AlgorithmicStability.abs_expectedStabilityGap_le_uniformStability_piMeasure_of_boundedLoss
#print axioms FormalSLT.AlgorithmicStability.abs_expectedStabilityGap_le_uniformStability_piMeasure_of_boundedLoss
