import FormalSLT

/-!
# Total-bounded Dudley bridge audit

Checks the first topology bridge for the continuous/total-bounded Dudley lane:
turning a totally bounded metric index space into bundled finite nets that can
feed the existing finite chaining infrastructure.
-/

#check FormalSLT.Covering.TotalBoundedDudley.BundledFiniteNet
#print axioms FormalSLT.Covering.TotalBoundedDudley.BundledFiniteNet

#check FormalSLT.Covering.TotalBoundedDudley.finiteMetricCoverOfTotallyBoundedUniv
#print axioms FormalSLT.Covering.TotalBoundedDudley.finiteMetricCoverOfTotallyBoundedUniv

#check FormalSLT.Covering.TotalBoundedDudley.finiteNetOfCoverSet
#print axioms FormalSLT.Covering.TotalBoundedDudley.finiteNetOfCoverSet

#check FormalSLT.Covering.TotalBoundedDudley.finiteNetOfTotallyBoundedUniv
#print axioms FormalSLT.Covering.TotalBoundedDudley.finiteNetOfTotallyBoundedUniv

#check FormalSLT.Covering.TotalBoundedDudley.finiteNetOfTotallyBoundedUniv_covers
#print axioms FormalSLT.Covering.TotalBoundedDudley.finiteNetOfTotallyBoundedUniv_covers

#check FormalSLT.Covering.TotalBoundedDudley.dyadicChainingNetRadius
#print axioms FormalSLT.Covering.TotalBoundedDudley.dyadicChainingNetRadius

#check FormalSLT.Covering.TotalBoundedDudley.dyadicChainingNetRadius_pair_sum_le
#print axioms FormalSLT.Covering.TotalBoundedDudley.dyadicChainingNetRadius_pair_sum_le

#check FormalSLT.Covering.TotalBoundedDudley.dyadicChainingFiniteNetOfTotallyBoundedUniv
#print axioms FormalSLT.Covering.TotalBoundedDudley.dyadicChainingFiniteNetOfTotallyBoundedUniv

#check FormalSLT.Covering.TotalBoundedDudley.dyadicChainingFiniteNetOfTotallyBoundedUniv_covers
#print axioms FormalSLT.Covering.TotalBoundedDudley.dyadicChainingFiniteNetOfTotallyBoundedUniv_covers

#check FormalSLT.Covering.TotalBoundedDudley.dyadicChainingFiniteNetOfTotallyBoundedUniv_pair_radius_le
#print axioms FormalSLT.Covering.TotalBoundedDudley.dyadicChainingFiniteNetOfTotallyBoundedUniv_pair_radius_le

#check FormalSLT.Covering.TotalBoundedDudley.dyadicChainingFiniteNetOfTotallyBoundedUniv_pair_radius_pos
#print axioms FormalSLT.Covering.TotalBoundedDudley.dyadicChainingFiniteNetOfTotallyBoundedUniv_pair_radius_pos

#check FormalSLT.Covering.TotalBoundedDudley.dyadicChainingCoverCount
#print axioms FormalSLT.Covering.TotalBoundedDudley.dyadicChainingCoverCount

#check FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_coveringNumbers
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_coveringNumbers

#check FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_entropy_integral_comparison
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_entropy_integral_comparison

#check FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_entropy_intervalIntegral_comparison
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_entropy_intervalIntegral_comparison

#check FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_projectedNet_dudley_entropy_sum_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison

#check FormalSLT.Covering.TotalBoundedDudley.finite_supFunctional_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_supFunctional_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison

#check FormalSLT.Covering.TotalBoundedDudley.finite_separableSupFunctional_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_separableSupFunctional_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison

#check FormalSLT.Covering.TotalBoundedDudley.finite_witnessedSup_modulus_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_witnessedSup_modulus_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison

#check FormalSLT.Covering.TotalBoundedDudley.EpsilonizedSupremumBoundaryChoice
#check FormalSLT.Covering.TotalBoundedDudley.finite_epsilonizedSup_modulus_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_epsilonizedSup_modulus_dudley_totalBounded_dyadic_entropy_truncatedIntervalIntegral_comparison

#check FormalSLT.Covering.TotalBoundedDudley.skeletonApprox_of_finiteCover_pathwiseModulus
#print axioms FormalSLT.Covering.TotalBoundedDudley.skeletonApprox_of_finiteCover_pathwiseModulus

#check FormalSLT.Covering.TotalBoundedDudley.FiniteCoverSupremumBoundaryChoice

#check FormalSLT.Covering.TotalBoundedDudley.epsilonizedSupremumBoundaryChoice_of_finiteCoverSupremumBoundaryChoice
#print axioms FormalSLT.Covering.TotalBoundedDudley.epsilonizedSupremumBoundaryChoice_of_finiteCoverSupremumBoundaryChoice

#check FormalSLT.Covering.TotalBoundedDudley.finite_epsilonizedSup_dudley_totalBounded_of_finiteCoverSupremumBoundaryChoice
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_epsilonizedSup_dudley_totalBounded_of_finiteCoverSupremumBoundaryChoice

#check FormalSLT.Covering.TotalBoundedDudley.finite_projected_dudley_entropy_sum_totalBounded_dyadic_coveringNumbers
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_projected_dudley_entropy_sum_totalBounded_dyadic_coveringNumbers

#check FormalSLT.Covering.TotalBoundedDudley.dyadicTerminalFiniteNet
#print axioms FormalSLT.Covering.TotalBoundedDudley.dyadicTerminalFiniteNet

#check FormalSLT.Covering.TotalBoundedDudley.dyadicTerminalFiniteNet_pair_radius_le
#print axioms FormalSLT.Covering.TotalBoundedDudley.dyadicTerminalFiniteNet_pair_radius_le

#check FormalSLT.Covering.TotalBoundedDudley.finite_dudley_entropy_sum_totalBounded_dyadic_coveringNumbers
#print axioms FormalSLT.Covering.TotalBoundedDudley.finite_dudley_entropy_sum_totalBounded_dyadic_coveringNumbers
