#!/usr/bin/env bash
#
# repo-stats.sh — single source of truth for the repo size figures the README,
# the theorem-chain SVG, and any reviewer quote against the GitHub page.
#
# It recomputes the Lean module count and total Lean line count from disk using
# exactly the commands a skeptical reader would run, writes them to
# `.stats.json`, and stamps them into the marker-delimited STATS regions of
# `README.md` and `docs/theorem-chain.svg` so the numbers cannot silently drift.
#
# Usage:
#   scripts/repo-stats.sh           # recompute, write .stats.json, stamp files
#   scripts/repo-stats.sh --check   # recompute and FAIL (exit 1) if anything is
#                                   # stale; writes nothing. Use this in CI / the
#                                   # pre-PR checklist to catch drift.
#
# The canonical count commands (kept identical to the audit instructions):
#   modules: find FormalSLT -name "*.lean" | wc -l
#   lines:   find FormalSLT -name "*.lean" -exec cat {} \; | wc -l
set -euo pipefail

# Resolve repo root from this script's location so it works from any cwd.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${ROOT}"

CHECK=0
if [[ "${1:-}" == "--check" ]]; then
  CHECK=1
fi

MODULES="$(find FormalSLT -name '*.lean' | wc -l | tr -d ' ')"
LINES="$(find FormalSLT -name '*.lean' -exec cat {} \; | wc -l | tr -d ' ')"

README="README.md"
SVG="docs/theorem-chain.svg"
STATS_JSON=".stats.json"

MODULES="${MODULES}" LINES="${LINES}" \
README="${README}" SVG="${SVG}" STATS_JSON="${STATS_JSON}" CHECK="${CHECK}" \
python3 - <<'PY'
import os, re, sys, json

modules   = os.environ["MODULES"]
lines     = os.environ["LINES"]
check     = os.environ["CHECK"] == "1"
readme    = os.environ["README"]
svg       = os.environ["SVG"]
stats_json = os.environ["STATS_JSON"]

# Thousands-separated line count for prose (e.g. 20789 -> 20,789).
lines_human = f"{int(lines):,}"

# The exact strings stamped between the STATS markers in each file.
README_STATS = f"**{modules} Lean modules. {lines_human} lines of Lean. Zero `sorry`. Zero `admit`. Zero custom axioms.**"
SVG_STATS    = f"{modules} Lean modules · {lines_human} lines · zero sorry · zero admit · axioms: propext, Classical.choice, Quot.sound"

drift = []

def restamp(path, replacement):
    """Replace the text between STATS:BEGIN and STATS:END markers."""
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    pat = re.compile(r"(<!--\s*STATS:BEGIN[^>]*-->)(.*?)(<!--\s*STATS:END\s*-->)", re.DOTALL)
    m = pat.search(text)
    if not m:
        sys.stderr.write(f"error: STATS markers not found in {path}\n")
        sys.exit(2)
    current = m.group(2).strip()
    want = replacement.strip()
    if current != want:
        drift.append(f"{path}: stale STATS region\n    have: {current}\n    want: {want}")
    new = text[:m.start(2)] + "\n" + replacement + "\n" + text[m.end(2):]
    if not check and new != text:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(new)

restamp(readme, README_STATS)
restamp(svg, SVG_STATS)

# .stats.json is fully regenerated; compare semantically for --check.
payload = {
    "lean_modules": int(modules),
    "lean_lines": int(lines),
    "_note": "Generated by scripts/repo-stats.sh. Do not edit by hand.",
}
existing = None
if os.path.exists(stats_json):
    try:
        with open(stats_json, encoding="utf-8") as fh:
            existing = json.load(fh)
    except Exception:
        existing = None
if existing != payload:
    if existing is None:
        drift.append(f"{stats_json}: missing or unreadable")
    else:
        drift.append(f"{stats_json}: stale (have {existing.get('lean_modules')}/{existing.get('lean_lines')}, want {modules}/{lines})")
    if not check:
        with open(stats_json, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, indent=2)
            fh.write("\n")

if check:
    if drift:
        sys.stderr.write("repo-stats: DRIFT DETECTED — run scripts/repo-stats.sh to fix:\n")
        for d in drift:
            sys.stderr.write("  - " + d + "\n")
        sys.exit(1)
    print(f"repo-stats: in sync ({modules} modules, {lines} lines)")
else:
    print(f"repo-stats: stamped {modules} modules, {lines} lines into {readme}, {svg}, {stats_json}")
PY
